### ISSUE TITLE
ERROR: bench 5.0.0 has requirement setuptools

### ISSUE THREAD

**Issue by aykou** [frappe/bench#1014]
Issue: Bug report

ERROR: bench 5.0.0 has requirement setuptools==40.8.0, but you'll have setuptools 47.1.1 which is incompatible.

**Do the checklist before filing an issue:**
 - [ ] Can you replicate the issue?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:

**To Reproduce** :page_with_curl:
1. python3 install.py --production

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [ ] Linux: `distro:version`
- [ ] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder

- Bench Branch: `master` _(Only master is supported)_
- Frappe Version:
- ERPNext Version:

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem.

**Comment by gavindsouza** [comment]
```
ERROR: bench 5.0.0 has requirement setuptools==40.8.0, but you'll have setuptools 47.1.1 which is incompatible.
```

That's a "harmless" error raised by pip. It shouldn't affect your environment directly. Just means that you have `47.1.1` installed on your system globally and bench requires `40.8.0`. If this raises any issues on your system, feel free to raise them here.
