### ISSUE TITLE
Replace platform.dist() with distro.linux_distribution in install.py | platform.dist() not supported by python3.8

### ISSUE THREAD

**Issue by nikunj1222** [frappe/bench#1016]
Issue: Easy Install

**Distro Information (Required)**

Ubuntu 20.04 LTS
And for all new distros in future

**Possible Solution**

To replace **Replace platform.dist() with distro.linux_distribution in install.py**

Use this module https://github.com/nir0s/distro for getting distro/system verion information.

I will try to cook something myself. But I am not a professional programmer. So if anybody can work on this request.

**Comment by nikunj1222** [comment]
#1019 

Check this pull request to manage the installation on ubuntu 20.04

**Comment by gavindsouza** [comment]
Fixed with https://github.com/frappe/bench/pull/1048
