### ISSUE TITLE
Rates are not coming in Rejection Store and Purchase Return

### ISSUE THREAD

**Issue by ruchin78** [frappe/bench#102]
I have received an item from the vendor and few quantity of the same I have rejected at the time of purchase receipt also I have selected the rejection store for the purpose rejection.
Now the problem is this, when I actually rejected the quantity system didn't transferred the rates in the rejection store therefore the rates are not coming in the purchase return.
I am using ERPNext: v4.24.2
I request you to please resolve this issue in this version as well as in Version 5

**Comment by pdvyas** [comment]
Please make this issue in the erpnext repository, https://github.com/frappe/erpnext/issues
