### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'Nonetype' and 'list'

### ISSUE THREAD

**Issue by AbdelilahDerfoufi** [frappe/bench#1027]
Issue: Bug repoI can't use any commad bench without getting this error. 

Traceback (most recent call last):
  File "home/username/.local/bin/bench", line 11,in <module>
   load_entry_point('frappe-bench', 'console_scripts', 'bench')()
 File "home/username/bench/bench/cli.py", line 45,in cli
if sys.argv[1] in get_frappe_commands() + ["--site", "--verbose", "--force","--profile"]:
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

OS: Linux ubuntu 16.04
python 2.7.12

![image](https://user-images.githubusercontent.com/49759161/85269687-2519b500-b470-11ea-8b36-1c6a22bef906.png)

**Comment by gavindsouza** [comment]
it's likely that frappe wasn't installed during the `bench init` process or it could be that it got deleted after. Try installing frappe in your `{frappe-bench}/env` again. Else try creating another bench and find out why frappe failed to install

**Comment by AbdelilahDerfoufi** [comment]
> it's likely that frappe wasn't installed during the `bench init` process or it could be that it got deleted after. Try installing frappe in your `{frappe-bench}/env` again. Else try creating another bench and find out why frappe failed to install

I managed to make it work, at the end, but my virtual image crashed so i had to reinstall it again, but the same problem appeared and I don't remember how I fixed it the last time.

![image](https://user-images.githubusercontent.com/49759161/90497573-21886e80-e13f-11ea-8d70-9cb3668adbbe.png)

**Comment by Alchez** [comment]
@AbdelilahDerfoufi, what Python version are you on? I've seen this happen on Python2.7, not sure about the fix either.

**Comment by AbdelilahDerfoufi** [comment]
@Alchez Yes, and I tried on python 3.6, and it shows that database.tabDefaultValue or something like that is missing.
So I'm stuck

**Comment by Alchez** [comment]
Weird, can you try re-installing (`bench reinstall`) or restoring the site with a backup (`bench restore`)? Might be a corrupted database.

**Comment by gavindsouza** [comment]
> @Alchez Yes, and I tried on python 3.6, and it shows that database.tabDefaultValue or something like that is missing.
So I'm stuck

@AbdelilahDerfoufi your site wasn't created properly. Try creating one again

**Comment by AbdelilahDerfoufi** [comment]
@gavindsouza I tried it, but I still get the same error.

**Comment by gavindsouza** [comment]
@AbdelilahDerfoufi if this is a db error, this isn't the same issue anymore and it comes under frappe, so open an issue under its repo. try updating your branches and try again. 

I'm closing this issue now

**Comment by AbdelilahDerfoufi** [comment]
@gavindsouza Right now, it's the Nonetype error that keeps showing up. So I'm still struggling with it.

**Comment by gavindsouza** [comment]
@AbdelilahDerfoufi can you uninstall the editable install completely and try it out again with the PyPI package. Use `pip3 install frappe-bench` to install it.

**Comment by AbdelilahDerfoufi** [comment]
@gavindsouza I should use use sudo apt remove bench , right ?

**Comment by gavindsouza** [comment]
@AbdelilahDerfoufi No, bench is always only managed by `pip`. Checkout [this discuss post](https://discuss.erpnext.com/t/warn-bench-is-installed-in-editable-mode-why-i-cant-run-bench-commend-i-am-getting-this-error/63246/10?u=gavindsouza).

**Comment by AbdelilahDerfoufi** [comment]
@gavindsouza so I should remove the egg file .

**Comment by gavindsouza** [comment]
@AbdelilahDerfoufi and the bench folder, too.

**Comment by AbdelilahDerfoufi** [comment]
@gavindsouza I followed that link but now this new error shows up.

![image](https://user-images.githubusercontent.com/49759161/90758893-9abac980-e2d7-11ea-96e3-227cbe31f610.png)

**Comment by gavindsouza** [comment]
go through the wrapper script and replace the python version or site packages path where bench is installed. 

 or

rm $(which bench) and run pip install -U frappe-bench again

if you have followed my previous comment and used pip3, your wrapper script is trying to fetch a Py2 package instead

**Comment by AbdelilahDerfoufi** [comment]
@gavindsouza I used pip3. So $(which bench) will get my current verion of bench ?

**Comment by AbdelilahDerfoufi** [comment]
@gavindsouza 

![image](https://user-images.githubusercontent.com/49759161/90767674-7ebe2480-e2e5-11ea-9880-eb5a5ed63113.png)

It worked, at least I hope, now what ?
