### ISSUE TITLE
The resource you are looking for is not available

### ISSUE THREAD

**Issue by almarkae** [frappe/bench#1033]
when i updated my erpnext to new version via VB I faced the up problem 

 
![بدون عنوان](https://user-images.githubusercontent.com/49963545/86530472-940bfa80-bec1-11ea-9488-ec6c0bd81870.png)
Issue: Bug report

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue?
 - [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:

**To Reproduce** :page_with_curl:

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [ ] Linux: `distro:version`
- [ ] macOS: `version`
- [x] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder

- Bench Branch: `master` _(Only master is supported)_
- Frappe Version:
- ERPNext Version:

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem.

**Comment by gavindsouza** [comment]
Seems like you're running out of memory.

Ref: https://stackoverflow.com/questions/26193654/node-js-catch-enomem-error-thrown-after-spawn
