### ISSUE TITLE
Error during installation according to documentation

### ISSUE THREAD

**Issue by wegyang** [frappe/bench#1042]
![image](https://user-images.githubusercontent.com/69234013/89378755-19840400-d727-11ea-8c26-98cb722105ae.png)

I follow the installation document step by step, and the result is an error！What is the reason and how to solve it！！thanks！！！

**Comment by gavindsouza** [comment]
The [Installation Document](https://github.com/frappe/bench/blob/develop/docs/installation.md) does not provide a step by step guide. What documentation are you referring to? 

Anyway, this seems like a permission error. Do you have permission to write in the current directory you're in?

**Comment by wegyang** [comment]
> The [Installation Document](https://github.com/frappe/bench/blob/develop/docs/installation.md) does not provide a step by step guide. What documentation are you referring to?
> 
> Anyway, this seems like a permission error. Do you have permission to write in the current directory you're in?

>According to 'https://github.com/frappe/bench/blob/develop/README.md'   
There is no problem following the document operation in the front, but there is a problem in the https://github.com/frappe/bench/wiki/Setting-up-a-Mac-for-Frappe-ERPNext-Development#setting-up-frappe-bench-1 

>I think the permission should be no problem ...

**Comment by ghulamostafa** [comment]
You can check this guideline for a step by step installation and run for Production
http://ghulamustafa.com/2020/09/15/how-to-install-erpnext-on-ubuntu-20-04/

**Comment by justmejust** [comment]
make sure where did you installed bench and execute bench --version there

**Comment by gavindsouza** [comment]
Closing as this now outdated and inactive.
