### ISSUE TITLE
Install specific version of erpnext via frappe

### ISSUE THREAD

**Issue by opnoack** [frappe/bench#105]
Is it possible to install a specific version of erpnext via frappe? At the moment it seems like the latest version is installed. We would like to be able to pin our installation scripts to specific versions.

**Comment by somo82** [comment]
This is a very sound request. Specially when choosing between major releases like V4 and V5. Even though V5 is awesome, I may choose to install V4 for stability or users request reasons. By install here I mean the "Easy Install Script".

**Comment by pdvyas** [comment]
Sorry for the late reply.

You can pin to v4, with `bench switch-to-v4`

**Comment by opnoack** [comment]
Thanks for the reply @pdvyas. That's a good start, but isn't it possible to specify the exact version that I want to install? That would be great!

**Comment by pdvyas** [comment]
Not at the moment

But you can 
```
cd apps/frappe
git reset --hard v{version_no}
cd apps/erpnext
git reset --hard v{version_no}
```

**Comment by istvano** [comment]
Hi Guys,

I am building docker version of erpnext. I want to tie the dicker image to a specific Erp Next version.

I am happy to change the setup_frappe.sh script but I would need some guidance. 
What would be the best approach to do this as it seems . 

it is possible to pass BRANCH parameter
run_cmd sudo su $FRAPPE_USER -c "cd /home/$FRAPPE_USER && bench init frappe-bench --frappe-branch $FRAPPE_BRANCH --apps_path $ERPNEXT_APPS_JSON"

Although the git checkout command is inside the get_app method in bench which is hardcoded to checkout branches. 

Would it be possible to add a new feature to the get_app to also wotk with TAGs ?
Something like

bench init frappe-bench --frappe-tag $FRAPPE_TAG--apps_path $ERPNEXT_APPS_JSON"

Can someone help me out on this one ? 

Thanks a lot
