### ISSUE TITLE
certbot-auto will fail on ubuntu > 20

### ISSUE THREAD

**Issue by JeansReal** [frappe/bench#1073]
Issue: Bug report

https://github.com/certbot/certbot/issues/7941#issuecomment-619177149

> We're planning on deprecating certbot-auto later this year though so we're not going to add support for Ubuntu 20.04 to it.

**To Reproduce**
`$ sudo -H bench setup lets-encrypt site1.local`

**Screenshots** :crystal_ball:
![Screenshot from 2020-09-18 15-32-34](https://user-images.githubusercontent.com/6005082/93646835-3f5a2500-f9c4-11ea-9f02-17ee76c0e05e.png)

**OS:**:
Ubuntu Server 20.04 LTS

**Version Information**:
Bench 5.2.1
Frapee: version-13-beta

**Possible Solution** :bookmark_tabs:
On ubuntu < 20 its possible fixing the issue running:
USE_PYTHON_3=1 /opt/certbot-auto 

This forces certbot-auto to run using python 3.
But this does not work on Ubuntu 20.04LTS

**Comment by gavindsouza** [comment]
> USE_PYTHON_3=1 /opt/certbot-auto

I think we should do this for now. Can you raise a PR for this?

**Comment by abdouz** [comment]
Any updates about this issue? I still get the same errors on Ubuntu 20.04

**Comment by gavindsouza** [comment]
Should be fixed by https://github.com/frappe/bench/pull/1303 and released via 5.9.0
