### ISSUE TITLE
install bench from github (fatal: unable to access 'https://github/frappe/erpnext.git/': Could not resolve host: github)

### ISSUE THREAD

**Issue by justmejust** [frappe/bench#1074]
while trying  to clone erpnext from github 
i got this
$ bench get-app --branch version-12 https://github/frappe/erpnext.git
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

Getting erpnext
$ git clone https://github/frappe/erpnext.git --branch version-12 --depth 1 --origin upstream
Cloning into 'erpnext'...
**fatal: unable to access 'https://github/frappe/erpnext.git/': Could not resolve host: github**

any one had faced same issue or any suggestion pleae

**Comment by hammerstick** [comment]
Your bench command `bench get-app --branch version-12 https://github/frappe/erpnext.git` has a typo. Try putting `.com` at the end of `https://github`

**Comment by justmejust** [comment]
Your bench command bench get-app --branch version-12 https://github/frappe/erpnext.git has a typo. Try putting .com at the end of https://github
> Your bench command `bench get-app --branch version-12 https://github/frappe/erpnext.git` has a typo. Try putting `.com` at the end of `https://github`

yes thats right thank you@hammerstick
