### ISSUE TITLE
I have an issue when i use easy install

### ISSUE THREAD

**Issue by MahmoudRadwan1** [frappe/bench#1076]
Issue: Easy Install

Could not find aptitude. Using apt-get instead

**Comment by msalim79** [comment]
Has the install stopped , it should have just carried on.

**Comment by MahmoudRadwan1** [comment]
What is the solution now?

**Comment by msalim79** [comment]
The install will carry on , even though you see that message, it’s an
informative message.
If you are still having issues , post the errors you are getting and we’ll
try to assist you.

Regards
Salim

**Comment by MahmoudRadwan1** [comment]
Done
