### ISSUE TITLE
Backup creates empty database

### ISSUE THREAD

**Issue by danielchalmers** [frappe/bench#1089]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:

`bench backup` creates a zipped empty database every time.
The `.gz` archive is 20B and the unzipped `.sql` file itself is 0B.

I found this issue because the backups being uploaded by the S3 Backup tool were tiny.

**To Reproduce** :page_with_curl:

```
$ cd ~/frappe-bench
~/frappe-bench$ bench backup
~/frappe-bench$ ls -lh sites/*/private/backups/
-rw-rw-r-- 1 frappe frappe   20 Oct 10 00:43 20201010_004337-mysite-database.sql.gz
-rw-rw-r-- 1 frappe frappe  378 Oct 10 00:43 20201010_004337-mysite-site_config_backup.json
```

**Expected behavior** :chart_with_upwards_trend:

A database backup that's the same size as before upgrading.

Pre-upgrade: `20201009_000025-mysite-database.sql.gz` = 11.4MB, ERPNext version 11
Post-upgrade: `20201010_004337-mysite-database.sql.gz` = 20B, ERPNext 13.0.0-beta.4

**OS:** :cyclone:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

**Version Information**

```
$ bench version
erpnext 13.0.0-beta.4
frappe 13.0.0-beta.5

$ mysql -V
mysql  Ver 15.1 Distrib 10.5.6-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

**Comment by gavindsouza** [comment]
Does it work for you via `bench --site name backup` or from the `/desk#backups`?
I can't seem to replicate this on the `version-13-beta` or the `develop` branch

**Comment by danielchalmers** [comment]
Just tried `bench --site mysite backup`. It behaves the same as `bench backup`.
Runs for about a second then it's done, with nothing written to the console.

Here's what my `/desk#backups` looks like:
![image](https://user-images.githubusercontent.com/7112040/95951429-05f6b880-0dbc-11eb-9c56-c14595c72399.png)

**Comment by danielchalmers** [comment]
Not sure if this would help but here's the listing of `~/frappe-bench/sites/mysite/private/backups`:

```
frappe@erpnext:~/frappe-bench$ ls -l sites/mysite/private/
total 12
drwxr-xr-x 2 frappe frappe 18 Oct 14 01:30 backups
drwxrwxr-x 2 frappe frappe  4 Oct 11 00:13 files

frappe@erpnext:~/frappe-bench$ ls -l sites/mysite/private/backups/*.sql.gz
-rw-r--r-- 1 frappe frappe 20 Oct 14 00:00 sites/mysite/private/backups/20201014_000047-mysite-database.sql.gz
-rw-rw-r-- 1 frappe frappe 20 Oct 14 01:20 sites/mysite/private/backups/20201014_012006-mysite-database.sql.gz
-rw-r--r-- 1 frappe frappe 20 Oct 14 01:24 sites/mysite/private/backups/20201014_012447-mysite-database.sql.gz
```

The first backup was a scheduled one done by S3 Backup, the second was done through SSH, and the third was from the `Download Files Backup` button. Strangely the write permissions are different on the second one.

**Comment by gavindsouza** [comment]
Try it with verbose, (or|and) check out the `develop` branch too.

**Comment by danielchalmers** [comment]
Verbose is the same (blank), but switching to `develop` fixed it 👍.

```
erpnext 13.x.x-develop
frappe 13.x.x-develop

-rw-rw-r-- 1 frappe frappe  13M Oct 14 13:27 20201014_132724-mysite-database.sql.gz
-rw-rw-r-- 1 frappe frappe  354 Oct 14 13:27 20201014_132724-mysite-site_config_backup.json
```

Sorry, I should have tried that first! Thank you!

**Comment by rohansh-tty** [comment]
I am facing this exact same issue, where my db backup is a byte sized file. I am using frappe version 13.15. 
```
frappe 13.15.0
bench 5.6.0
```
