### ISSUE TITLE
Multiple Cancellation/Assignment/Submit etc.

### ISSUE THREAD

**Issue by ruchin78** [frappe/bench#109]
I have one suggestion that there should be a way by which user can cancel/assign/submit multiple documents in one go.

Like for e.g., I have 200 Material Request and I want to cancel all therefore as per current feature I have to open each and everyone and press cancel button.

My opinion is system should raise error for the request which have some problem to cancel and leave them but user should be able to cancel the all in one go.

Same should be applied to
Assigned To
Submit

**Comment by pdvyas** [comment]
Please make an issue at https://github.com/frappe/erpnext/issues
This is bench
