### ISSUE TITLE
lets-encrypt cronjob

### ISSUE THREAD

**Issue by renehauck** [frappe/bench#1090]
Hi, first of all thank you very much for the great work! 

I have installed erpnext via bench on ubuntu 18.04 After everything worked wonderfully, I wanted to install a certificate via `sudo -H bench setup lets-encrypt my.site.com`.
This also works fine, but I have a question about one thing:
In the docu of you is the sentence 

> This command will also add an entry to the crontab of the user that will attempt to renew the certificate every month

But if I enter the command `crontab -l` in the console, I only get the following result:
```
0 */6 * * * cd /home/frappe/bench && /usr/local/bin/bench --verbose --site all backup >> /home/frappe/bench/logs/backup.log 2>&1 # bench auto backups set for every 6 hours

```

Do I get something wrong or is the cronjob not started?

Thank you!

**Comment by gavindsouza** [comment]
@renehauck We've changed where the cronjob is set in v5.x, now it gets set up under root's crontab. The docs you're referring to are outdated and will be fixed. 

Thank you for raising this.
