### ISSUE TITLE
Material Issue

### ISSUE THREAD

**Issue by ArmanRipon** [frappe/bench#1098]
Backdated Stock Entry
Last Stock Transaction for item Cement under warehouse Raw Materials - BRL was on 2020-11-13 16:36:53.953821.

Stock Transactions for Item Cement under warehouse Raw Materials - BRL cannot be posted before this time.

Please remove this item and try to submit again or update the posting time.

**Comment by hasnain2808** [comment]
@ArmanRipon this does not look like a valid https://github.com/frappe/bench issue.
If it is an [ERPNext](https://github.com/frappe/erpnext) please create an issue here -  https://github.com/frappe/erpnext. You can also post on the Discuss Forum.
