### ISSUE TITLE
certbot-auto deprecated 

### ISSUE THREAD

**Issue by dnyt84** [frappe/bench#1105]
Issue: Bug report

Ubuntu 20.04.1 LTS and Ubuntu 18.04.5 LTS

bench version
erpnext 13.x.x-develop
frappe 13.x.x-develop
I just did a bench update as well 

I followed the Guide on 
https://frappeframework.com/docs/user/en/bench/guides/lets-encrypt-ssl-setup

```
sudo -H bench setup lets-encrypt domain.com
Running this will stop the nginx service temporarily causing your sites to go offline
Do you want to continue? [y/N]: y
$ sudo systemctl stop nginx
$ /opt/certbot-auto  --config /etc/letsencrypt/configs/domain.com.cfg certonly
Skipping bootstrap because certbot-auto is deprecated on this system.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.
nginx.conf already exists and this will overwrite it. Do you want to continue? [y/N]: n
```

**Possible Solution** :bookmark_tabs:
I followed this guide here and was able to install the cert. It does install certbot instead of certbot-auto but the command otherwise is the same.

**Comment by barredterra** [comment]
Todo: Update bench to [uninstall certbot-auto](https://certbot.eff.org/docs/uninstall.html) and [install certbot](https://certbot.eff.org/docs/install.html).

**Comment by barredterra** [comment]
### Workaround

Install certbot:

```bash
sudo apt-get install certbot
```

Stop NGINX webserver, create certificates, start NGINX
webserver:

```bash
sudo systemctl stop nginx
sudo certbot --standalone --agree-tos --domain erp.example.org -n -m mail@example.org certonly
sudo systemctl start nginx
```

Add the following lines to your `frappe-bench/sites/erp.example.org/site_config.json`:

```json
{
    "ssl_certificate": "/etc/letsencrypt/live/erp.example.org/fullchain.pem",
    "ssl_certificate_key": "/etc/letsencrypt/live/erp.example.org/privkey.pem"
}
```

Regenerate the NGINX configuration and reload nginx:

```bash
bench setup nginx
sudo service nginx reload
```

**Comment by josmeldiaz21** [comment]
Hi, I have some questions about it.

I had a server and the letsencrypt was renewing perfectly, then I had the same issue with certbot-auto. 

This workaround works with a server with the certbot-auto already installed?

and it will renew the ssl certificate automatically?

**Comment by victor-abz** [comment]
ANy update on this? I am having the same problem

**Comment by mubeenmazhar** [comment]
any update?

**Comment by barredterra** [comment]
@josmeldiaz21 you'll have to remove certbot-auto, it's not supported anymore. Automatic renewal was not included in my workaround, but you can set it up manually. Please check the [certbot website](https://certbot.eff.org/lets-encrypt/ubuntubionic-nginx) for detailed instructions.
