### ISSUE TITLE
Testing only in Localhost can create problem

### ISSUE THREAD

**Issue by Talismanic** [frappe/bench#1107]
Greetings,
I am an engineer who is interested in infrastructure as code testing. Currently, I am looking for testing anti-patterns in iac test scripts. I noticed Local-only Testing occurring in test instances. This can give happy test results in the local environment but in a real production system test can fail due to the difference in the environment. My recommendation is to test IaC code in an isolated non-local environment which needs to be similar to the production environment.

So I have the following queries:

Do you agree that this is an IaC testing anti-pattern?
Do you want to fix this?

Any feedback is appreciated.

Source Files:
https://github.com/frappe/bench/blob/develop/bench/playbooks/roles/nginx/tests/test.yml

**Comment by gavindsouza** [comment]
I'm a year and a half late but I don't understand the proposal or rather the bug. If you're still interested, we'd need a lot more details to consider this.
