### ISSUE TITLE
Develop branch has lower version number than 5.x branch

### ISSUE THREAD

**Issue by kisg** [frappe/bench#1114]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:

When running bench from the develop branch it shows the message that an upgrade is available from 5.2.1 to 5.3.0. Checking the code it seems that the bench version in 5.x branch got updated by the semantic versioning bot after the latest merge from the develop branch, but the same was not done in the develop branch.

**Expected behavior** :chart_with_upwards_trend:

The develop branch should always have a version equal or greater than the current release version.

**Possible Solution** :bookmark_tabs:

It might make sense to create a special develop version e.g. 5.x-dev in the develop branch. When bench version is run on such a version, the git commit id would be included in the version output to help with debugging. When a merge from develop to 5.x is done, this version number would not be merged but the semantic versioning bot would update the release version according to its rules.

If you agree with this proposal, I would be happy to send a PR.

**Comment by hasnain2808** [comment]
Hi @kisg ,

Thanks for bringing our attention to this inconsistency.

So the semantic release command can be run locally in debug mode to get the next release version without actually releasing it.

So when we merge develop to 5.x semantic release creates a new version and then pushes it.

This commit gets pushed only to the 5.x branch and not develop.

Hence the develop branch does not have the correct version.

Will the suggested PR help solving this too?

**Comment by kisg** [comment]
Basically my proposal would be the following:
- The develop branch would have a special version, e.g. 5.x-dev. This would be regarded as always greater than the 5.[0-9].[0-9] version by the bench code, so it does not offer an upgrade. To know the exact version, the commit id could be included in the bench output.
- There would be a Github action that prevents the merging of a PR to the release branch that updates the version in bench/__init__.py
- There would be another Github action that makes sure that no breaking change is allowed in a PR targeting the 5.x branch because that would cause the release version to become 6.x.y, and that should not be done on the 5.x branch.

If you decide to introduce a breaking change, then first the base version needs to be changed in the develop branch to 6.x-dev, then the new 6.x branch set up with the appropriate Github workflows similar to the 5.x branch.

After the 6.x branch is created, only fix commits are allowed to the 5.x branch (hopefully only backports of the fixes on the develop branch).

What do you think?

**Comment by hasnain2808** [comment]
@kisg 
This sounds like a good plan.

My suggestion would be to create a PR for the first point separately. Since it's important to get it fixed soon. And then we can work on the other two points.

Thanks

**Comment by gavindsouza** [comment]
Fixed via https://github.com/frappe/bench/pull/1138
