### ISSUE TITLE
Installation fail: Wrong pip version.

### ISSUE THREAD

**Issue by rtdany10** [frappe/bench#1119]
Issue: Easy Install

```
root@ERP-Update:~# export LC_ALL=C.UTF-8
root@ERP-Update:~# python3 install.py --production --user frappe
Logs are saved under /tmp/logs/easy-install__2021-02-10__05-14.log
Checking System Compatibility...
ubuntu 18 is compatible!
curl already installed!
wget already installed!
git already installed!
pip3 already installed!
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xtg0iged/cryptography/
Traceback (most recent call last):
  File "install.py", line 436, in <module>
    install_prerequisites()
  File "install.py", line 143, in install_prerequisites
    'python3': "sudo -H python3 -m pip install --upgrade setuptools cryptography ansible==2.8.5 pip"
  File "install.py", line 118, in run_os_command
    returncode = subprocess.check_call(command, shell=True, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo -H python3 -m pip install --upgrade setuptools cryptography ansible==2.8.5 pip' returned non-zero exit status 1.
root@ERP-Update:~# sudo -H python3 -m pip install --upgrade setuptools cryptography ansible==2.8.5 pip
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/15/0e/255e3d57965f318973e417d5b7034223f1223de500d91b945ddfaef42a37/setuptools-53.0.0-py3-none-any.whl
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/27/5a/007acee0243186123a55423d49cbb5c15cb02d76dd1b6a27659a894b13a2/cryptography-3.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4lu4bgnu/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4lu4bgnu/cryptography/
```

**Possible Solution**
```
python3 -m pip install --upgrade pip

**Comment by rtdany10** [comment]
I believe upgrading pip3 using the install.py everytime would solve the issue.

Same issue raised by another user at frappe/easy_install#19

**Comment by onepaanplus** [comment]
Hi,

I have encountered the same issues, already tried the code but still an error.
> python3 -m pip install --upgrade pip

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

**Comment by rtdany10** [comment]
> Hi,
> 
> I have encountered the same issues, already tried the code but still an error.
> 
> > python3 -m pip install --upgrade pip
> 
> DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.

Why are you using Python 2.7?

Try
```
sudo apt-get install python3-pip
sudo pip3 install --upgrade pip

**Comment by onepaanplus** [comment]
Actually already done with 

> python3 -m pip install --upgrade pip

This error comes out.

_**WARNING: The directory '/home/frappe/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pip in ./.local/lib/python3.6/site-packages (21.0.1)**_
===============================================================================
Done this command.
sudo pip3 install --upgrade pip

Error

> WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
> Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
> To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
> WARNING: The directory '/home/frappe/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
> Requirement already satisfied: pip in ./.local/lib/python3.6/site-packages (21.0.1)

This is the log for sudo 

_sudo sudo python3 install.py --production --version 12_

> Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
> Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease
> Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease
> Hit:4 https://deb.nodesource.com/node_12.x bionic InRelease
> Hit:5 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.4/ubuntu bionic InRelease
> Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
> Get:7 http://ftp.ubuntu-tw.org/mirror/mariadb/repo/10.3/ubuntu xenial InRelease [4641 B]
> Fetched 93.4 kB in 1s (75.3 kB/s)
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> build-essential is already the newest version (12.4ubuntu1).
> libffi-dev is already the newest version (3.2.1-8).
> python3-setuptools is already the newest version (39.0.1-2).
> git is already the newest version (1:2.17.1-1ubuntu0.7).
> python3-dev is already the newest version (3.6.7-1~18.04).
> The following packages were automatically installed and are no longer required:
>   galera-3 libaio1 libcgi-fast-perl libcgi-pm-perl libencode-locale-perl
>   libfcgi-perl libhtml-parser-perl libhtml-tagset-perl libhtml-template-perl
>   libhttp-date-perl libhttp-message-perl libio-html-perl
>   liblwp-mediatypes-perl libtimedate-perl liburi-perl mariadb-server-core-10.3
>   socat
> Use 'sudo apt autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
> Collecting setuptools_rust
>   Using cached https://files.pythonhosted.org/packages/e5/e3/ede8b8545e7ce7f5fde88d1a89cdfffa281ab3b93815c3c1a464ca3b6855/setuptools_rust-0.11.6-py3-none-any.whl
> Collecting wheel
>   Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
> Collecting cryptography
>   Using cached https://files.pythonhosted.org/packages/27/5a/007acee0243186123a55423d49cbb5c15cb02d76dd1b6a27659a894b13a2/cryptography-3.4.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-rp39acvl/cryptography/setup.py", line 14, in <module>
>         from setuptools_rust import RustExtension
>     ModuleNotFoundError: No module named 'setuptools_rust'
> 
>             =============================DEBUG ASSISTANCE==========================
>             If you are seeing an error here please try the following to
>             successfully install cryptography:
> 
>             Upgrade to the latest pip and try again. This will fix errors for most
>             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
>             =============================DEBUG ASSISTANCE==========================
> 
> 
>     ----------------------------------------
> Install script run at 08:02 on 2021-02-10

**Comment by onepaanplus** [comment]
Do i need to change anything on install.py for these line?

_'python3': "sudo -H python3 -m pip install --upgrade setuptools wheel cryptography ansible~=2.8.15 pip"_

**Comment by onepaanplus** [comment]
Manage to install using these commands.

```
sudo apt-get install python3-pip
sudo pip3 install --upgrade pip
```

but now a new error happens as below.

```
Logs are saved under /tmp/logs/easy-install__2021-02-10__08-17.log
curl already installed!
wget already installed!
git already installed!
pip3 already installed!
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
pip3 already installed!
Checking System Compatibility...
ubuntu 18 is compatible!
Not cloning already existing Bench repository at /tmp/.bench
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
Input MySQL and Frappe Administrator passwords:
Passwords saved at ~/passwords.txt
Initializing bench frappe-bench:
        Frappe Branch: version-12
        ERPNext Branch: version-12
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Consider using the get_url or uri module rather than running 'curl'.  If you need to use command because get_url or uri is insufficient you can add 'warn: false' to this command task or set 'command_warnings=False' in
ansible.cfg to get rid of this message.
Traceback (most recent call last):
  File "install.py", line 489, in <module>
    install_bench(args)
  File "install.py", line 275, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 405, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.
```

**Comment by rtdany10** [comment]
> but now a new error happens as below.

This error usually happens when an install attempt failed once and you retry(from my experience).
There are lot of issues(open and closed) about this error. Try solutions mentioned in them.
Lets not merge both in this issue.

**Comment by manasan3010** [comment]
> python3 -m pip install --upgrade pip

Please update the README at https://github.com/frappe/bench#easy-install-script to include this command during the installation
