### ISSUE TITLE
bench new-site site1.local --force throws a my.cnf related issue "for key collation_server expect value utf8mb4_unicode_ci found value utf8mb4_general_ci

### ISSUE THREAD

**Issue by q-omar** [frappe/bench#1139]
**Issue: Bug report**

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - PyPI [latest](https://pypi.org/project/frappe-bench/) 

I did `pip3 install frappe-bench`

**Describe the bug** :chart_with_downwards_trend:
Does not execute `bench new-site site1.local` properly. 

**To Reproduce** :page_with_curl:
1. After doing `pip3 install frappe-bench`, go to `cd frappe-bench`
2. Do `bench start`
3. Open new tab in same folder
4. Do `bench new-site site1.local`
5. Throws
```
For key collation_server. Expected value utf8mb4_unicode_ci, found value utf8mb4_general_ci
================================================================================
Creation of your site - site1.local failed because MariaDB is not properly
configured.  If using version 10.2.x or earlier, make sure you use the
the Barracuda storage engine.

Please verify the settings above in MariaDB's my.cnf.  Restart MariaDB.  And
then run `bench new-site site1.local` again.


================================================================================
Database settings do not match expected values; stopping database setup.
```
6. Go to `cd sites`
7. Remove newly created sites folder `rm -rf site1.local`
8. Going back to `cd ..` and doing `bench new-site site1.local` returns same error

**Expected behavior** :chart_with_upwards_trend:
Not sure, haven't gotten that far.

**Screenshots** :crystal_ball:
[link](https://imgur.com/0YxVtoB.png)

**OS (please complete the following information):** :cyclone:
- [x] macOS: `11.2.2

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.3.0
- Frappe Version: latest because I did `pip3 install frappe-bench`
- ERPNext Version: n/a

**Additional context** :page_facing_up:
Some stuff I tried is running `mariadb --help` command to locate where my `my.cnf` file is. For me it was located in `/usr/local/etc/my.cnf`. I also noticed another `my.cnf` file called `my.cnf.default`. I edited this file to have same config as regular `my.cnf` file. 

I think there is some file on my system that is overwriting this for whatever reason.

**Comment by ankush** [comment]
This does not look like bug. Follow this guide to properly setup mariadb configuration:

https://frappeframework.com/docs/user/en/installation#macos

**Comment by q-omar** [comment]
I followed the guide correctly to my knowledge. Here is the file contents for my.cnf: 

```
#
# This group is read both by the client and the server
# use it for options that affect everything
#
[client-server]

#
# include *.cnf from the config directory
#
#!includedir /usr/local/etc/my.cnf.d
[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[mysql]
default-character-set = utf8mb4
```

**Comment by q-omar** [comment]
Actually interestingly enough after restarting my computer everything worked 😅.

**Comment by ankush** [comment]
Oh, I guess you just needed to restart mariadb after changing conf.
