### ISSUE TITLE
bench new-app --no-git

### ISSUE THREAD

**Issue by revant** [frappe/bench#1173]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**

bench new-app creates a new git repo

**Describe the solution you'd like**

`bench new-app --no-git app_name` should create app with no git repo.

**Describe alternatives you've considered**

```shell
bench new-app app_name
rm -rf apps/app_name/.git
```

**Comment by phot0n** [comment]
implemented in https://github.com/frappe/bench/pull/1218
