### ISSUE TITLE
CLI: Bench level Operation locking

### ISSUE THREAD

**Issue by gavindsouza** [frappe/bench#1176]
**Is your feature request related to a problem? Please describe.**

Multiple instances of the same or conflicting operations shouldn't be allowed to trigger via bench.

**Describe the solution you'd like**

A file-based lock should be taken by a process before starting a particular type of process. If another instance is started via a different session, it should either wait or exit saying that there's a similar process doing the same thing at `{this}` PID. The locks should be taken at bench level for bench operations. In case of site operations _(handled by Frappe)_, a lock for the same should be taken.

**Eg:** If `bench build` is being run on a particular bench, another instance of the same operation shouldn't be allowed to trigger until the current one is complete.

**Comment by ankush** [comment]
Should be possible with https://github.com/frappe/frappe/pull/19133 :smile:

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/19162 

`bench build` was fixed here. Not sure of any other commands that need it. 




Added one more here: https://github.com/frappe/frappe/pull/25340 

can't think of any other right now.
