### ISSUE TITLE
Refactor bench version code

### ISSUE THREAD

**Issue by saxenabhishek** [frappe/bench#1183]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
The code that handles the `--version` argument is an example from click's documentation even though Click recommends using their implementation.
https://click.palletsprojects.com/en/8.0.x/options/#callbacks-and-eager-options

**Describe the solution you'd like**
to Use click's implementation of the  `--version` parameter to keep code clean.

**Comment by gavindsouza** [comment]
No reason to change the output format at this point. Closing this as there doesn't seem to be any benefit from doing so
