### ISSUE TITLE
Please Update Wiki for MacOS - MariaDB my.cnf Does Not Affect Defaults

### ISSUE THREAD

**Issue by JeffArwady** [frappe/bench#1188]
When following the Wiki - Setting up a Mac for Frappe ERPNext Development - I try to install a new site with bench.  When doing so I get the following error after running **bench new-site jeffdev.local**:

**Error Start**
For key collation_server. Expected value utf8mb4_unicode_ci, found value utf8mb4_general_ci

Creation of your site - jeffdev.local failed because MariaDB is not properly 
configured.  If using version 10.2.x or earlier, make sure you use the 
the Barracuda storage engine. 

Please verify the settings above in MariaDB's my.cnf.  Restart MariaDB.  And 
then run `bench new-site jeffdev.local` again.

Database settings do not match expected values; stopping database setup.
**Error End**

I have the following code in my /usr/local/etc/my.cnf file as indicated in the wiki

[mysqld]
character-set-client-handshake = FALSE
character-set-server = utf8mb4
collation-server = utf8mb4_unicode_ci

[mysql]
default-character-set = utf8mb4

I made sure to use the following command to restart mariadb:
**brew services restart mariadb**

When running the command:
**mysqladmin -u root -p var | grep -E 'character|collation' | tr -s ' '**

I see this

| character_set_client | utf8mb4 |
| character_set_connection | utf8mb4 |
| character_set_database | utf8mb4 |
| character_set_filesystem | binary |
| character_set_results | utf8mb4 |
| character_set_server | utf8mb4 |
| character_set_system | utf8 |
| character_sets_dir | /usr/local/Cellar/mariadb/10.5.11/share/mysql/charsets/ |
**| collation_connection | utf8mb4_general_ci |
| collation_database | utf8mb4_general_ci |
| collation_server | utf8mb4_general_ci |**
| session_track_system_variables | autocommit,character_set_client,character_set_connection,character_set_results,time_zone |

So I can certainly see why my new-site is not working as the defaults for collation are **general** not **unicode** as the my.cnf file specifies.

I have no idea why changing my.cnf does not affect the defaults but that is immaterial.  The fact is the Wiki, when followed, does not lead to a functional result.  I am requesting that someone please try a fresh install per the Wiki and then update the Wiki so that it may be followed correctly.

**Comment by arwadyj** [comment]
This issue seems to have resolved itself.  Closing this issue.

**Comment by safwansamsudeen** [comment]
I have the same problem too. How did you fix this?

**Comment by JeffArwady** [comment]
I didn't as I never got a response. I ended up abandoning frappe on my Mac in favor of a hosted Linux install of frappe that I could run on my Mac via the remote ssh plugin in vs code. 

It's very annoying that they say it works on a Mac given the Maria db issues. I really hope they update their documentation to either exclude Mac support, or tell us exactly how to make it work with the current version of Maria db. In any case, save yourself a lot of time and trouble and run frappe on Linux instead.

**Comment by swamymysore** [comment]
Hi I faced this issue tried everything from all the top solutions I could find on internet, it did not resolve.
### Following changes resolved my issue and finally Frappe app is running and creating new sites for me without issues.

```
nano /usr/local/etc/my.cnf.default

Added the following:
[mysqld]
innodb-read-only-compressed=OFF
```


Saved and quit

brew services restart mariadb@10.3

bench new-site <site name>

bench --site <site name> install-app frappe

bench --site <site name> add-to-hosts;

now you can go to your browser and <site name>:8000 will bring up the frappe app

This may help with other apps too built on frappe.

**Comment by JeffArwady** [comment]
@swamymysore - Thanks very much for following up on this thread!  I am not currently using my Mac for frappe development, however if I do try that approach again, I'm sure your fix will help make that work.

**Comment by safwansamsudeen** [comment]
Hi,
I did use Frappe on my Mac, and I wrote a [blog post](https://safwan-samsudeen.medium.com/setting-up-frappe-bench-on-mac-problems-faced-with-solutions-5100a9a72656) on how I solved the error. I too set `innodb-read-only-compressed` to `OFF`, though I had to set the collation server before that. It worked.

**Comment by swamymysore** [comment]
Jeff

Thank you for responding.

**Comment by swamymysore** [comment]
Hi Safwan

Thank you.
I tried setting that in my.cnf and for some reason mariadb used to stop
working. Everything worked once I moved that parameter to my.cnf.default
