### ISSUE TITLE
No doctype dirs

### ISSUE THREAD

**Issue by Madko** [frappe/bench#119]
I'm trying to follow this tutorial https://frappe.io/tutorial/doctype-directory-structure everything went almost smoothly, but I don't have the doctype directory structure. Is it normal?

[frappe@localhost library_management]$ tree
 .
├── config
│   ├── desktop.py
│   ├── desktop.pyc
│   ├── __init__.py
│   └── __init__.pyc
├── hooks.py
├── hooks.pyc
├── __init__.py
├── __init__.pyc
├── library_management
│   ├── __init__.py
│   └── __init__.pyc
├── modules.txt
├── patches.txt
├── templates
│   ├── generators
│   │   └── __init__.py
│   ├── includes
│   ├── __init__.py
│   └── pages
│       └── __init__.py
└── www

**Comment by pdvyas** [comment]
Can you post this on discuss.frappe.io? Also, I think you made a "custom"
doctype (which do not make the directories)

**Comment by Madko** [comment]
Will try without the "custom", but it is shown in the screenshots of the tutorial, custom is checked.
Thanks for your help Pratik. Will post that on discuss.frappe.io
