### ISSUE TITLE
Invalid syntax error.

### ISSUE THREAD

**Issue by rtdany10** [frappe/bench#1193]
`sudo bench setup supervisor` failing with traceback:
```
Traceback (most recent call last):
  File "/usr/bin/bench", line 7, in <module>
    from bench.cli import cli
  File "/usr/lib/python2.7/site-packages/bench/cli.py", line 67
    logger.warning(f"{command} executed with exit code {return_code}")
                                                                    ^
SyntaxError: invalid syntax
```

In fact, any command that didn't run successfully shows this traceback. Making it impossible to know the reason of failure.

`bench --version` outputs `5.5.0`

**Comment by rtdany10** [comment]
Tried checking python version via bench console. It's 3.6.8
```
In [1]: import sys

In [2]: sys.version
Out[2]: '3.6.8 (default, Nov 16 2020, 16:55:22) \n[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]'
```

The error log doesn't make sense. The path points to `python2.7`

**Comment by rtdany10** [comment]
https://github.com/frappe/bench/issues/1194#issuecomment-908048849

I guess bench should by default use python3 if `--python` flag isn't passed on `init` command.

**Comment by gavindsouza** [comment]
> `sudo bench setup supervisor` failing with traceback:

seems like you have bench installed on PY2 for the root user.

> I guess bench should by default use python3 if `--python` flag isn't passed on `init` command.

Agree with this. First we should search for `python3` in PATH, then `python` as fallback.

**Comment by rtdany10** [comment]
> Agree with this. First we should search for `python3` in PATH, then `python` as fallback.

I just checked the init command's code, it defaults to python3 everywhere.
Seems probably like some issue on my side. Still unsure why it was installed on PY2. Maybe make PY3 a requirement and not install the bench otherwise?

**Comment by gavindsouza** [comment]
> Maybe make PY3 a requirement and not install the bench otherwise?

The minimum requirement is `PY3.6` now. Which version of bench can be installed is dictated by pip at this point. The only way I know to reliably install the latest compatible version is by:

```bash
pip3 install -U frappe-bench --only-binary='all'
```

I'm not sure if there's any other way.
