### ISSUE TITLE
Unable to remove app from bench

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/bench#1198]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:
Unable to remove app from bench. Bench says the app is installed on site x. When I try to uninstall app from site x I get error the app is not installed.

**To Reproduce** :page_with_curl:
1. bench init --frappe-branch version-13 frappe-bench
2. bench get-app // All other apps
3. create site directory
4. copy old site files into new site directory
5. create current_site.txt, and add site_name
6. bench --site site_name restore ~/path_to_db_backup
7. bench --site site_name migrate
8. bench --site site_name uninstall_app app_name (Success uninstalled)
9. bench remove-app app_name (Fail see screen shot)

**Expected behavior** :chart_with_upwards_trend:
The app should be removed from env and apps folder.

**Screenshots** :crystal_ball:
![image](https://user-images.githubusercontent.com/29856401/132950996-ed53d76d-e255-437b-9753-139399886caf.png)

**OS (please complete the following information):** :cyclone:
Linux: `Ubuntu:18.04`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.5.0

**Comment by dj12djdjs** [comment]
Here is another example of some error: https://discuss.erpnext.com/t/cant-remove-app/68226

**Comment by gavindsouza** [comment]
Use `--force ` to uninstall app from site, and try again?

**Comment by dj12djdjs** [comment]
I just deleted all the app files from the app directory and removed the lines in apps.txt manually. Seems to have worked.

**Comment by dj12djdjs** [comment]
I just ran into same problem on another bench. So I'm keeping this open.
Also the --force command did not fix the problem.

**Comment by gavindsouza** [comment]
it's probably getting the app name in the globals set in the site. For that, there's `bench --site {site} remove-from-installed-apps {app}`. 

Anyway, this is still a problem. Probably with `uninstall-app` in Frappe and `remove-app` in Bench, and will require further investigation.

**Comment by dj12djdjs** [comment]
@gavindsouza I will try remove-from-installed-apps command.
I found some additional information. This only occurs after migrating from original server to secondary server.
I updated my original post with the steps to reproduce. Maybe I migrated incorrectly?

**Comment by dj12djdjs** [comment]
I haven't been able to re-replicate this since my original posting. I'm thinking it was caused by installing the bench, the site, and the apps in the wrong order. I'm not sure, but it hasn't happened on any of my future migrations so I'm gonna close this.
