### ISSUE TITLE
Install bench via pip3

### ISSUE THREAD

**Issue by akitibala** [frappe/bench#1203]
Issue: Bug report

python3 version : 3.5.2

**To Reproduce** :page_with_curl:
Steps to reproduce the behavior and Installation i followed these steps for ubuntu:
1. [frappe link] (https://frappeframework.com/docs/user/en/installation#debian-ubuntu)
2. [bench cli] (https://frappeframework.com/docs/user/en/installation#install-bench-cli)

**OS (please complete the following information):** :cyclone:
`ubuntu version : 16.0.4`

I attached a screenshot here:
<img width="424" alt="frappe" src="https://user-images.githubusercontent.com/33974086/135983465-bfb8c866-884d-4b46-8e2b-cd1ab59a4a1e.png">

**Comment by Alchez** [comment]
@akitibala, Frappe has dropped support for Python versions below 3.6. You will need to upgrade to 3.6 or higher and try again.

**Comment by gavindsouza** [comment]
Python 3.5 has reached end of life in September 2020. Latest bench versions require at least `PY3.6`.  
Ref: https://www.python.org/downloads/release/python-3510/

To install a version compatible with your Python version, run the following command:

```bash
pip3 install -U frappe-bench --only-binary='all'
```
