### ISSUE TITLE
bench setup lets-encrypt [site] fails due to 404 when downloading certbot-auto

### ISSUE THREAD

**Issue by skjbulcher** [frappe/bench#1206]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:
`bench setup lets-encrypt` fails due to a 404 when fetching certbot-auto

During the lets-encrypt install process, the URL bench uses to retrieve `certbot-auto` is no longer available and produces a 404 (https://dl.eff.org/certbot-auto): 
https://github.com/frappe/bench/blob/8b0d522b639575e0fd651ddcd5cd5ab6b91d43c4/bench/config/lets_encrypt.py#L109

The failure causes `bench setup lets-encrypt` to fail without producing output. Examining `bench/logs/bench.log` shows output similar to the following:

```
2021-10-18 20:49:00,619 DEBUG sudo systemctl stop nginx
2021-10-18 20:49:00,683 WARNING /usr/local/bin/bench setup lets-encrypt [SITE] executed with exit code 404
```

**Expected behavior** :chart_with_upwards_trend:
`bench setup lets-encrypt` should succeed or log that it failed in stderr.

**OS (please complete the following information):** :cyclone:
- [ ] Linux: `ubuntu:20.04`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: see https://github.com/frappe/bench/blob/8b0d522b639575e0fd651ddcd5cd5ab6b91d43c4/bench/config/lets_encrypt.py#L109

**Additional context** :page_facing_up:
Related: https://github.com/frappe/bench/issues/1105

**Comment by gavindsouza** [comment]
There was a PR https://github.com/frappe/bench/pull/1152 that aimed to fix this but it was never completed.
