### ISSUE TITLE
error on easy install on ubuntu 20.04 not clean server

### ISSUE THREAD

**Issue by AliShaatani** [frappe/bench#1207]
Issue: Easy Install
I'm using AWS ubuntu 20.04 and currently running Virtualmin 

when using the easy installation on the clean server it's working okay, but after I installed Virtualmin, I got that error 
if the Virtualmin is conflicting with some libraries, I want to know which ones, 
cuz eventually, i want to run both of them Virtualmin  and ERPNEXT

ubuntu@ip xx.xxx.xx.x$ sudo python3 install.py --production --version 13 
Logs are saved under /tmp/logs/easy-install__2021-10-19__13-41.log
curl already installed!
wget already installed!
git already installed!
pip3 already installed!
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
WARNING: Running pip as the 'root' user can result in broken permissions and conflicing behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecation                              Warning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
pip3 already installed!
Checking System Compatibility...
ubuntu 20 is compatible!
Not cloning already existing Bench repository at /tmp/.bench
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'
Input MySQL and Frappe Administrator passwords:
Please enter mysql root password:
Re-enter mysql root password:
Please enter the default Administrator user password:
Re-enter Administrator password:
Passwords saved at ~/passwords.txt
Initializing bench frappe-bench:
        Frappe Branch: version-13
        ERPNext Branch: version-13
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'
Traceback (most recent call last):
  File "install.py", line 500, in <module>
    install_bench(args)
  File "install.py", line 281, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 416, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, sderr=sys.stderr)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.ym', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=darko']' returned non-zero exit status 2.

**Comment by AliShaatani** [comment]
the conflict was from mariaDB server,

**Comment by smitz96** [comment]
Could you elaborate how you solved this issue?
