### ISSUE TITLE
Run the install script issue

### ISSUE THREAD

**Issue by agrameshprasath** [frappe/bench#1209]
i am using ubuntu 16.04 LTS
while i run the install script , i received  error, anyone help me please.

**2. Run the install script**

**If you are on a fresh server and logged in as root, use --user flag to create a user and install using that user

python install.py --develop --user frappe**

----------------error at the end-----------------

[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'

PLAY [localhost] **********************************************************************

TASK [Gathering Facts] ****************************************************************
ok: [localhost]

TASK [Create user] ********************************************************************
ok: [localhost]

TASK [Set home folder perms] **********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/home/ramesh/.config/chromium/c2btech-10678'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_RxL92X/ansible_module_file.py\", line 473, in <module>\n    main()\n  File \"/tmp/ansible_RxL92X/ansible_module_file.py\", line 350, in main\n    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\n  File \"/tmp/ansible_RxL92X/ansible_module_file.py\", line 172, in recursive_set_attributes\n    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed, expand=False)\n  File \"/tmp/ansible_RxL92X/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1507, in set_fs_attributes_if_different\n  File \"/tmp/ansible_RxL92X/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1164, in set_owner_if_different\n  File \"/tmp/ansible_RxL92X/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1059, in user_and_group\nOSError: [Errno 2] No such file or directory: '/home/ramesh/.config/chromium/c2btech-10678'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/tmp/.bench/playbooks/create_user.retry

PLAY RECAP ****************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 100, in install_bench
    run_playbook('create_user.yml', extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'create_user.yml', '-e', '@/tmp/extra_vars.json']' returned non-zero exit status 2
You have new mail in /var/mail/root

**Comment by gavindsouza** [comment]
This issue seems to be a bit out of date. Closing since the script has changed significantly since and there's no way to replicate this now 😅
