### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by gavindsouza** [frappe/bench#1219]
The current one hasn't been changed since 2018 (via https://github.com/frappe/bench/pull/551). So, along with all the new changes introduced via #1208, a logo change is long due. 

Current Logo
---

<img src="https://raw.githubusercontent.com/frappe/design/master/logos/png/bench-logo.png" width=180 height=180/>

New Logos
---

![bench-logo-minimal-blue](https://user-images.githubusercontent.com/36654812/143925094-e95bc8ab-c392-43e3-aa30-e4a8620f811e.png)

![bench-logo-minimal](https://user-images.githubusercontent.com/36654812/143925171-f567c2e5-ecbb-4d6b-9bdb-e1f1acfc0fd8.png)

I prefer the green, the blue keeps with the Frappe themes (?) but looks pretty bland. Also, the terminal element is sorta missing there.

**Comment by gavindsouza** [comment]
For consistency with the Frappe branding, we built a logo with a white terminal:

![bench-logo-white-blue](https://user-images.githubusercontent.com/36654812/144035327-71c173ab-19b5-4c55-9a62-946955df3097.png)

**Comment by marination** [comment]
With BG Shadows for visibility?
![bench-logo-white-blue-shadow](https://user-images.githubusercontent.com/25857446/144040647-b3fe42ab-2666-4d4a-a817-c9bc2fddaeb3.png)
