### ISSUE TITLE
Error when doing bench update

### ISSUE THREAD

**Issue by hameedacpa** [frappe/bench#1225]
Issue: Bug report

When doing bench update when the new version coming up the following message came 
1. Merge the frappe app manually with "git pull" / "git pull --rebase" and fix conflicts.
1. Temporarily remove your changes with "git stash" or discard them completely
	with "bench update --reset" or for individual repositories "git reset --hard"
2. If your changes are helpful for others, send in a pull request via GitHub and
	wait for them to be merged in the core.

I reviewed different topics, and they suggested doing the following:
    1.Go to the directory, either frappe-bench/apps/erpnext or frappe-bench/apps/frappe
    2.Type git status
    3.Check the list of the untracked files. There might be files, which do or don’t belong there.
    4.Type git add --all to track those files
    5.Type git stash
    6.Run bench update
    7.It should run successfully, if not, start over with 1. and repeat for the other directory

when I'm doing the above steps I found the problem located in the file ((( frappe/www/_test/assets/__init__.py )))
Now I have to do the above steps everytime I'm updating ERPNext 

Please do something for this issue, it is annoying me.

**Comment by ankush** [comment]
Do `bench update --reset` if you're not actually changing anything in code...? 🤔 
Much simpler that way. If you're changing things in code then we can't magically decide what to stash/remove for you.

**Comment by hameedacpa** [comment]
I done before bench update --reset but problem not permanently solved, By the way I didn't change anything in code

**Comment by ankush** [comment]
`bench update --reset` wipes all local changes so it should move ahead with upgrade regardless of local changes and reset it to original code from frappe. 

> when I'm doing the above steps I found the problem located in the file ((( frappe/www/_test/assets/init.py )))


Did you may be open and saved this file thus adding a newline? `__init__.py` is just an empty file

**Comment by hameedacpa** [comment]
No I didn't open any file for any kind of development 
I like to use the original ERPNext as it is 
I'm auditor in UAE not a developer.

**Comment by hameedacpa** [comment]
I have tried again doing `bench update --reset ` as you recommend, but the same issue came to me 
the file name __init__.py is existed under /bench/erpnext/apps/frappe/frappe/www/_test/assets
by the way, the __init__.py file is empty when I reviewed it
the error come after `bench update` is:

> Cannot proceed with update: You have local changes in app "frappe" that are not committed.
> 
> Here are your choices:
> 
> 1. Merge the frappe app manually with "git pull" / "git pull --rebase" and fix conflicts.
> 1. Temporarily remove your changes with "git stash" or discard them completely
> 	with "bench update --reset" or for individual repositries "git reset --hard"
> 2. If your changes are helpful for others, send in a pull request via GitHub and
> 	wait for them to be merged in the core.
>
![2021-12-07_17-17-36](https://user-images.githubusercontent.com/84820402/145037406-dfe15383-c6c6-4221-8d9b-967832015fe3.png)

**Comment by hameedacpa** [comment]
Reopen again

**Comment by ankush** [comment]
That file actually exists on `develop` branch. It's not getting created or modified, so it's not the issue. `git diff` might help find actual changes in your local directory. 


ref: https://github.com/frappe/frappe/blob/develop/frappe/www/_test/assets/__init__.py

**Comment by hameedacpa** [comment]
What can I do to help in fixing this bug, We like your software, and really we want to report our findings to you to make it better

**Comment by ankush** [comment]
@hameedacpa can you share output of `git branch` and `git status` inside frappe directory.

**Comment by hameedacpa** [comment]
@ankush  I updated to version 13.17.0 and before updating to the latest version I got the same error and I have done the same process described above which is (git add --all and  git stash)
anyway I have done the bench update again (after updating to 13.17.0) and everything working fine, and I think you already removed in version 13.17.0 the file init.py which may cause this issue 
The result after updating to version 13.17.0 of git branch:
`version-13`
The result after updating to version 13.17.0 of git status:
```
On branch version-13
Your branch is up to date with 'upstream/version-13'.
nothing to commit, working tree clean
```
It will be preferable to don't close the issue till the next update and if everything fine I'll inform here about this to close the issue 
Thanks

**Comment by hameedacpa** [comment]
@ankush I tried to do `bench update` to update to version 13.17.1 from 13.17.0 but the error is coming again as follow:
```
Updating apps source...


Cannot proceed with update: You have local changes in app "erpnext" that are not committed.

Here are your choices:

1. Merge the erpnext app manually with "git pull" / "git pull --rebase" and fix conflicts.
1. Temporarily remove your changes with "git stash" or discard them completely
	with "bench update --reset" or for individual repositries "git reset --hard"
2. If your changes are helpful for others, send in a pull request via GitHub and
	wait for them to be merged in the core.
```

Also when doing git status the result will be as follow:
```
user@server-VirtualBox:/opt/bench/erpnext/apps/frappe$ git status
On branch version-13
Your branch and 'upstream/version-13' have diverged,
and have 33799 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	frappe/www/_test/assets/__init__.py

nothing added to commit but untracked files present (use "git add" to track)
```

The result of git branch
```
user@server-VirtualBox:/opt/bench/erpnext/apps/frappe$ git branch
* version-13
```

**Comment by hameedacpa** [comment]
@ankush Another error coming in different place 

```
user@server-VirtualBox:/opt/bench/erpnext/apps/erpnext$ git status
On branch version-13
Your branch is up to date with 'upstream/version-13'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	erpnext/www/shop-by-category/__init__.py

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by ankush** [comment]
This has nothing to do with bench it seems. `__init__.py` needs to be checked in source control.

**Comment by put3r-r00t3r** [comment]
I can also attest to this issue recurring every "bench update". The two files are:
frappe-bench/apps/frappe/frappe/www/_test/assets/__init__.py
frappe-bench/apps/erpnext/erpnext/www/shop-by-category/__init__.py

git branch: version-13

My workaround recently has been to delete these files, which are empty files anyway.  How about adding these files to .gitignore in the source? I tried doing this myself in frappe-bench/apps/erpnext/.gitignore and frappe-bench/apps/frappe/.gitignore but then git status says .gitignore is modified.

**Comment by put3r-r00t3r** [comment]
@hameedacpa Did you ever find a solution for this? I did find this workaround that seems to be working for me:

**Comment by ankush** [comment]
Closing this now as I've added all missing `__init__.py` files. Let us know if this happens again in next update. 

Also this isn't a bench problem, Framework is adding init files in prod.
