### ISSUE TITLE
Bench get-app always use github.com even if we use different git server such as gitlab

### ISSUE THREAD

**Issue by rvbd** [frappe/bench#1228]
Issue: Bug report

To reproduce, run bench get-app (anything from gitlab) 

An error, will appear: 
fatal: unable to access 'https://github.com/git@gitlab.com:....

Looking at the codes it seems that the remote_server is set to github.com but I can't find where it's actually set to a custom url.
Therefore when running bench get-app from anything other than gitlab it just don't work anymore.

Apology of course if I'm not using the command right, however this was working a while ago, last known working version was 5.0.0-dev.

Thanks a lot for your help.

**Comment by phot0n** [comment]
seems hardcoded https://github.com/frappe/bench/blob/cbf30b4e6a77132bb242606e1d3b3367fab4f3ee/bench/app.py#L62

https://github.com/frappe/bench/blob/cbf30b4e6a77132bb242606e1d3b3367fab4f3ee/bench/app.py#L116-L133

**Comment by ankush** [comment]
https://github.com/frappe/bench/pull/1227 should fix it. Not closing for now (till release + addition of tests)

**Comment by Alchez** [comment]
@ankush Actually, the remote server is still hardcoded to `github.com`, even if you use SSH URLs (line 133 in the previous comment). The change for this issue would be a different PR that detects the host from the given URL, I think.

**Comment by ankush** [comment]
Release might take some time, for now I'd suggest downgrading to `5.6.0`

**Comment by TurkerTunali** [comment]
We also faced this issue. A workaround is here https://discuss.erpnext.com/t/bench-get-app-bitbucket-requires-github-account/83495?u=turkertunali
