### ISSUE TITLE
use updated URL for wkhtmltopdf downloads

### ISSUE THREAD

**Issue by ashkulz** [frappe/bench#123]
Hello,

wkhtmltopdf has [moved the downloads provider](https://groups.google.com/d/msg/wkhtmltopdf-general/wZwTUol3mXI/GNVeyrKDdqIJ) from SourceForge to gna.org. As mentioned in the linked message, all earlier downloads have been removed from SourceForge and you are strongly advised to migrate to the new URLs. The following files in your repository will need to be updated:

* install_scripts/setup_frappe.sh

It is recommended to either subscribe to the [mailing list](https://groups.google.com/forum/#!forum/wkhtmltopdf-general) or [Twitter feed](https://twitter.com/wkhtmltopdf) to receive updates on new releases and further changes.

Thanks,
wkhtmltopdf maintainer

**Comment by anandpdoshi** [comment]
@ashkulz Thanks a lot for notifying us. Though I am curious–how did you find out that we were using wkhtmltopdf?

**Comment by ashkulz** [comment]
@anandpdoshi: ran a script which searched github repositories for `sourceforge` and `wkhtmltox`, downloaded the metadata of all repositories via API which matched and notified all repositories which seemed to be having users (i.e. having forks, stars, issues enabled, etc) by creating an issue via the API.

**Comment by anandpdoshi** [comment]
That's awesome :). Thanks again.
