### ISSUE TITLE
Easy Install issue with python3.8 

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/bench#1240]
Issue: Easy Install

TASK [bench : python3 bench init for production] **********************************************************************************************************************************************************
task path: /tmp/.bench/bench/playbooks/roles/bench/tasks/main.yml:44
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p " echo /var/tmp "&& mkdir /var/tmp/ansible-tmp-1640021988.9975839-122700-191766143225741 && echo ansible-tmp-1640021988.9975839-122700-191766143225741=" echo /var/tmp/ansible-tmp-1640021988.9975839-122700-191766143225741 " ) && sleep 0'
Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/commands/command.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-118810hd67ruu1/tmpvu2iii28 TO /var/tmp/ansible-tmp-1640021988.9975839-122700-191766143225741/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'setfacl -m u:erpnext:r-x /var/tmp/ansible-tmp-1640021988.9975839-122700-191766143225741/ /var/tmp/ansible-tmp-1640021988.9975839-122700-191766143225741/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n  -u erpnext /bin/sh -c '"'"'echo BECOME-SUCCESS-sjqhwpigspujysmpkgxigrsxohvkfbvn ; /usr/bin/python3 /var/tmp/ansible-tmp-1640021988.9975839-122700-191766143225741/AnsiballZ_command.py'"'"' && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/tmp/ansible-tmp-1640021988.9975839-122700-191766143225741/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "bench",
        "init",
        "/home/erpnext/frappe-bench",
        "--frappe-path",
        "https://github.com/frappe/frappe",
        "--frappe-branch",
        "version-13",
        "--python",
        "python3"
    ],
    "delta": "0:00:00.394418",
    "end": "2021-12-20 19:39:49.799462",
    "invocation": {
        "module_args": {
            "_raw_params": "bench init /home/erpnext/frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13 --python python3",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": "/home/erpnext/frappe-bench",
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2021-12-20 19:39:49.405044",
    "stderr": "Traceback (most recent call last):\n  File \"/usr/bin/bench\", line 33, in <module>\n    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())\n  File \"/usr/bin/bench\", line 22, in importlib_load_entry_point\n    for entry_point in distribution(dist_name).entry_points\n  File \"/usr/lib/python3.8/importlib/metadata.py\", line 503, in distribution\n    return Distribution.from_name(distribution_name)\n  File \"/usr/lib/python3.8/importlib/metadata.py\", line 177, in from_name\n    raise PackageNotFoundError(name)\nimportlib.metadata.PackageNotFoundError: frappe-bench",
    "stderr_lines": [
        "Traceback (most recent call last):",
        "  File \"/usr/bin/bench\", line 33, in <module>",
        "    sys.exit(load_entry_point('frappe-bench', 'console_scripts', 'bench')())",
        "  File \"/usr/bin/bench\", line 22, in importlib_load_entry_point",
        "    for entry_point in distribution(dist_name).entry_points",
        "  File \"/usr/lib/python3.8/importlib/metadata.py\", line 503, in distribution",
        "    return Distribution.from_name(distribution_name)",
        "  File \"/usr/lib/python3.8/importlib/metadata.py\", line 177, in from_name",
        "    raise PackageNotFoundError(name)",
        "importlib.metadata.PackageNotFoundError: frappe-bench"
    ],
    "stdout": "",
    "stdout_lines": []
}

PLAY RECAP ******************************************************************************************************************************************************************************

**Comment by nomi-gee** [comment]
i fixed it by
`sudo pip3 uninstall setuptools`
`sudo pip3 install setuptools==59.6.0`
`sudo pip3 install -e /home/erp/.bench/`

**Comment by mohsinalimat** [comment]
Let me try

**Comment by mohsinalimat** [comment]
> i fixed it by
> `sudo pip3 uninstall setuptools`
> `sudo pip3 install setuptools==59.6.0`
> `sudo pip3 install -e /home/erp/.bench/`

Nice, Thanks, It works.

**Comment by arthurokonkwo** [comment]
I get this error after running

`sudo pip3 install -e /home/erp.bench/`

chiefklar@server1:~$ sudo pip3 install -e /home/erp/.bench/
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
ERROR: /home/erp/.bench/ is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by official-akshayjadhav** [comment]
ERROR: /home/erp/.bench/ is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

**Comment by saru2020** [comment]
> ERROR: /home/erp/.bench/ is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with bzr+http, bzr+https, bzr+ssh, bzr+sftp, bzr+ftp, bzr+lp, bzr+file, git+http, git+https, git+ssh, git+git, git+file, hg+file, hg+http, hg+https, hg+ssh, hg+static-http, svn+ssh, svn+http, svn+https, svn+svn, svn+file).

seeing same issue, any solution? @official-akshayjadhav

**Comment by muteshi** [comment]
@saru2020 change the the code to ```sudo pip3 install -e /home/frappe/.bench/```
