### ISSUE TITLE
bench 5.7.4's get-app assumes my project is one folder below the server's root

### ISSUE THREAD

**Issue by daraul** [frappe/bench#1251]
For example, my project is *two* directories deep. bench 5.7.4 think it is only one directory deep, and therefore removes the domain. It then fails to resolve "subd1", in my example below: 

```
user@server:~/frappe-bench$ bench get-app --overwrite project https://user:token@custom.server/subd1/subd2/project.git                            
Getting project                                                                                 
$ git clone https://subd1/subd2/project.git  --depth 1 --origin upstream
fatal: unable to access 'https://subd1/subd2/project.git/': Could not resolve host: subd1
```
I've downgraded to 5.6 in the meantime.

**Comment by phot0n** [comment]
can you please try once with v5.7.5 (latest) one? - this seems to have been fixed in that

**Comment by daraul** [comment]
Just did that, and can confirm the problem is gone on v5.7.5. I'll close this.
