### ISSUE TITLE
Install specific version name

### ISSUE THREAD

**Issue by mohsinalimat** [frappe/bench#1252]
Install specific version name

Example:- `bench get-app https://github.com/frappe/erpnext --version-name 13.18.0`

**Comment by gavindsouza** [comment]
I believe this is possible using the `--branch` option already. You can pass any `tag`, `branch` or `commit sha` to fetch and install a specific version of said app.

**Comment by mohsinalimat** [comment]
I mean release version name.

**Comment by gavindsouza** [comment]
So, even though you can currently do `bench get-app erpnext --branch v13.18.0`, you want a separate interface that does the same thing but only less powerful?

**Comment by mohsinalimat** [comment]
Yes

**Comment by gavindsouza** [comment]
You can use `bench get-app erpnext --branch v13.18.0` since the differences are only specific to adding or removing the `v` in the git tag. You may write a wrapper over this if you wish but it's not a requirement that warrants a change in the core.
