### ISSUE TITLE
The daily backup scheduled job not exist in the list and no backups occurred

### ISSUE THREAD

**Issue by hameedacpa** [frappe/bench#1255]
Since last Friday or last version update, no scheduled backup exist 
When I opened, the scheduled job type, I didn't find anything related to the daily backup in the virtual server that I have
![2022-01-13_3-29-56](https://user-images.githubusercontent.com/84820402/149239661-ee2dde96-20eb-40a1-8329-522079e2786c.png)
Please investigate this issue

**Comment by hameedacpa** [comment]
I think the error coming from the command in the crontab
`bench --verbose --site all backup`

**Comment by TurkerTunali** [comment]
"verbose" switch were causing some errors. Did try to update your bench?

**Comment by gavindsouza** [comment]
I think there was an issue with the backup temporarily then. Can't replicate. Closing this.
