### ISSUE TITLE
bench restart seems to to nothing

### ISSUE THREAD

**Issue by zongo811** [frappe/bench#1261]
Issue: Bug report

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - PyPI [latest](https://pypi.org/project/frappe-bench/) 
 - master         (minor bug fixes)
 - v5.x           (Merged with develop on every release)
 - develop        (all updates)

**Do the checklist before filing an issue:**
 - [X] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
In 5.7.5 the command "bench restart" seems to have no effect. Only "bench restart --supervisor" seems to really restart the bench, see output of the two commands:
```
frappe@itucvmerpnextdevelop:~/frappe-bench$ bench restart
frappe@itucvmerpnextdevelop:~/frappe-bench$ bench restart --supervisor
$ supervisorctl restart frappe-bench-workers: frappe-bench-web:
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
frappe@itucvmerpnextdevelop:~/frappe-bench$
```

**To Reproduce** :page_with_curl:
1. execute "bench restart"
2. execute "bench restart --supervisor"
3. Compare output.

**Expected behavior** :chart_with_upwards_trend:
"bench restart" really restarts the bench: changed python-files are loaded, output print()ed form python-files is written to web.log, ...

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [X] Linux: `debian:buster`
- [ ] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**
- Bench Branch: 5.7.5
- Frappe Version: 13.19.0
- ERPNext Version: 13.19.0

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem.

**Comment by dawoodjee** [comment]
weird, i'm having the same issue

bench restart goes quiet without the effect

but these work

bench restart --supervisor
supervisorctl restart all


![image](https://user-images.githubusercontent.com/7912989/156553078-fccbd5c8-1340-4b0d-ab45-7f289b781377.png)

**Comment by india081947** [comment]
I am new to ERPNext and was exploring the Frappe Dev Container by referring to document given at https://github.com/frappe/frappe_docker/tree/main/development

In the setup process there is a command mentioned below:
`
bench init --skip-redis-config-generation --frappe-branch version-13 frappe-bench
`
This was working fine before this commit but when I tried doing it again today it failed as there are no supervisor installed on developer mode.

Error in frappe restart_supervisor_processes return code 127

Same way redis port is also 6379 by container but common_site_config.json is different

This is based on what I have observed but I may be incorrect as I am new to this Project and its structure or deployment.
