### ISSUE TITLE
Register/upload frappe bench as "frappe-bench" on PyPI

### ISSUE THREAD

**Issue by ghost** [frappe/bench#127]
Hi, I'm trying to add this package into FreeBSD ports tree, 
but bench is already used by another one: https://pypi.python.org/pypi/bench
Could you please submit it to PyPI, then it can have a canonical package name to use.

Thanks,

**Comment by koobs** [comment]
+1

**Comment by pdvyas** [comment]
We can call it `frappe-bench` on PyPI.

**Comment by yashodhank** [comment]
:+1:

**Comment by koobs** [comment]
@pdvyas Can you register frappe-bench on PyPI (even if you upload the sdist later) so that this issue can be closed?

@ubldr Can you rename this issue to "Register/upload frappe bench as "frappe-bench" on PyPI"

**Comment by pdvyas** [comment]
I just registered. Will upload sdist and update description soon.
https://pypi.python.org/pypi/frappe-bench

**Comment by koobs** [comment]
@pdvyas Thank you :)

**Comment by pdvyas** [comment]
@koobs Sorry for the off-topic..  Are you the author of the FreeBSD port (https://www.freshports.org/www/py-frappe-bench/) ? I'll test it soon and also adapt `bench setup production`. Also, it should depend on mariadb, redis and supervisord.

**Comment by koobs** [comment]
@pdvyas Not off-topic at all. The author and current MAINTAINER is @ubldr :)

I reviewed his original patch [1] to submit it to the ports tree, hence the creation of this issue:

[1] https://reviews.freebsd.org/D3120

**Comment by pdvyas** [comment]
Awesome, I'll be happy to make it compatible so that you don't have to patch anything/much. Also, we made quite a few changes recently for frappe version 6 with new dependencies on nodejs (without proper release management :( ). I'll setup a freebsd environment, test and contact @ubldr .

**Comment by koobs** [comment]
Regarding mysql, redis, supervisord

 * If there's no support for other SQL engines, then sure. If not, we can add multiple database OPTIONS to the port.
 * If it can run ''at all' without redis (just slowly), then we can add it as an OPTION. If not, sure :)
 * If it can via other/any startup/supervisor mechanisms, then supervisord could/should be an OPTION

I also note that virtualenv is in install_requires, where it probably shouldn't be. That declaration is too prescriptive without knowledge of the deployment environment. My guess is all OS package maintainers will be patching out this line.

Protip: Make good use of install_requires, setup_requires, tests_require, extras_require :)

**Comment by koobs** [comment]
@pdvyas Not a problem at all, we're here to help :) Thanks!

**Comment by koobs** [comment]
Protip #2: Utilise >= or no version for requirement versions (in released packages). This ensures that packages/ports dont break when dependent package versions (in ports/packages) are bumped past ==x or <= version.

Test with travis/other-CI-system with the latest versions of each

**Comment by pdvyas** [comment]
Agreed about supervisord as an option as `bench start` (should be able to start a dev server). Redis is definitely required as it's used as a celery (background job) broker.

Virtualenv is a definitely required as it's as there's a lot of assumption around in the directory structure, 

```
bench init frappe-bench
``` 
creates a directory, frappe-bench with a virtualenv, configuration, site, apps (frappe and erpnext, for example) directory inside (all self contained).

I agree about your versioning suggestions and use of Travis CI, making an issue for that!

Thanks! :)

**Comment by koobs** [comment]
If you use virtualenv commands/code at the moment, sure, it's *currently* an install_requires.

Longer term however, I would look at decoupling/removing assumptions Frappe makes about the deployment environment.

This should **still** be possible while retaining your requirements for a particular directory structure.

**Comment by pdvyas** [comment]
Yes, we can decouple the requirement of a virtualenv, I'll give some deep thought on that. Thanks a lot for your help :)

**Comment by koobs** [comment]
@pdvyas You're very welcome. Collaborative opensource is the best kind of opensource :)

**Comment by pdvyas** [comment]
:+1: True that!

**Comment by ubldr** [comment]
Regarding mysql and redis I think they are required by the apps downloaded via bench command, so I just added the dependencies that are only needed to run the bench command itself.

**Comment by mandarvaze** [comment]
I came here based on "Help Wanted" tag, But it seems that the issue is resolved as I see version 4.1.2 on PyPI

Can someone mark this as closed ?
