### ISSUE TITLE
Problem with "bench update" while running in development mode

### ISSUE THREAD

**Issue by zongo811** [frappe/bench#1278]
Issue: Bug report

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - v5.7.6

**Do the checklist before filing an issue:**
 - [X] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
I run my bench in development-mode. During "bench update" my bench is automagicaly stopped, and finally "bench update" stops with this message:
```
Building erpnext assets...

✔ Built js/erpnext-web.min.js
✔ Built js/erpnext.min.js
...
Done in 8.64s.
$ supervisorctl restart frappe:
frappe: ERROR (no such group)
frappe: ERROR (no such group)
Patching sites...
Migrating erpnextthkr.schloss.ituc.de
redis_cache service is not running.
Cannot run bench migrate without the services running.
If you are running bench in development mode, make sure that bench is running:

$ bench start
Otherwise, check the server logs and ensure that all the required services are running.

```
Then I have to do this:
```
bench start
bench migrate
```
When I try to login to the desk, I'm greeted with this message:
Error 
The system is being updated. Please refresh again after a few moments.

The Log shows this message:
10:03:43 web.1            | 127.0.0.1 - - [09/Mar/2022 10:03:43] "POST / HTTP/1.1" 503 -

To get rid of this, I have to run:
`bench config set-common-config -c maintenance_mode 0`

**To Reproduce** :page_with_curl:
1. Setup a bench in development mode as described in the Frappe-tutorial.
2. do "bench update" after some changes in git
3. See error

**Expected behavior** :chart_with_upwards_trend:

1. "bench update" completes without error, 
2. running bench is not stopped, 
3. maintenance mode is disabled after "bench update" completes

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [X] Linux: `debian:buster`
- [ ] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.7.6
- Frappe Version: 13.22.0
- ERPNext Version: 13.22.0

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem.

**Comment by zongo811** [comment]
I just discovered this workaround:
After "bench update" stops, do "bench start". Then do "bench update --no-backup".
Changes are already pulled from git, running bench is not stopped and "bench update" completes.

**Comment by zongo811** [comment]
Observation: Error did not occur when updating from 13.22.0 to 13.22.1.

**Comment by gavindsouza** [comment]
So, `bench migrate` has been running checks on active services for quite some time now (ref: https://github.com/frappe/frappe/pull/9934 - probs v12). You need Redis and your DBMS running in order to get site migrations done. For that, you should have `bench start` running in the background or another tab while doing a migrate operation.
