### ISSUE TITLE
[v6] Completions broken

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/bench#128]
in my bashrc:
`source ~/dev/webnotes/bench-repo/completion.sh`

Error on opening a new tab:
`/Users/anandpdoshi/dev/terminal.sh:source:59: no such file or directory: /Users/anandpdoshi/dev/webnotes/bench-repo/completion.sh`

**Comment by gavindsouza** [comment]
I was also working on one for zsh, more descriptive, etc. If anyone wants to collaborate, hit me up!
