### ISSUE TITLE
cannot get app from other git repo such as gitlab

### ISSUE THREAD

**Issue by mojerro** [frappe/bench#1282]
Issue: Bug report

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - PyPI [latest](https://pypi.org/project/frappe-bench/) 
 - master         (minor bug fixes)
 - v5.x           (Merged with develop on every release)
 - develop        (all updates)

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?
 - [x] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:

as I run `bench get --branch version-14-beta erpnext https://gitlab.com/frappe/erpnext.git`, it will try to clone the repo from github.
And I found that there is the code 
```
self.remote_server = "github.com"
```
I'm not sure why you solid the  remote_server, or I can take a pr to chang it

**Comment by phot0n** [comment]
hey @mojerro this should be fixed in v5.7.5, can you please once check and confirm?

**Comment by mojerro** [comment]
I found that the docker image is still in version 5.0.0-dev, I think this will be a new issue in frappe-docker repo?
