### ISSUE TITLE
Error installing version-13 "bench.exceptions.InvalidRemoteException: Frappe branch does not exist"

### ISSUE THREAD

**Issue by afuentes-alphas** [frappe/bench#1292]
Issue: Easy Install

**Distro Information (Required)**

bench develop

**Command Run (Required)**

To start the installation, the following commands were executed:

sudo apt install python3-minimal build-essential python3-setuptools

export LC_ALL=C.UTF-8

wget https://raw.githubusercontent.com/frappe/bench/develop/install.py

Then I tried running this command:

sudo python3 install.py --production --site site.example --verbose

In another instance I tried this one:

sudo python3 install.py --version 13 --production --site site.example --verbose

Both produced the same error:

"bench.exceptions.InvalidRemoteException: Frappe branch does not exist"

Is there any particular reason for this to happen?

Reviewing the source code of the bench, I observe that the API:

https://api.github.com/repos/frappe/frappe/branches

The list that returns does not appear version-13 although from github you can see that branch.

The same happens with erpnext, the API does not return version-13

**Additional context**

Server Ubuntu 18.04

->>>>>>>>>>>>>>>Error<<<<<<<<<<<<<<-

fatal: [localhost]: FAILED! => {
    "changed": true,
    "cmd": [
        "bench",
        "init",
        "~frappe/frappe-bench",
        "--frappe-path",
        "https://github.com/frappe/frappe",
        "--frappe-branch",
        "version-13",
        "--python",
        "python3"
    ],
    "delta": "0:00:09.657527",
    "end": "2022-04-07 21:57:57.012289",
    "invocation": {
        "module_args": {
            "_raw_params": "bench init ~frappe/frappe-bench --frappe-path https://github.com/frappe/frappe --frappe-branch version-13 --python python3",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": "/home/frappe/frappe-bench",
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2022-04-07 21:57:47.354762",
    "stderr": "Aborted!",
    "stderr_lines": [
        "Aborted!"
    ],
    "stdout": "WARN: bench is installed in editable mode!\n\nThis is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`\n\nSetting Up Environment\n$ /usr/local/bin/virtualenv --quiet env -p python3\n$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip\nTraceback (most recent call last):\n  File \"/home/frappe/.bench/bench/commands/make.py\", line 83, in init\n    verbose=verbose,\n  File \"/home/frappe/.bench/bench/utils/render.py\", line 95, in wrapper_fn\n    return fn(*args, **kwargs)\n  File \"/home/frappe/.bench/bench/utils/system.py\", line 78, in init\n    is_valid_frappe_branch(frappe_path=frappe_path, frappe_branch=frappe_branch)\n  File \"/home/frappe/.bench/bench/utils/__init__.py\", line 81, in is_valid_frappe_branch\n    raise InvalidRemoteException(\"Frappe branch does not exist\")\nbench.exceptions.InvalidRemoteException: Frappe branch does not exist\n\nERROR: There was a problem while creating /home/frappe/frappe-bench\nDo you want to rollback these changes? [y/N]: ",
    "stdout_lines": [
        "WARN: bench is installed in editable mode!",
        "",
        "This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`",
        "",
        "Setting Up Environment",
        "$ /usr/local/bin/virtualenv --quiet env -p python3",
        "$ /home/frappe/frappe-bench/env/bin/python -m pip install --quiet --upgrade pip",
        "Traceback (most recent call last):",
        "  File \"/home/frappe/.bench/bench/commands/make.py\", line 83, in init",
        "    verbose=verbose,",
        "  File \"/home/frappe/.bench/bench/utils/render.py\", line 95, in wrapper_fn",
        "    return fn(*args, **kwargs)",
        "  File \"/home/frappe/.bench/bench/utils/system.py\", line 78, in init",
        "    is_valid_frappe_branch(frappe_path=frappe_path, frappe_branch=frappe_branch)",
        "  File \"/home/frappe/.bench/bench/utils/__init__.py\", line 81, in is_valid_frappe_branch",
        "    raise InvalidRemoteException(\"Frappe branch does not exist\")",
        "bench.exceptions.InvalidRemoteException: Frappe branch does not exist",
        "",
        "ERROR: There was a problem while creating /home/frappe/frappe-bench",
        "Do you want to rollback these changes? [y/N]: "
    ]
}

PLAY RECAP ******************************************************************************************************************************************************************************************
localhost                  : ok=71   changed=44   unreachable=0    failed=1    skipped=59   rescued=0    ignored=0

Traceback (most recent call last):
  File "install.py", line 497, in <module>
    install_bench(args)
  File "install.py", line 278, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 413, in run_playbook
    success = subprocess.check_call(args, cwd=playbooks_folder, stdout=log_stream, stderr=sys.stderr)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-vvvv', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2.

**Possible Solution**

The API returns within the list of branches the version-13 of frappe and erpnext

**Comment by phot0n** [comment]
hey @afuentes-alphas , so i think the api results are getting paginated ..try using https://api.github.com/repos/frappe/frappe/branches?per_page=100 (note the `per_page` query) ..this will have `version-13` branch in the fetched data.

also, i don't think you're on develop branch of bench (as you've mentioned in distro info) as I was not able to find any function/method named `is_valid_frappe_branch` on current develop. can you please once check and confirm?

oh and, both these commands 👇  are the same `version` has value of 13 by default 😅 (in develop)
 
> Then I tried running this command:
> 
> sudo python3 install.py --production --site site.example --verbose
> 
> In another instance I tried this one:
> 
> sudo python3 install.py --version 13 --production --site site.example --verbose

**Comment by afuentes-alphas** [comment]
Hello @phot0n 

Here is a capture of the method where the error is being raised

![image](https://user-images.githubusercontent.com/64218953/162445474-ea21161d-8487-46ba-b7ac-5320e326150b.png)



It seems to me that develop of frappe now has version 14

![image](https://user-images.githubusercontent.com/64218953/162445195-1c11f76d-22ec-484e-9d78-b3828c807c9c.png)


Thank you for your time in reviewing.

**Comment by phot0n** [comment]
Ah yes, you're correct ..I have old code in my local 😅 sorry for that. will try to fix it

And yes frappe v14 is going to launch soon

**Comment by naourass** [comment]
Hello, what's the proper way to bypass this error at the moment ?
