### ISSUE TITLE
Certbot auto script is deprecated

### ISSUE THREAD

**Issue by dj12djdjs** [frappe/bench#1301]
According to https://community.letsencrypt.org/t/cant-download-file-in-https-dl-eff-org-certbot-auto/159053
This script is deprecated. Therefor, causing `bench setup lets-encrypt` to crash.

**Usage**
https://github.com/frappe/bench/blob/eb715735bbb79e5edd39e29c1b0e5587d2d3712c/bench/config/lets_encrypt.py#L117

**Comment by gavindsouza** [comment]
https://github.com/frappe/bench/pull/1152 was supposed to fix it. But the PR was never completed.

**Comment by dj12djdjs** [comment]
@gavindsouza I'll see if I can finish it up this weekend.
