### ISSUE TITLE
run bench with pipx

### ISSUE THREAD

**Issue by kafai-lam** [frappe/bench#1302]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:
Since I don't wanna mess up my global pip dependency, I perfer to install bench with pipx. However it will lead to runtime error while running commands like `bench init` and `bench setup env`.

**To Reproduce** :page_with_curl:
1. remove frappe-bench installed by pip
2. run `pipx install bench`
3. run `bench init frappe-bench`

**Expected behavior** :chart_with_upwards_trend:
correctly init bench

**Screenshots** :crystal_ball:
<img width="1135" alt="Screenshot 2022-04-30 at 00 57 30" src="https://user-images.githubusercontent.com/41912520/165989748-d72a4236-6886-479a-862d-0972ec4291da.png">

**OS (please complete the following information):** :cyclone:
macOS: 12.2

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.8.1

**Additional context** :page_facing_up:
https://github.com/pypa/pipx

**Possible Solution** :bookmark_tabs:
After investigation, I find 2 places cause this error:

1. 
https://github.com/frappe/bench/blob/31d9de4decacf62a5e8aec9d88855174dc929b51/bench/utils/bench.py#L36-L48

When we do `pipx install frappe-bench`, `virtualenv` was also installed under the same isolated virtual environment but not as system binary. That's why `venv = which("virtualenv")` cannot find the path.

Idea 1: use other method to locale `virtualenv` which under same virtual environment as bench 

2.
https://github.com/frappe/bench/blob/31d9de4decacf62a5e8aec9d88855174dc929b51/bench/bench.py#L326-L330

Since we cannot locale `virtualenv` correctly,  `get_venv_path()` returns path of  `venv` instead. Unfortunately, `venv` does not support options like `--quiet`, `--python`

Idea 2: fix up the option provided

**Comment by Aradhya-Tripathi** [comment]
Fixed by [e0f6b17](https://github.com/frappe/bench/pull/1314/commits/e0f6b1735d355e03d9e7dc221231ab33b7dec4c3)
