### ISSUE TITLE
frappe bench 12 stopped suddenly 

### ISSUE THREAD

**Issue by ailanbelal** [frappe/bench#1310]
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
08:52:29 system           | redis_cache.1 started (pid=5302)
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
08:52:29 system           | redis_socketio.1 started (pid=5304)
08:52:29 system           | redis_queue.1 started (pid=5308)
08:52:29 redis_queue.1    | 5314:C 22 May 2022 08:52:29.119 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
08:52:29 redis_queue.1    | 5314:C 22 May 2022 08:52:29.119 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=5314, just started
08:52:29 redis_queue.1    | 5314:C 22 May 2022 08:52:29.119 # Configuration loaded
08:52:29 redis_cache.1    | 5307:C 22 May 2022 08:52:29.118 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
08:52:29 redis_cache.1    | 5307:C 22 May 2022 08:52:29.118 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=5307, just started
08:52:29 redis_cache.1    | 5307:C 22 May 2022 08:52:29.118 # Configuration loaded
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.118 * Increased maximum number of open files to 10032 (it was originally set to 1024).
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.119 * Running mode=standalone, port=13001.
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.119 # Server initialized
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.119 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.119 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.119 * Ready to accept connections
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.119 * Increased maximum number of open files to 10032 (it was originally set to 1024).
08:52:29 redis_socketio.1 | 5311:C 22 May 2022 08:52:29.118 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
08:52:29 redis_socketio.1 | 5311:C 22 May 2022 08:52:29.118 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=5311, just started
08:52:29 redis_socketio.1 | 5311:C 22 May 2022 08:52:29.118 # Configuration loaded
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.119 * Increased maximum number of open files to 10032 (it was originally set to 1024).
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.119 * Running mode=standalone, port=12001.
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.119 # Server initialized
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.119 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.119 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.119 * Ready to accept connections
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.120 * Running mode=standalone, port=11001.
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.120 # Server initialized
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.120 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.120 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.120 * Ready to accept connections
08:52:29 system           | web.1 started (pid=5312)
08:52:29 system           | socketio.1 started (pid=5315)
08:52:29 system           | worker_short.1 started (pid=5332)
08:52:29 system           | schedule.1 started (pid=5334)
08:52:29 system           | worker_default.1 started (pid=5342)
08:52:29 system           | worker_long.1 started (pid=5343)
08:52:29 system           | watch.1 started (pid=5336)
08:52:29 socketio.1       | listening on *: 9001
08:52:29 schedule.1       | Traceback (most recent call last):
08:52:29 schedule.1       |   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
08:52:29 schedule.1       |     return _run_code(code, main_globals, None,
08:52:29 schedule.1       |   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
08:52:29 schedule.1       |     exec(code, run_globals)
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
08:52:29 schedule.1       |     main()
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
08:52:29 schedule.1       |     click.Group(commands=commands)(prog_name='bench')
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/env/lib/python3.8/site-packages/click/core.py", line 764, in __call__
08:52:29 schedule.1       |     return self.main(*args, **kwargs)
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/env/lib/python3.8/site-packages/click/core.py", line 717, in main
08:52:29 schedule.1       |     rv = self.invoke(ctx)
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
08:52:29 schedule.1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/env/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
08:52:29 schedule.1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/env/lib/python3.8/site-packages/click/core.py", line 956, in invoke
08:52:29 schedule.1       |     return ctx.invoke(self.callback, **ctx.params)
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/env/lib/python3.8/site-packages/click/core.py", line 555, in invoke
08:52:29 schedule.1       |     return callback(*args, **kwargs)
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/commands/scheduler.py", line 159, in start_scheduler
08:52:29 schedule.1       |     from frappe.utils.scheduler import start_scheduler
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/utils/scheduler.py", line 42, in <module>
08:52:29 schedule.1       |     "all": "0/" + str((frappe.get_conf().scheduler_interval or 240) // 60) + " * * * *",
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/__init__.py", line 239, in get_conf
08:52:29 schedule.1       |     with init_site(site):
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/__init__.py", line 248, in __enter__
08:52:29 schedule.1       |     init(self.site)
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/__init__.py", line 175, in init
08:52:29 schedule.1       |     setup_module_map()
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/__init__.py", line 1041, in setup_module_map
08:52:29 schedule.1       |     for module in get_module_list(app):
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/__init__.py", line 904, in get_module_list
08:52:29 schedule.1       |     return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
08:52:29 schedule.1       |   File "/home/belal/frappe-bench-12/apps/frappe/frappe/__init__.py", line 862, in get_module
08:52:29 schedule.1       |     return importlib.import_module(modulename)
08:52:29 schedule.1       |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
08:52:29 schedule.1       |     return _bootstrap._gcd_import(name[level:], package, level)
08:52:29 schedule.1       | ModuleNotFoundError: No module named 'chr'
08:52:29 system           | worker_default.1 stopped (rc=1)
08:52:29 system           | sending SIGTERM to redis_cache.1 (pid 5302)
08:52:29 system           | sending SIGTERM to redis_socketio.1 (pid 5304)
08:52:29 system           | sending SIGTERM to redis_queue.1 (pid 5308)
08:52:29 system           | sending SIGTERM to web.1 (pid 5312)
08:52:29 system           | sending SIGTERM to socketio.1 (pid 5315)
08:52:29 system           | sending SIGTERM to watch.1 (pid 5336)
08:52:29 system           | sending SIGTERM to schedule.1 (pid 5334)
08:52:29 system           | sending SIGTERM to worker_short.1 (pid 5332)
08:52:29 system           | sending SIGTERM to worker_long.1 (pid 5343)
08:52:29 redis_cache.1    | 5307:signal-handler (1653198749) Received SIGTERM scheduling shutdown...
08:52:29 redis_socketio.1 | 5311:signal-handler (1653198749) Received SIGTERM scheduling shutdown...
08:52:29 system           | worker_short.1 stopped (rc=-15)
08:52:29 system           | worker_long.1 stopped (rc=-15)
08:52:29 redis_queue.1    | 5314:signal-handler (1653198749) Received SIGTERM scheduling shutdown...
08:52:29 system           | watch.1 stopped (rc=-15)
08:52:29 system           | web.1 stopped (rc=-15)
08:52:29 system           | schedule.1 stopped (rc=-15)
08:52:29 system           | socketio.1 stopped (rc=-15)
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.923 # User requested shutdown...
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.924 # User requested shutdown...
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.924 # User requested shutdown...
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.924 * Removing the pid file.
08:52:29 redis_queue.1    | 5314:M 22 May 2022 08:52:29.924 # Redis is now ready to exit, bye bye...
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.924 * Removing the pid file.
08:52:29 redis_cache.1    | 5307:M 22 May 2022 08:52:29.924 # Redis is now ready to exit, bye bye...
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.924 * Removing the pid file.
08:52:29 redis_socketio.1 | 5311:M 22 May 2022 08:52:29.924 # Redis is now ready to exit, bye bye...
08:52:29 system           | redis_socketio.1 stopped (rc=-15)
08:52:29 system           | redis_queue.1 stopped (rc=-15)
08:52:29 system           | redis_cache.1 stopped (rc=-15)

**Comment by gavindsouza** [comment]
I'm not sure if v12 supports `PY38`. Try with `PY37` or 36 instead. Check what v12's CI uses for a sure shot answer.
