### ISSUE TITLE
How to initialize bench with the v14.0.0-beta.4 version ??

### ISSUE THREAD

**Issue by SaberChacha** [frappe/bench#1317]
I tried to use the command `bench init --skip-redis-config-generation --frappe-branch version-14 frappe-bench` but the following Error occured : 
bench.exceptions.InvalidRemoteException: Invalid version-14 for the remote https://github.com/frappe/frappe.git

**Comment by gavindsouza** [comment]
`bench init --skip-redis-config-generation --frappe-branch v14.0.0-beta.4 frappe-bench` should work. There's no version-14 branch on frappe/frappe yet - it will be when there's a stable v14 release. But for now, there's a `version-14-beta` branch from which releases happen.

`bench init --skip-redis-config-generation --frappe-branch version-14-beta frappe-bench` should create a bench with the latest v14 beta release.
