### ISSUE TITLE
 Unable to start (reload) nginx

### ISSUE THREAD

**Issue by scdanieli** [frappe/bench#1351]
Issue: Bug report

**Describe the bug** :chart_with_downwards_trend:

 Unable to start (reload) nginx.

```
$ sudo systemctl start nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
```

**To Reproduce** :page_with_curl:

1. Use frappe-bench 5.13.x
2. `bench setup nginx --yes` (as frappe user)
3. `sudo systemctl start nginx` (as sudor)

**OS (please complete the following information):** :cyclone:
- [x] Linux: Ubuntu 20.04

**Version Information**

- Bench Branch: v5.13.x

**Possible Solution** :bookmark_tabs:

The nginx template seems broken since this [commit](https://github.com/frappe/bench/pull/1308/commits/c61e993a789b4d9c13b6129f026a19b93a70f523). @deajan @gavindsouza 

```
sudo nginx -t
nginx: [emerg] unknown "site_name_ihrkdqy_access" variable
nginx: configuration file /etc/nginx/nginx.conf test failed
```

**Comment by git-avc** [comment]
We are facing same issue. Multitenant mode. Probably {{site_name}} can't be assigned. 

We get too this error:

"nginx: [emerg] unknown log format “main” in /etc/nginx/conf.d/frappe-bench.conf:101
nginx: configuration file /etc/nginx/nginx.conf test failed"

Frappe v14
Ubuntu v22.04
Bench v5.13.4

**Comment by gavindsouza** [comment]
Hey @scdanieli, @git-avc @Tom-Finke (via https://github.com/frappe/bench/pull/1308), what version of NGINX are you guys running? I'm trying to figure out what we're missing here.

I hadn't faced any issues testing the PR on `nginx/1.18.0`, and neither did the tests of the production CI fail. 

For the time being, I'd suggest you downgrade the Bench package to 5.12.1

**Comment by git-avc** [comment]
Nginx 1.18.0 in my case.

After " bench setup nginx " the file nginx.conf get incorrect.

**Comment by git-avc** [comment]
In my case,, the workaround is modify the nginx.conf template removing the "main" modifier and "$host" variable in log creation.

**Comment by gavindsouza** [comment]
> In my case,, the workaround is modify the nginx.conf template removing the "main" modifier and "$host" variable in log creation.

Does removing just the `main` modifier work too? 

_(The config will be erroneous if the main log_format isn't defined ([SO ref](https://serverfault.com/a/985570/581425)))_

**Comment by git-avc** [comment]
Yes, my template contains this in logs "section"

> # logs in var
        access_log  /var/log/nginx/_access.log;
        error_log  /var/log/nginx/}_error.log;

Just removed "main" modifier and "{{ site_name }}" variable (that results in "$host" in generated nginx.conf).

It's working, and nginx -t shows 
"nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful"

Just 1 log file is generated for all sites. I think {{ site_name }} should let create log for each site on dns multitenant scenario ... but is not working.

**Comment by gavindsouza** [comment]
@git-avc Can you try out https://github.com/frappe/bench/pull/1355 and let me know if it (logging choices) works for you?

**Comment by git-avc** [comment]
Of course, done, comments on PR

**Comment by gavindsouza** [comment]
Try `bench setup nginx --log_format ''` with bench `v5.14.0` if you haven't installed + setup NGINX via `bench install nginx`

v5.14.0 has added options for logging in NGINX

**Comment by git-avc** [comment]
Tested, it's working! Thanks!
