### ISSUE TITLE
cannot import name ‘clear_command_cache’ 

### ISSUE THREAD

**Issue by ishanloya** [frappe/bench#1352]
Facing this issue with both python3.8 and python3.10 and with frappe v13 and v14 after upgrading to bench 5.13.3.

`cannot import name ‘clear_command_cache’ from ‘bench.utils’ (/usr/local/lib/python3.10/dist-packages/bench/utils/init.py)`

**Comment by artemartamonov** [comment]
@gavindsouza please check, it looks your latest commit https://github.com/frappe/bench/commit/18a954b88c7ef2574a5ea5408d1924b14c4484a4
You have to clear all the decencies like:
https://github.com/frappe/bench/blob/b810144f83222cdbc79d46de02a96b5bce11bab9/bench/utils/bench.py#L388
