### ISSUE TITLE
Enhancement: Development under Windows / Create Vagrantfile setup for Vagrant

### ISSUE THREAD

**Issue by dottenbr** [frappe/bench#136]
As discussed with @anandpdoshi it would be amazing if you had a Vagrantfile that would allow to run and develop ERPNext and Frappé under Windows or any other operating system without having to install dependencies. We would be really looking forward to this and would like to be early testers / adopters.

**Comment by pdvyas** [comment]
We tried on windows once with `frappe-bench` dir as a shared folder and it didn't work out. Luis works on OSX using vagrant and has also documented the steps here, https://github.com/frappe/frappe/wiki/V5:-Vagrant-box-for-frappe-framework

**Comment by dottenbr** [comment]
@pdvyas thank you for your message. I have set up VirtualBox and Vagrant on my Mac OS X Yosemite system and the initial setup works nicely, vagrant up and there we go under localhost:8020 we can check out ERPNext. Since that is quite a dated version I tried running "bench update" to get the latest version, but that actually breaks with an error message I can't resolve. I think it would be worth spending some time creating a vagrant setup script or a new vagrant file for 5.3 that also will fix any update problems.

@anandpdoshi any news on the script you have written? Maybe you can provide that and we will test it on the windows and or mac machine.

**Comment by dottenbr** [comment]
vagrant@vagrant-ubuntu-utopic-64:/vagrant/frappe-bench$ bench update
Already up-to-date.
From https://github.com/frappe/erpnext
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
From https://github.com/frappe/frappe
 * branch            develop    -> FETCH_HEAD
Already up-to-date.
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
You are using pip version 6.1.1, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
    Command "/vagrant/frappe-bench/env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-GBy8Hq/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-ehb83s-record/install-record.txt --single-version-externally-managed --compile --install-headers /vagrant/frappe-bench/env/include/site/python2.7/cffi" failed with error code 1 in /tmp/pip-build-GBy8Hq/cffi
Error: None
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 9, in <module>
    load_entry_point('bench==0.1', 'console_scripts', 'bench')()
  File "/vagrant/bench-repo/bench/cli.py", line 56, in cli
    bench()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/vagrant/bench-repo/bench/cli.py", line 239, in update
    update_requirements()
  File "/vagrant/bench-repo/bench/utils.py", line 324, in update_requirements
    exec_cmd("{pip} install -q -r {req_file}".format(pip=pip, req_file=req_file))
  File "/vagrant/bench-repo/bench/utils.py", line 80, in exec_cmd
    subprocess.check_call(cmd, cwd=cwd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command './env/bin/pip install -q -r ./apps/frappe/requirements.txt' returned non-zero exit status 1

**Comment by dottenbr** [comment]
<img width="958" alt="bildschirmfoto 2015-08-11 um 23 42 00" src="https://cloud.githubusercontent.com/assets/9136094/9211450/99c90ea8-4082-11e5-9eed-a330ba47c88f.png">

**Comment by pdvyas** [comment]
This is strange, what is the output of
`./env/bin/pip install -r apps/frappe/requirements.txt`

Also, run bench commands from the VM and not the host.

**Comment by dottenbr** [comment]
@pdvyas this seems to have been a bug and was resolved through the forum https://discuss.erpnext.com/t/bench-update-error-v5/6989/3

**Comment by pdvyas** [comment]
new repo, https://github.com/frappe/erpnext_vagrant

**Comment by dottenbr** [comment]
Hi @pdvyas unfortunately after:

git clone https://github.com/frappe/erpnext_vagrant.git erpnext_vagrant
vagrant up
vagrant ssh

"frappe-bench" is not set up in /vagrant/. The bootstap script fails.

![2015-09-10 16_28_28-select posh git erpnext_vagrant master](https://cloud.githubusercontent.com/assets/9136094/9790952/10581b8c-57d9-11e5-8688-442d7c41609a.png)
