### ISSUE TITLE
rds_db option not configurable via bench

### ISSUE THREAD

**Issue by joshuarestivo** [frappe/bench#1371]
Issue:
When deploying frappe on an aws RDS database, an 'rds_db: 1' flag must be set inside of common_site_config.json. This allows frappe to play nicely with the RDS database instance. However, bench does not currently have a command-line switch that facilitates the addition of rds_db. It can only be added by manually editing the common_site_config.json file.

This breaks helm-based deployments where the environment needs to be configured programatically. Manual intervention and fix-up is required.

Desired Resolution:
Add ability to set rds_db through a bench option. This could manifest as a separate option (eg., db-environment) or by adding a new db-type (eg., mariadb-rds).

**Comment by ankush** [comment]
`bench set-common-config rds_db 1`

This should be enough?
