### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by creative-paramu** [frappe/bench#1379]
Issue: Easy Install
I was run this install.py script it was arising this error, how to solve this?

![Screenshot from 2022-10-20 09-58-47](https://user-images.githubusercontent.com/101092028/196857127-d2fc3a91-ffeb-4b32-a033-61333ef635b9.png)

**Comment by ankush** [comment]
https://discuss.erpnext.com/t/deprecation-easy-install-script-is-no-longer-supported/96245

**Comment by ankush** [comment]
refer https://github.com/pyca/pyopenssl/issues/728
