### ISSUE TITLE
Courses API (ESG) on Moodle 

### ISSUE THREAD

**Issue by RajivGanger** [frappe/bench#1386]
Hey Team,

I need help on implementing the APIs on Moodle, I am new to it, can anyone help me on this.

Laureus SSG API
API (ESG)
1. Courses
2. Course feedback
3. Training providers
4. Skills passport
5. E-certificates
6. Assessment

Thanks
Rajiv Ganger

**Comment by ankush** [comment]
Wrong place for this question

https://discuss.erpnext.com/

**Comment by RajivGanger** [comment]
Thanks Ankush, Can you please let me know from where I can get help for this?

**Comment by ankush** [comment]
Use the link I shared in the previous comment. It's out community forums for all-things-frappe and erpnext.

**Comment by RajivGanger** [comment]
Okay Thanks
