### ISSUE TITLE
add Node and npm to the installer

### ISSUE THREAD

**Issue by DrTrills** [frappe/bench#139]
On debian 7, installer cant finish without Node and npm. Need to add these to the installer so the install is smooth.

**Comment by pdvyas** [comment]
Does this not help ? https://github.com/frappe/bench/blob/master/install_scripts/setup_frappe.sh#L197

Are you using the latest script?

**Comment by DrTrills** [comment]
Yep, I am working on modding it now- This is what I got

me@erpnext:~$ sudo bash setup_frappe.sh --setup-production
Installing for debian 7 amd64
In case you encounter an error, you can post on https://discuss.frappe.io

Adding debian mariadb repo
Installing packages for debian. This might take time...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nodejs
E: Unable to locate package npm
patrick@erpnext:~$

I installed it with https://github.com/joyent/node/wiki/installing-node.js-via-package-manager which shows it needs curl, as well as the repo added. I am working on a fork now (unless you can do it quicker!)

**Comment by DrTrills** [comment]
I think this should do the trick- though not tested yet! https://github.com/DrTrills/bench/blob/master/install_scripts/setup_frappe.sh#L197

**Comment by pdvyas** [comment]
https://deb.nodesource.com/setup_0.12 this script adds another debian repository. This fine. 

About your fix, do a `run_cmd curl....` before the apt-get command.

**Comment by DrTrills** [comment]
good call- i believe its all working now. will need to reset a vm to test

Thanks!

**Comment by DrTrills** [comment]
This actually is a bit tricky since it needs to be installed as root first. Might want to add that to the setup instructions? Unless there is a better way of doing this
