### ISSUE TITLE
Error: no such option: --site

### ISSUE THREAD

**Issue by ShahzadNaser** [frappe/bench#1394]
Issue: Bug report

My bench version is 5.14.4

i won't able to perform any operation on specific site using  *bench --site * command it throwing error "no such option: --site"

**Comment by ankush** [comment]
Not enough info to debug anything. What commands you ran?

**Comment by ShahzadNaser** [comment]
@ankush  i am installing a custom app on specific site in multitenent env. but won't able to use **--site** command for selecting specific site.

bench --site  [sitename] install-app [custom-app]

this is the example command which i am running

**Comment by ardi85** [comment]
bench use [sitename]

**Comment by skanel** [comment]
I faced the same issue `bench --site` , example

**Comment by dawoodjee** [comment]
Same issue here, it occurs randomly

Perhaps relevant to mention what OS we're each using, I'm on MacOS

**Comment by ankush** [comment]
https://github.com/frappe/bench/issues/1488

**Comment by dawoodjee** [comment]
WORKAROUND

Like @ardi85 said, use `bench use` then your command, e.g

```
bench use [sitename]
bench migrate
# will perform migrate on [sitename]
```
