### ISSUE TITLE
--prod setting installs self-signed certificate by default

### ISSUE THREAD

**Issue by i5hi** [frappe/bench#1418]
Issue: Easy Install

**Do the checklist before filing an issue:**
 - [ y ] Did you retain the logfile (path of logfile is shared while the script is run)? We definitely **need** the logfile to debug any easy install related issues.
 - [ m ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Distro Information (Required)**
Linux erp 5.10.0-14-amd64 https://github.com/frappe/bench/issues/1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

ID="generic"
VERSION="20220503-998"
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
**Command Run (Required)**

`python3 easy-install.py --prod -n office -s office.toma.tech --email ishi@toma.tech`

**Log File (Required)**
debian@erp:~$ cat easy-install.log 
2023-01-16 17:48:39,905 - INFO - Running Production Setup
2023-01-16 17:48:55,603 - INFO - Docker Compose file generated at ~/office-compose.yml
2023-01-16 17:51:06,391 - INFO - New site creation completed

**Additional context**

Following the last update the installation process was smooth however instead of issuing a valid Lets encrypt certificate, it has created a self-signed certificate for my subdomain.

This is the proxy log:

```
office-proxy-1        | time="2023-01-16T18:57:32Z" level=info msg="Configuration loaded from flags."
office-proxy-1        | time="2023-01-16T18:58:09Z" level=error msg="accept tcp [::]:80: use of closed network connection" entryPointName=web
office-proxy-1        | time="2023-01-16T18:58:09Z" level=error msg="Error while starting server: accept tcp [::]:80: use of closed network connection" entryPointName=web
office-proxy-1        | time="2023-01-16T18:58:09Z" level=error msg="accept tcp [::]:443: use of closed network connection" entryPointName=websecure
office-proxy-1        | time="2023-01-16T18:58:09Z" level=error msg="Error while starting server: accept tcp [::]:443: use of closed network connection" entryPointName=websecure
office-proxy-1        | time="2023-01-16T18:58:09Z" level=error msg="Cannot connect to docker server context canceled" providerName=docker
office-proxy-1        | time="2023-01-16T18:58:35Z" level=info msg="Configuration loaded from flags."
```

**Possible Solution**

The proxy log failed requests could these be failed attempts to validate a cert with letsencrypt?

**Comment by revant** [comment]
try restarting the server and container once.

check running containers with `docker ps`. Make sure frontend, backend, scheduler, queue-default, queue-short, queue-long, websocket, redis-cache, redis-queue, redis-socketio, db and proxy are running.

make sure frontend stays up and running.

Edit: If you wish you can add my ssh public keys from github to the server and I'll check and report here.

**Comment by revant** [comment]
I found the reason https://community.traefik.io/t/no-domain-parsed-in-provider-acme/4886/2

**Comment by revant** [comment]
https://github.com/frappe/bench/pull/1424

**Comment by i5hi** [comment]
Thanks @revant !
