### ISSUE TITLE
Error: No such command "switch-to-v5".

### ISSUE THREAD

**Issue by jevonearth** [frappe/bench#142]
Bench or erpnext now has a v6. The upgrade command tells the user that it is possible to pin the version using the command `bench switch-to-v5` but that subcommand doesn't appear to have been implemented yet.

```
erpnext@erp-sandbox:~/frappe-bench$ bench switch-to-v5
Usage: bench [OPTIONS] COMMAND [ARGS]...

Error: No such command "switch-to-v5".
erpnext@erp-sandbox:~/frappe-bench$
```

Tested using:
frappe/bench at commit: 27d64b6ea6d0f305697921cd78b070b6e3718feb

ERPNext: v4.20.2
Frappe Framework: v4.10.2
*and*
ERPNext: v4.25.7
Frappe Framework: v4.14.3

**Comment by yashodhank** [comment]
Affirmative, same happened with me when I tried to perform update using bench command.
later fixed by performing bench upgrade twice.
