### ISSUE TITLE
Documentation needs guidance on How to restart ERPnext after PC restart?

### ISSUE THREAD

**Issue by dkipp** [frappe/bench#1422]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
I successfully  installed erpnext (for validation, not production) with the easy installscript as documented in [README.md](https://github.com/frappe/bench#readme)
But I cant find a Dokumentation on how to start erpnext again, after I restarted my PC

**Describe the solution you'd like**
one line at the end of the install documentation would be enough for me.

**Describe alternatives you've considered**
i tried several things:
- manually started "frappe" within win11 docker -> results in: "Running (5/15)"
- tried "bench start" within ubunt: `user@erpnext:~$ bench start -> Command 'bench' not found`
- searched the doc and the issues for more guidance, but found nothing that appears as the next appropriate step

**Additional context**
- I'm on win11 (clean test system - nothing else installed) using ubuntu within wsl
- I don't mind a manual erpnext start

**Comment by codezart** [comment]
@dkipp You need to be inside frappe-bench directory to be able to run bench commands.

**Comment by acibibo** [comment]
Ive tried using command bench start in frappe-bench directory. And it doesnt work, i mean it started something, but when I click on the localhost address, it say it couldnt reach out.

**Comment by ankush** [comment]
If you've configured production then supervisorctl is supposed to auto start as service after reboot.
