### ISSUE TITLE
bench python requirements incompatible with frappe v14

### ISSUE THREAD

**Issue by casesolved-co-uk** [frappe/bench#1425]
I suggest you drop the use of `~=` everywhere because it's too restrictive:

```console
  Attempting uninstall: Jinja2
    Found existing installation: Jinja2 3.0.3
    Uninstalling Jinja2-3.0.3:
      Successfully uninstalled Jinja2-3.0.3
  Attempting uninstall: frappe
    Found existing installation: frappe 14.23.0
    Uninstalling frappe-14.23.0:
      Successfully uninstalled **frappe-14.23.0**
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
**frappe-bench 5.0.0.dev0** requires jinja2~=3.0.3, but you have jinja2 3.1.2 which is incompatible.
frappe-bench 5.0.0.dev0 requires semantic-version~=2.8.2, but you have semantic-version 2.10.0 which is incompatible.
Successfully installed Jinja2-3.1.2 frappe-14.23.0 semantic-version-2.10.0
```

Instead use a range where you know it will work

**Comment by blaggacao** [comment]
That would also help [packaging for nixpkgs](https://github.com/NixOS/nixpkgs/pull/214800/files#diff-f17c2605a50fe771c61964d5d7b7c86c0349fcca2acce41252c48bece0067557R27-R32)

**Comment by ankush** [comment]
Bench is supposed to be globally installed, not inside virtual env of frappe. Both python versions can be very different and it'd mostly work fine.

**Comment by blaggacao** [comment]
> is supposed to be globally installed

Under certain scenarios, that assumption and the reasoning that follows isn't defendable.

To understand my argument we have to acknowledge that a binary that claims system wide side effects isn't well-behaved.

If we can part from that principle, I'm happy to expand on my argument, which I actually care about and think it would make `frappe` genuinely better, safer and more pleasant to use.

Please let me know, if I should expand on that basis?

**Comment by casesolved-co-uk** [comment]
> Please let me know, if I should expand on that basis?

I would like to hear it, but you'll be preaching to the converted on my end

**Comment by blaggacao** [comment]
@ankush Is there a chance you'd reopen and/or accept a PR?

**Comment by blaggacao** [comment]
@ankush Is there a chance you'd reopen and/or accept a PR as long as we get agreement on the legitimacy of alternative installing scenarios that exist for good reason?

**Comment by ankush** [comment]
@blaggacao no. Moreover, I am mostly leaning towards deprecating non-docker installs too. 

It's just not manageable for me to keep dealing with packaging mess of multiple distros and multiple package managers.

**Comment by casesolved-co-uk** [comment]
> @blaggacao no. Moreover, I am mostly leaning towards deprecating non-docker installs too.
> 
> It's just not manageable for me to keep dealing with packaging mess of multiple distros and multiple package managers.

This isn't a rational decision. Presumably you're talking about the ansible playbooks? Everything else is vanilla python afaik. You only need to support debian/ubuntu

**Comment by blaggacao** [comment]
> It's just not manageable for me to keep dealing with packaging mess of multiple distros and multiple package managers.

I guess, I can see a good solution then for that problem. :smile: And that solution provides builtin docker images as a distribution collateral. It's two layers:

- A reproducible "binary" (rather: executable) package (for linux / macos / WSL)
- On top of the former: a docker distribution image (for windows)

And yes, it removes the ansible playbooks from the maintenance equation, too.

Happy to help! Just ask.
