### ISSUE TITLE
New Sites Not Resolving On Localhost

### ISSUE THREAD

**Issue by azwalzaman** [frappe/bench#1437]
Issue: Bug report

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
I installed Frappe with the easy install script with the fix from Revant's PR #1424 . The default site ie. site1.localhost works fine. But when I create a new one, for example site2.localhost, it gives me a 404 not found
**To Reproduce** :page_with_curl:
1. `python3 easy-install.py --prod --email email@gmail.com`
2. `docker exec -it <container-id> \bin\bash`
3. `cd frappe-bench`
4. `bench config dns_multitenant on`
5. `bench new-site site2.localhost`
6. `bench --site site2.localhost install-app erpnext`
7. `bench setup nginx`
8. `service nginx reload`

**Expected behavior** :chart_with_upwards_trend:
site2.localhost loads my site

**Screenshots** :crystal_ball:
![image](https://user-images.githubusercontent.com/37041930/220873508-4fd19ca9-ca7d-4532-b948-cdee53f01dfa.png)
![image](https://user-images.githubusercontent.com/37041930/220873836-2b68e723-331a-446c-8d1e-c4eefc500550.png)

**OS:** :cyclone:
- [x] Linux: `Ubuntu 22.04 (WSL)`

**Version Information**

- Bench Branch: develop
- Frappe Version: 14.26.0
- ERPNext Version: 14.17.0

**Additional context** :page_facing_up:

**Comment by athul** [comment]
Hi,

For frappe_docker setups, DNS multitenancy isn't supported out of the box irrc. You have to setup port based multitenancy for using multiple sites. 

Please refer https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md for port based multitenancy support.

**Comment by azwalzaman** [comment]
> Hi,
> 
> For frappe_docker setups, DNS multitenancy isn't supported out of the box irrc. You have to setup port based multitenancy for using multiple sites.
> 
> Please refer https://github.com/frappe/frappe_docker/blob/main/docs/port-based-multi-tenancy.md for port based multitenancy support.

Thanks for responding! I guess I will try to set up port based multitenancy then. IMO you guys should mention that DNS based multitenancy isn't supported out of the box in the main README.

**Comment by revant** [comment]
also read https://github.com/frappe/frappe_docker/wiki/Frequently-Asked-Questions if you decide to stick with containers
