### ISSUE TITLE
Hardcoded log directory causes error in Dreamhost VPS

### ISSUE THREAD

**Issue by felipekk** [frappe/bench#146]
When trying to install frappe into a VPS from Dreamhost I get the following error:

<tt>IOError: [Errno 13] Permission denied: '/home/erpcoisasdekelya/logs/bench.log'</tt>

The directory used for the logfile seems to be hardcoded, and Dreamhost uses the ~/logs directory for the apache logs and thus it exists with special permissions.

**Comment by pdvyas** [comment]
There's something wrong as the directory has to be `~/frappe-bench/logs`. Can you try on clean minimal install (no cPanel)?
