### ISSUE TITLE
python files should be compiled in Python version of bench instance, not bench CLI

### ISSUE THREAD

**Issue by sagarvora** [frappe/bench#1468]
Currently, we use the Python version of bench CLI which is wrong:
https://github.com/frappe/bench/blob/develop/bench/utils/bench.py#L464

This is triggered when running `bench update`

**Comment by gavindsouza** [comment]
Good catch - this should be EXEC `{bench.env.python} -m compileall ./apps` instead. You'll benefit from this only if cli installed + env python are the same 😄 

---

Though, I do wonder if we need `compileall` at all - I'm not sure if concurrent running PVMs try to generate pyc simultaneously...I'm guessing this doesn't really do much at this point in time/tech matrix 🤔
