### ISSUE TITLE
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead

### ISSUE THREAD

**Issue by Spixmaster** [frappe/bench#1472]
When working with MariaDB, this software uses the executable `mysql` which is deprecated. The following error message occurs.

```
mysql: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb' instead
```

You need to switch to `mariadb`.

**Comment by ankush** [comment]
We mostly just need to find instances where `mysql` is used in commands, check if `mariadb` works as equivalent there and replace them. 

This needs to be done in Frappe and Bench both.
