### ISSUE TITLE
autoreload not found

### ISSUE THREAD

**Issue by Mutantpenguin** [frappe/bench#1487]
Issue: Bug report

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - PyPI [latest](https://pypi.org/project/frappe-bench/) 
 - master         (minor bug fixes)
 - v5.x           (Merged with develop on every release)
 - develop        (all updates)

Is reproducible on version 5.17.2 from PyPI.

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:
The documentation at both https://frappeframework.com/docs/user/en/bench/frappe-commands and https://frappeframework.com/docs/user/en/bench/resources/bench-commands-cheatsheet says that you can use `bench console --autoreload`, but this doesn't work.

Searching for the word `autoreload` in the sources of bench on github comes up empty.

**To Reproduce** :page_with_curl:
1. Open a command prompt in a bench
2. type `bench console --autoreload`
3. does not work

**Expected behavior** :chart_with_upwards_trend:
An ipython instance with autoreload.

**Screenshots** :crystal_ball:
```bash
Usage: bench  console [OPTIONS]
Try 'bench  console --help' for help.

Error: no such option: --autoreload
```

**OS (please complete the following information):** :cyclone:
- [x] Linux: `Ubuntu:22.04`
- [ ] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: 5.17.2

**Comment by ankush** [comment]
You need to specify site, the error message is misleading.

**Comment by ankush** [comment]
Surprisingly not happening for me. But it does happen to some other frappe commands. 

![image](https://github.com/frappe/bench/assets/9079960/53190111-3321-4f4f-9276-de5b6b330370)


Are you running it on v14+ bench?

**Comment by Mutantpenguin** [comment]
I am sorry. Since it was mentioned in the cheat sheet I thought that it was functionality of bench itself, and not of frappe.

There is no way to see where a command comes from in the cheat sheet.

With frappe 14 it works as expected.
