### ISSUE TITLE
Misleading error message for site commands

### ISSUE THREAD

**Issue by ankush** [frappe/bench#1488]
Here the error should be "migrat" command not found, click usually gets typos and suggest right one but our site arg modification is probably messing with it. 

```
λ bench --site dev.localhost migrat
Usage: bench [OPTIONS] COMMAND [ARGS]...
Try 'bench --help' for help.

Error: No such option: --site
```

Related code: 

https://github.com/frappe/bench/blob/dcae3e35cf7c098fdb8ecc60c730ef68f58b70f6/bench/cli.py#L134-L138

If we merge frappe and app commands it kind works, but that will likely break other things.

**Comment by gavindsouza** [comment]
Something like the following could help probs? (But with additional changes of course - especially replace EXECV usages)

```python
		frappe_commands = get_frappe_commands()
		frappe_command_exists = cmd_from_sys in frappe_commands

		if frappe_command_exists:
			frappe_cmd()

		try:
			app_cmd()
		except Exception:
			from difflib import get_close_matches

			possibilities = get_close_matches(cmd_from_sys, frappe_commands)
			if possibilities:
				raise NoSuchOption(cmd_from_sys, possibilities=possibilities)
			raise
```

**Comment by bosue** [comment]
Related and really awful:

![IMG_1572](https://github.com/frappe/bench/assets/46800703/457a43f9-5b62-489e-96b5-6b405d41dc9b)

Aarggh… 🥵😆

_edit:_ Of course, `bench --site ap15 run-tests --app lending` does work fine. It‘s just not intuitive at all why some flags weirdly need to be set in front of the actual command whereas others have to go to the end.

**Comment by ankush** [comment]
https://github.com/frappe/bench/pull/1542

This fixes the problem, MILDLY breaking but I doubt anyone uses internal `get-frappe-commands` via bench API. So eh. :shrug: 



```
> bench --site dev.localhost migrat
Error: No such command 'migrat'.
```

**Comment by ankush** [comment]
Wait, the help message is still misleading... little less than before :laughing: 

> Try 'bench frappe --help' for help.



We can probably handle error message in Framework.

**Comment by ankush** [comment]
![image](https://github.com/frappe/bench/assets/9079960/69e089e4-f8b3-4844-aa70-28f8d33a6a6b)


Overrriding click.Group in Framework works.

**Comment by ankush** [comment]
@bosue that one is practically unfixable. `--site` will have to be come first... open to PRs if there's any to fix it.
