### ISSUE TITLE
ERROR: [plugin postcss2] Cannot read properties of undefined

### ISSUE THREAD

**Issue by ghost** [frappe/bench#1491]
### Bunch of Errors

Hello fellas,
I was installing today frappe bench and encountered some weird errors with ✘ [ERROR] [plugin postcss2] Cannot read properties of undefined (reading 'pop and indexOf')

I hope someone can help me :)

**Screenshots** :crystal_ball:
![Screenshot from 2023-10-22 14-38-21](https://github.com/frappe/bench/assets/90602545/dc7813f5-d8b7-409c-bf2c-96a7ccbf97b3)
![Screenshot from 2023-10-22 14-38-58](https://github.com/frappe/bench/assets/90602545/f2997d78-e29f-4f03-8468-d5ff48cb5297)
![Screenshot from 2023-10-22 14-39-12](https://github.com/frappe/bench/assets/90602545/3ea30407-8646-498b-a9c5-9b7d105e6cb9)
![Screenshot from 2023-10-22 14-39-30](https://github.com/frappe/bench/assets/90602545/bbf11277-6ff6-4132-8f17-980166f6cb5c)
![Screenshot from 2023-10-22 14-39-43](https://github.com/frappe/bench/assets/90602545/cf37aec0-412a-449f-82c2-de5d2842a13c)

**OS (please complete the following information):** :cyclone:
- [x] Linux: `ubuntu server:LTS`

**Comment by iamejaaz** [comment]
Same issue in MAC OS

**Comment by iamejaaz** [comment]
Try Installing node version 18 @NaviLeon
