### ISSUE TITLE
Cannot be installed on Windows 11

### ISSUE THREAD

**Issue by nikraychev** [frappe/bench#1504]
Issue: Bug report

Please make sure your issue is reproducible on the latest bench version. The currently supported branches are:
 - PyPI [latest](https://pypi.org/project/frappe-bench/) 
 - master         (minor bug fixes)
 - v5.x           (Merged with develop on every release)
 - develop        (all updates)

**Do the checklist before filing an issue:**
 - [ ] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**Describe the bug** :chart_with_downwards_trend:

**To Reproduce** :page_with_curl:

**Expected behavior** :chart_with_upwards_trend:

**Screenshots** :crystal_ball:

**OS (please complete the following information):** :cyclone:
- [ ] Linux: `distro:version`
- [ ] macOS: `version`
- [x] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch:
- Frappe Version:
- ERPNext Version:

**Additional context** :page_facing_up:

**Possible Solution** :bookmark_tabs:
Any idea what might be causing the issue. Or if you have a proposed solution to the problem.

**Comment by nikraychev** [comment]
python easy-install.py --prod --email vbg@abv.bg


2023-12-02 07:16:22,076 - INFO - Running Production Setup
2023-12-02 07:16:22,094 - ERROR - Docker Compose generation failed
Traceback (most recent call last):
  File "C:\Apache24\htdocs\frappe_docker\easy-install.py", line 150, in setup_prod
    subprocess.run(
  File "C:\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by nikraychev** [comment]
[Sat Dec 02 07:23:09.653607 2023] [authz_core:error] [pid 36796:tid 1360] [client 127.0.0.1:56943] AH01630: client denied by server configuration: C:/Apache24/htdocs/akaunting/.htaccess

[Sat Dec 02 07:47:09.367725 2023] [cgi:error] [pid 36796:tid 1344] (OS 2)The system cannot find the file specified.  : [client 127.0.0.1:57434] couldn't create child process: 720002: easy-install.py, referer: http://localhost/frappe_docker/

[Sat Dec 02 07:47:09.367725 2023] [cgi:error] [pid 36796:tid 1344] (OS 2)The system cannot find the file specified.  : [client 127.0.0.1:57434] AH01223: couldn't spawn child process: C:/Apache24/htdocs/frappe_docker/easy-install.py, referer: http://localhost/frappe_docker/

**Comment by ankush** [comment]
Windows was never supported. 


Try https://github.com/D-codE-Hub/Guide-to-Install-Frappe-ERPNext-in-Windows-Using-Docker
