### ISSUE TITLE
Cannot listen in port 443 (how can I change ERPNet port)

### ISSUE THREAD

**Issue by jaimestuardo** [frappe/bench#1510]
Hello, I ran this command:

`python3 easy-install.py --prod --email my@example.com --sitename erp.example.com`

After some processing, this message is shown in console:

```
Error response from daemon: driver failed programming external connectivity on endpoint frappe-proxy-1 (2e353b1161f0659e52c53e806b05e5b4df95015db34ea698d9e6837a0393c500): Error starting userland proxy: listen tcp4 0.0.0.0:443: bind: address already in use
  Docker Compose failed, please check the container logs
 Command '['/usr/bin/docker', 'compose', '-p', 'frappe', '-f', '/root/frappe-compose.yml', 'up', '-d']' returned non-zero exit status 1.
```

It says that it cannot listen on port 443, which is obvious, because that port is used by Apache server.

I need to create a site whose URL is erp.example.com, listening on port 443. How can I do that? I tried also to use other port and then used a ReverseProxy in Apache, but I did not find a way to specify a different port.

Any help, please?

**Comment by ankush** [comment]
You might already have something else running on 443 port. 

https://www.cyberciti.biz/faq/what-process-has-open-linux-port/

**Comment by jaimestuardo** [comment]
> You might already have something else running on 443 port.
> 
> https://www.cyberciti.biz/faq/what-process-has-open-linux-port/

Excuse me, but, have you read the post?

I wrote that I know Apache is listening on 443 port. The question was, how can I configure a different port in ERPNext installation.

**Comment by ankush** [comment]
Try asking in https://discuss.frappe.io/

GitHub is primarily for reporting bugs and feature request.
