### ISSUE TITLE
Handle FATAL processes better

### ISSUE THREAD

**Issue by ankush** [frappe/bench#1518]
`startretries` should be set to avoid instant failure of some process due to temporary problems like disk full or port not available etc

**Comment by akhilnarang** [comment]
This should be set to some relatively low number, maybe 5 tries or something?

**Comment by ankush** [comment]
Default is 3, 10 should be good enough IMO. 10 retries ~= 55 seconds max.

**Comment by ankush** [comment]
Since this is fatal error and not really reported to user in anyway unless they check status :sweat_smile: Retries don't cost us anything.

**Comment by akhilnarang** [comment]
> Since this is fatal error and not really reported to user in anyway unless they check status 😅 Retries don't cost us anything.

Yeah makes sense.
