### ISSUE TITLE
make-app : Broken and Undocumented

### ISSUE THREAD

**Issue by brian-pond** [frappe/bench#1530]
* Bench version 5.21.4
* Frappe version 15.11

###  Command "make-app" is undocumented.
I cannot find any documentation explaining the purpose or syntax of `bench make-app`.  There are a few discuss.frappe.com posts.  But nothing official, and nothing appears in a search engine.

![image](https://github.com/frappe/bench/assets/19827963/3f73eb24-e1d6-4a1b-b71e-a29be625af88)

Without knowing what "DESTINATION" means, I cannot use this command (_even if I understood its purpose_)

-----

### Other Thoughts
Generally, I'm confused about how change management is happening in Bench.
If this `make-app` command is not read for "production" use, and it undocumented, why was it merged from `develop` into `v5.x`?

**Comment by ankush** [comment]
This is just internal command to interop bench with framework. End users can just use `new-app`.
