### ISSUE TITLE
add frappe-tag feature to get_app

### ISSUE THREAD

**Issue by istvano** [frappe/bench#154]
Hi,

I think this would be a great addition to brench. At the moment one can only pass the branch parameter to the script which allows the install script to install a specific branch.

While this is very useful during development it is not ideal for release management.

I think it would be great to be able to pass a '--frappe-tag' parameter to brench to checkout a given tag.

I am happy to modify the setup_frappe.sh although I would apprecite if someone could help out with the Python part to implement a quick change in 

https://github.com/frappe/bench/blob/master/bench/app.py

``` python
def get_app(app, git_url, branch=None, bench='.', build_asset_files=True):
```

to support a new parameter so that I can pass a tag name to the installer.

`
bench init frappe-bench --frappe-tag $FRAPPE_TAG--apps_path $ERPNEXT_APPS_JSON"
`

This could be used to build a docker container with a specific version in it. Also could be used for other release management tools. see  #105 

Is there anybody willing to do the python part quickly ?

Thanks a lot

**Comment by istvano** [comment]
Hi,

Apparently from git 1.8 git --branch can also take tags

Documentation for 1.8.5.2 of git clone states.

--branch can also take tags and detaches the HEAD at that commit in the resulting repository.

so I will try this first

**Comment by anandpdoshi** [comment]
That's seems suitable workaround till we fix this
