### ISSUE TITLE
Missing command new-site on bench version v5.22.3

### ISSUE THREAD

**Issue by lekhanh1234** [frappe/bench#1543]
Issue: Bug report

**Do the checklist before filing an issue:**
 - [x] Can you replicate the issue on the supported bench versions?
 - [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome

**To Reproduce** :page_with_curl:
1. Run command "bench new-site"
2. Error shows "Error: No such command 'new-site'"

**Expected behavior** :chart_with_upwards_trend:
Expect command "bench new-site" to works as normal

**OS (please complete the following information):** :cyclone:
- [ ] Linux: `distro:version`
- [x] macOS: `version`
- [ ] Windows `version`
- [ ] Others? `haros:distro:version`

**Version Information**

Can be found out by running `bench version` in your respective bench folder.
- Bench Branch: [v5.22.3](https://github.com/frappe/bench/releases/tag/v5.22.3)

**Additional context** :page_facing_up:
N/A

**Possible Solution** :bookmark_tabs:
N/A

**Comment by ankush** [comment]
Are you executing it in bench directory?

![image](https://github.com/frappe/bench/assets/9079960/a0a81126-871c-4e8a-867f-4ec921ace4e0)
