### ISSUE TITLE
`tool.bench.dev-dependencies` can't work with packages in the form `coverage[toml]` (optinal dependency)

### ISSUE THREAD

**Issue by Mutantpenguin** [frappe/bench#1544]
I really like `tool.bench.dev-dependencies` to install dev dependencies, but never really understood why the syntax to specify a packages name and version differs from the standard way of specifying them.

Because of that, installation of packages in the form `coverage[toml]` is just not possible for us.

For an explanation: this doesn't install `coverage` and also `toml`, but a special version of the `coverage` package with built in toml support (which is necessary for `coverage` to work with a `pyproject.toml`).

For further explanation about this package syntax have a look at stackoverflow where several other examples can be seen:
https://stackoverflow.com/questions/46775346/what-do-square-brackets-mean-in-pip-install

I would recommend also allowing the usual syntax for specifying packages to not break backwards compatibility:
```toml
[tool.bench.dev-dependencies]
pyngrok = "~=5.0.5"
dependencies = [
    "coverage[toml]"
]
```

**Comment by ankush** [comment]
```toml
[tool.bench.dev-dependencies]
"coverage['toml']" = "~=6.5.0"
```

This seems to work for me, doesn't look elegant but :grimacing:

**Comment by Mutantpenguin** [comment]
Thanks, that's totally fine for me!

I am going to try it out and will give a feedback here.

**Comment by ankush** [comment]
btw most optional packages like this just add dependencies, so they also be solved by adding them manually. 

I'll add `tomli` to deps as it's quite useful pre 3.11.

**Comment by Mutantpenguin** [comment]
Works great. Thank you very much. Beforehand I just tried `coverage[toml]` (without the `'`) which didn't work.

In this case installing them manually as dependencies is not enough, it really installs a special version of `coverage`.
