### ISSUE TITLE
`bench --help` should not give a warning when running in a non-bench directory

### ISSUE THREAD

**Issue by Delta456** [frappe/bench#1550]
## Description of the issue

`bench --h` gives a warning when running in a non-bench directory when it shouldn't because `--help` is a generic flag and isn't related to the current directory just like `--version`

## Context information (for bug reports)

**Output of `bench version`**
```
5.22.3
```

## Steps to reproduce the issue

1. Type `bench --help`
2. Look at the warning

### Observed result

![image](https://github.com/frappe/frappe/assets/28479139/22660b7d-eaa6-4d1d-a4ff-b3c1fec5877e)

### Expected result

No warning for `--help` just like there isn't for `--version`

![image](https://github.com/frappe/frappe/assets/28479139/4e9c47a3-ebd7-420c-b16e-d1a0744db5b0)

## Additional information

Pop OS, Installed from pip3

**Comment by ankush** [comment]
Best to leave this in. Not executing command in bench dir is frequent confusion.

Also help inside bench dir and outside bench dir is different. 

Outside of bench, only "init" is the command that's actually used like 99% of the time. 

Ref https://github.com/frappe/bench/blob/develop/bench/cli.py#L117
