### ISSUE TITLE
bench uninstall-app cannot delete app that is not yet associated with a site

### ISSUE THREAD

**Issue by chrisjameslennon** [frappe/bench#1566]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
I can't remove an app in bench that I have not yet associated with a site, even with --force

**Describe the solution you'd like**
`bench uninstall-app` should consider the use case where the app has not yet been associated with a site

**Describe alternatives you've considered**
perhaps I need to create a new site, then install the app on the site. However the app was created with `bench new-app` so this is not possible. Only option I can see it completely remove the bench and re-add a clean bench

**Comment by akhilnarang** [comment]
`bench remove-app` should work for this usecase.
