### ISSUE TITLE
Frappe fails to start after new installation

### ISSUE THREAD

**Issue by javieralmancevo** [frappe/bench#162]
I installed frappe bench the 'easy way' following [this page instructions](https://github.com/frappe/bench). I basically used the two commands:

>wget https://raw.githubusercontent.com/frappe/bench/master/install_scripts/setup_frappe.sh
>sudo bash setup_frappe.sh --setup-production

Everything went smoothly, no errors.

Then I cd into the newly created frappe-bench folder and run bench start and this is the log I get:

name@computer:~/frappe-bench$ bench start
12:09:20 system               | redis_cache.1 started (pid=3470)
12:09:20 system               | worker.1 started (pid=3467)
12:09:20 system               | workerbeat.1 started (pid=3466)
12:09:20 system               | web.1 started (pid=3469)
12:09:20 system               | redis_async_broker.1 started (pid=3468)
12:09:20 redis_async_broker.1 | [3475] 01 Dec 12:09:20.173 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
12:09:20 redis_async_broker.1 | [3475] 01 Dec 12:09:20.173 # Creating Server TCP listening socket *:12311: bind: Address already in use
12:09:20 system               | redis_async_broker.1 stopped (rc=1)
12:09:20 system               | socketio.1 started (pid=3471)
12:09:20 system               | sending SIGTERM to workerbeat.1 (pid 3466)
12:09:20 system               | sending SIGTERM to worker.1 (pid 3467)
12:09:20 system               | sending SIGTERM to web.1 (pid 3469)
12:09:20 system               | sending SIGTERM to socketio.1 (pid 3471)
12:09:20 system               | sending SIGTERM to redis_cache.1 (pid 3470)
12:09:20 system               | workerbeat.1 stopped (rc=-15)
12:09:20 redis_cache.1        | [3478] 01 Dec 12:09:20.180 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
12:09:20 redis_cache.1        | [3478] 01 Dec 12:09:20.180 # Creating Server TCP listening socket *:11311: bind: Address already in use
12:09:20 system               | worker.1 stopped (rc=-15)
12:09:20 system               | web.1 stopped (rc=-15)
12:09:20 system               | redis_cache.1 stopped (rc=1)
12:09:20 system               | socketio.1 stopped (rc=-15)
name@computer:~/frappe-bench$ 

It seems there is a problem with redis but I have no idea why it happened or where to start looking for a solution as I have no experience with it.

**Comment by javieralmancevo** [comment]
So I run the command netstat -tlpn and it seems the tcp sockets are being used because redis is already running there:

tcp6       0      0 :::11311                :::*                    LISTEN      2507/redis-server *
tcp6       0      0 :::12311                :::*                    LISTEN      2505/redis-server *

But if redis-server is already running I dont understand why frappe bench is not using it.

**Comment by javieralmancevo** [comment]
After some probing around I run

name@computer:~/frappe-bench$ redis-benchmark -q -n 1000 -c 10 -P 5
PING_INLINE: 166666.67 requests per second
PING_BULK: 166666.67 requests per second
SET: 166666.67 requests per second
GET: 333333.34 requests per second
INCR: 333333.34 requests per second
LPUSH: 333333.34 requests per second
LPOP: 333333.34 requests per second
SADD: 333333.34 requests per second
SPOP: 333333.34 requests per second
LPUSH (needed to benchmark LRANGE): 333333.34 requests per second
LRANGE_100 (first 100 elements): 35714.29 requests per second
LRANGE_300 (first 300 elements): 10638.30 requests per second
LRANGE_500 (first 450 elements): 7194.24 requests per second
LRANGE_600 (first 600 elements): 3968.25 requests per second
MSET (10 keys): 62500.00 requests per second

So redis is working fine. But for some reason bench start is trying to start another instance of the server when its already running.

**Comment by anandpdoshi** [comment]
@javieralmancevo you have used `--setup-production`

To go into development mode, do the following: https://github.com/frappe/bench/wiki/Stopping-Production-and-starting-Development

**Comment by javieralmancevo** [comment]
anandpdoshi, thanks for the quick answer but after following exactly those instructions I get the same error as before.

**Comment by anandpdoshi** [comment]
Do
```
sudo service nginx stop
sudo service supervisord stop
```

**Comment by javieralmancevo** [comment]
I used sudo to stop the services.

In any case I fail to see how nginx or supervisor matter since the problem is with redis:

12:45:35 system               | web.1 started (pid=4377)
12:45:35 system               | workerbeat.1 started (pid=4378)
12:45:35 system               | redis_cache.1 started (pid=4379)
12:45:35 system               | worker.1 started (pid=4376)
12:45:35 system               | redis_async_broker.1 started (pid=4385)
12:45:35 system               | socketio.1 started (pid=4381)
12:45:35 redis_cache.1        | [4386] 01 Dec 12:45:35.385 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
12:45:35 redis_cache.1        | [4386] 01 Dec 12:45:35.385 # Creating Server TCP listening socket *:11311: bind: Address already in use
12:45:35 system               | redis_cache.1 stopped (rc=1)
12:45:35 system               | sending SIGTERM to workerbeat.1 (pid 4378)
12:45:35 system               | sending SIGTERM to worker.1 (pid 4376)
12:45:35 system               | sending SIGTERM to web.1 (pid 4377)
12:45:35 system               | sending SIGTERM to socketio.1 (pid 4381)
12:45:35 system               | sending SIGTERM to redis_async_broker.1 (pid 4385)
12:45:35 system               | workerbeat.1 stopped (rc=-15)
12:45:35 system               | socketio.1 stopped (rc=-15)
12:45:35 redis_async_broker.1 | [4392] 01 Dec 12:45:35.387 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
12:45:35 redis_async_broker.1 | [4392] 01 Dec 12:45:35.387 # Creating Server TCP listening socket *:12311: bind: Address already in use
12:45:35 system               | redis_async_broker.1 stopped (rc=-15)
12:45:35 system               | worker.1 stopped (rc=-15)
12:45:35 system               | web.1 stopped (rc=-15)

**Comment by anandpdoshi** [comment]
Because in production setup, supervisor is used to start redis at port 11311 and bench start is trying to start redis again at port 11311. Hence the error: `12:45:35 redis_cache.1 | [4386] 01 Dec 12:45:35.385 # Creating Server TCP listening socket *:11311: bind: Address already in use`

Try checking:
ps aux | grep redis

**Comment by javieralmancevo** [comment]
Ok, in Ubuntu 14.04 the supervisor service is called supervisor not supervisord. After stopping the service for real, now 'bench start' seems to be working. Thanks for the quick answers.

**Comment by anandpdoshi** [comment]
@javieralmancevo are you on discuss.erpnext.com? We usually expect such questions on the forum and not issues. We try to keep limit the issues list to feature requests or bug reports.

**Comment by javieralmancevo** [comment]
Ok, Ill use the other forum for this kind of issues next time.
