### ISSUE TITLE
frappe developer version installation problem

### ISSUE THREAD

**Issue by ni8mr** [frappe/bench#166]
I have tried to setup the developer version via this command 

    sudo bash setup_frappe.sh

But i am getting **production version** (with ERPNext) installed. 

At first, i thought i have mistaken the command and forgot to omit **--setup-production**. But i have tried twice and still getting same result.

 Guys, may be, you should take a look into the **setup_frappe.sh** file.

**Comment by vjFaLk** [comment]
I'm having the same issue

**Comment by pdvyas** [comment]
Tested on ubuntu 14.04, worked as expected.

setup-production means nginx and supervisor setup and master branch checked out instead of develop.

**Comment by vjFaLk** [comment]
Okay, I just realized that this is merely confusion. ERPNext being installed with bench is intended behaviour, and that me and @ni8mr thought was only a part of the production setup.

**Comment by ni8mr** [comment]
I understand it now. So i am closing the issue.
