### ISSUE TITLE
How to remove the frappe_password.txt and how to perform full backup of ERPNext?

### ISSUE THREAD

**Issue by rainersg** [frappe/bench#169]
Hi all,
I have installed ERPNext in DigitalOcean successfully. But I noticed that the password for the Frappe, MariaDB and Administrator is stored in the txt file. I want to remove it for security reason. Or is it safe to keep inside? If I want to access to the txt file, what is the command to open it? Same for removing the file too.

And how will I take a full backup of the database and the ERPNext files? I am not familar with the Linux commands. Can you all guide me along the way on these issues I face?

Thanks!

**Comment by rmehta** [comment]
@rainersg for linux help, checkout linux forum!

**Comment by rainersg** [comment]
@rmehta thanks for the help, will check there.

But anyone know how to import Insightly CSV and XML files to the ERPNext? It seems that the fields are totally different. How will I do this?

**Comment by rmehta** [comment]
Please post help queries on the forum https://discuss.erpnext.com
