### ISSUE TITLE
Bench update recognizes "upstream" but not "origin" for apps

### ISSUE THREAD

**Issue by dottenbr** [frappe/bench#174]
As per discussion with @anandpdoshi 'bench update' recognizes "upstream" as a source for the pull but not "origin". Either this has to be clearly documented in the "creating a frappe ap tutorial" and the bench error message should indicate this or it should be fixed that it recognizes whatever is the remote and if there is multiple it would ask?

**Comment by yashodhank** [comment]
@dottenbr I am in process of updating Developers tutorials, I will make sure to add this as it will be very useful. Thanks for sharing.
