### ISSUE TITLE
Feature - Bench Update from Frappe Desk

### ISSUE THREAD

**Issue by dottenbr** [frappe/bench#175]
@rmehta I remember it had been discussed as a paid pro feature to be able to update the frappe bench from within Frappe Desk. Is this still being considered? This could potentiall resolve a lot of issues non linux gurus have with updating.

**Comment by rmehta** [comment]
@dottenbr we are plannig to make this a free feature, ETA 2-3 months

**Comment by dottenbr** [comment]
Excellent! I love that this will be a free feature.
