### ISSUE TITLE
Converting account to Group, copying transactions to a target account

### ISSUE THREAD

**Issue by Tropicalrambler** [frappe/bench#179]
Feature request:

Using the accounting page, when you are modifying accounts, it would be great to enable the user to convert an existing account to a group (folder) and during this task, have the user copy those transactions to a target account specified during this task, which could even be a new account under the account being converted to a group (folder)

As a reference, GNUCash provides this ability.

**Comment by vjFaLk** [comment]
If you're still having this issue please post on https://github.com/frappe/erpnext

Cheers!
