### ISSUE TITLE
Access levels in printing

### ISSUE THREAD

**Issue by ahmederp** [frappe/bench#182]
Team,

This year we ran our appraisals cycle through ERPnext. We customized the format, and added fields viewable only by managers and gave these access level 1, also some fields are only visible for the GM with access level 2.

Everything was fine until an employee decided to print his appraisal, and then we were surprised to see that all the feedback was visible on the print!!!! Even the GM comments were visible to a normal employee.

You can imagine the embarrassment this has caused to some employees.

Please look into this, and ensure that fields that are not visible to an access level in the form, should not be visible in a print as well.

Regards,
Ahmed

**Comment by vjFaLk** [comment]
If you're still having this issue please post on https://github.com/frappe/erpnext

Cheers!
