### ISSUE TITLE
followed Basic Usage tutorial got socketio ENOENT

### ISSUE THREAD

**Issue by bayuiravvan** [frappe/bench#188]
Hi, I've followed Basic Usage tutorial, app was running. But when I accessed localhost:3000 I got the following error from socketio:
`Error: ENOENT: no such file or directory, stat '/home/bayu/Sources/frappe-bench/index.html'
   at Error (native) `

And here is the console log:
`Sat, 27 Feb 2016 11:32:03 GMT express deprecated res.sendfile: Use res.sendFile instead at apps/frappe/socketio.js:19:7`
`Error: ENOENT: no such file or directory, stat '/home/bayu/Sources/frappe-bench/index.html'
   at Error (native) `

Tried the second time, and got the same result. Please help. Thanks in advance.

**Comment by rmehta** [comment]
Can you post help queries on https://disucss.erpnext.com
