### ISSUE TITLE
bench update error

### ISSUE THREAD

**Issue by s1rleblanc** [frappe/bench#189]
Hi everyone..

Im on OS X and im trying to updating the bench but i had this error:

$ bench update
"All the stuff"
frappe: ERROR (no such group)
frappe: ERROR (no such group)

and i glad to know what can i do to solve this, i tried added a group with the name frappe but don't worked.

Thank you in advance!.

**Comment by anandpdoshi** [comment]
The production setup isn't ready for Mac OS X.  You should change it to development setup for now. We are going to work on making the bench all OS compatible next month.

**Comment by s1rleblanc** [comment]
thank you @anandpdoshi!!!

where I can subscribe to find out the latest news  and know when it is ready for OS X ? #

**Comment by anandpdoshi** [comment]
We will post such an important update on our forum: discuss.erpnext.com

**Comment by s1rleblanc** [comment]
thank you again.. i'll waiting
