### ISSUE TITLE
[Request] Implement a remove-site funciton

### ISSUE THREAD

**Issue by jfschubert** [frappe/bench#193]
Hi,

tinkering around i found out that there is no function to delete sites via bench

**Comment by anandpdoshi** [comment]
bench drop-site sitename

**Comment by jfschubert** [comment]
Thanks.

Havent seen it mentioned anywhere.

**Comment by anandpdoshi** [comment]
@jfschubert I agree. We lack in documentation :(

Try doing `bench --help`. You will find many useful commands.
