### ISSUE TITLE
If invoice is in draft mode duplicate delivery note should not display in get item from delivery note

### ISSUE THREAD

**Issue by mkumar9699** [frappe/bench#194]
I have 10 delivery notes and when I raise invoice, select customer and click get item from delivery note but I can select same delivery note  while it should not be displayed in get item from delivery note. It creates confusion and will get wrong invoice. 

Please help

Thanks
Mithilesh Kumar

**Comment by vjFaLk** [comment]
If you're still having this issue please post on https://github.com/frappe/erpnext

Cheers!
