### ISSUE TITLE
Proposal `bench setup --development`

### ISSUE THREAD

**Issue by MaxMorais** [frappe/bench#197]
Hello folks!

Have some months, that I'm using a alternative way of setup environments to development, and it's working very well to me, and I believe that can help a lot the others!

I'm using vagrant enviroment, defined in https://github.com/frappe/erpnext_vagrant

My active enviroment run with 
- supervisor managing
  - memcached
  - frappe-worker
  - frappe-workerbeat
  - redis-cache
  - redis-async-broker
  - node-socket-io
- nginx
- bench start
  - frappe-web

I believe that this is awesome because on every manually restart of `bench start` all other services are already running, and dont will be touch!

Another detail is, `werkzeug` autorestart on file change, dont work on virtual machine shared folders, so, reduce the time of setup on every restart, is crucial!

The unique issue that I found with this scheme is, when I up my vagrant on the init of the day, I need restart my supervisor, but this is not a readache at all.

The idea for `bench setup --development` is generate the config files, in the proposed layout.

**Comment by rmehta** [comment]
Sure, send a PR!
