### ISSUE TITLE
[Feature request] Items and Serialize item tracking for Website user 

### ISSUE THREAD

**Issue by blackyzero** [frappe/bench#200]
Hello Team,

Would it possible to add items and serialize item be available in Website user page? This mean we could give permission for Website user to see their Serialize items (after ordered or purchased).
This would be great for Customers or Supliers to track their individual items/serialize.

Thanks a lot.
<img width="940" alt="screen shot 2016-04-08 at 7 35 19 pm" src="https://cloud.githubusercontent.com/assets/4286063/14404742/da025388-fea7-11e5-9c3a-e7948c7c57d6.png">

**Comment by saurabh6790** [comment]
Please open the issue at https://github.com/frappe/erpnext/issues/new
