### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by vjFaLk** [frappe/bench#201]
- [x] Update outdated Wiki articles
- [ ] More guides to solve common problems
- [x] Quick Reference Guide
- [x] Move wiki + readme to docs

**Comment by yashodhank** [comment]
I am updating developers tutorials with latest screenshots and some more details for first timers.

**Comment by vjFaLk** [comment]
@yashodhank Awesome! The documentation is here > https://github.com/frappe/frappe/tree/develop/frappe/docs/user/en/bench
