### ISSUE TITLE
 No such command "worker". Server shutdowns automatically 

### ISSUE THREAD

**Issue by iqtrix** [frappe/bench#212]
ubuntu@ip-172-31-34-32:~$ bench start
2016-04-30 13:57:33 [2185] [WARNING] Your terminal is not configured to receive UTF-8 encoded text. Please adjust your locale settings or force UTF-8 output by setting PYTHONIOENCODING="utf-8".
13:57:33 system           | redis_queue.1 started (pid=2204)
13:57:33 redis_queue.1    | [2213] 30 Apr 13:57:33.798 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
13:57:33 redis_queue.1    |                 _._                                                  
13:57:33 redis_queue.1    |            _.-``__ ''-._                                             
13:57:33 redis_queue.1    |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
13:57:33 redis_queue.1    |   .-`` .-```.  ```\/    _.,_ ''-._                                   
13:57:33 redis_queue.1    |  (    '      ,       .-`  | `,    )     Running in stand alone mode
13:57:33 redis_queue.1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 11000
13:57:33 redis_queue.1    |  |    `-._   `._    /     _.-'    |     PID: 2213
13:57:33 redis_queue.1    |   `-._    `-._  `-./  _.-'    _.-'                                   
13:57:33 redis_queue.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
13:57:33 redis_queue.1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
13:57:33 redis_queue.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
13:57:33 redis_queue.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
13:57:33 redis_queue.1    |  |    `-._`-._        _.-'_.-'    |                                  
13:57:33 redis_queue.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
13:57:33 redis_queue.1    |       `-._    `-.__.-'    _.-'                                       
13:57:33 redis_queue.1    |           `-._        _.-'                                           
13:57:33 redis_queue.1    |               `-.__.-'                                               
13:57:33 redis_queue.1    | 
13:57:33 redis_queue.1    | [2213] 30 Apr 13:57:33.798 # Server started, Redis version 2.8.4
13:57:33 redis_queue.1    | [2213] 30 Apr 13:57:33.798 * The server is now ready to accept connections on port 11000
13:57:33 system           | web.1 started (pid=2205)
13:57:33 system           | worker_long.1 started (pid=2206)
13:57:33 system           | schedule.1 started (pid=2207)
13:57:33 system           | watch.1 started (pid=2211)
13:57:33 system           | worker_default.1 started (pid=2212)
13:57:33 system           | redis_cache.1 started (pid=2209)
13:57:33 redis_cache.1    | [2223] 30 Apr 13:57:33.823 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
13:57:33 redis_cache.1    |                 _._                                                  
13:57:33 redis_cache.1    |            _.-``__ ''-._                                             
13:57:33 redis_cache.1    |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
13:57:33 redis_cache.1    |   .-`` .-```.  ```\/    _.,_ ''-._                                   
13:57:33 redis_cache.1    |  (    '      ,       .-`  | `,    )     Running in stand alone mode
13:57:33 redis_cache.1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 13000
13:57:33 redis_cache.1    |  |    `-._   `._    /     _.-'    |     PID: 2223
13:57:33 redis_cache.1    |   `-._    `-._  `-./  _.-'    _.-'                                   
13:57:33 redis_cache.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
13:57:33 redis_cache.1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
13:57:33 redis_cache.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
13:57:33 redis_cache.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
13:57:33 redis_cache.1    |  |    `-._`-._        _.-'_.-'    |                                  
13:57:33 redis_cache.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
13:57:33 redis_cache.1    |       `-._    `-.__.-'    _.-'                                       
13:57:33 redis_cache.1    |           `-._        _.-'                                           
13:57:33 redis_cache.1    |               `-.__.-'                                               
13:57:33 redis_cache.1    | 
13:57:33 redis_cache.1    | [2223] 30 Apr 13:57:33.824 # Server started, Redis version 2.8.4
13:57:33 redis_cache.1    | [2223] 30 Apr 13:57:33.824 * The server is now ready to accept connections on port 13000
13:57:33 system           | worker_short.1 started (pid=2210)
13:57:33 system           | socketio.1 started (pid=2208)
13:57:33 system           | redis_socketio.1 started (pid=2230)
13:57:33 redis_socketio.1 | [2236] 30 Apr 13:57:33.902 # Unable to set the max number of files limit to 10032 (Operation not permitted), setting the max clients configuration to 3984.
13:57:33 redis_socketio.1 |                 _._                                                  
13:57:33 redis_socketio.1 |            _.-``__ ''-._                                             
13:57:33 redis_socketio.1 |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
13:57:33 redis_socketio.1 |   .-`` .-```.  ```\/    _.,_ ''-._                                   
13:57:33 redis_socketio.1 |  (    '      ,       .-`  | `,    )     Running in stand alone mode
13:57:33 redis_socketio.1 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 12000
13:57:33 redis_socketio.1 |  |    `-._   `._    /     _.-'    |     PID: 2236
13:57:33 redis_socketio.1 |   `-._    `-._  `-./  _.-'    _.-'                                   
13:57:33 redis_socketio.1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
13:57:33 redis_socketio.1 |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
13:57:33 redis_socketio.1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
13:57:33 redis_socketio.1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
13:57:33 redis_socketio.1 |  |    `-._`-._        _.-'_.-'    |                                  
13:57:33 redis_socketio.1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
13:57:33 redis_socketio.1 |       `-._    `-.__.-'    _.-'                                       
13:57:33 redis_socketio.1 |           `-._        _.-'                                           
13:57:33 redis_socketio.1 |               `-.__.-'                                               
13:57:33 redis_socketio.1 | 
13:57:33 redis_socketio.1 | [2236] 30 Apr 13:57:33.903 # Server started, Redis version 2.8.4
13:57:33 redis_socketio.1 | [2236] 30 Apr 13:57:33.903 * The server is now ready to accept connections on port 12000
13:57:36 worker_long.1    | Usage: bench [OPTIONS] COMMAND [ARGS]...
13:57:36 worker_long.1    | 
13:57:36 schedule.1       | Usage: bench [OPTIONS] COMMAND [ARGS]...
13:57:36 schedule.1       | 
13:57:36 web.1            | Usage: bench [OPTIONS] COMMAND [ARGS]...
13:57:36 web.1            | 
13:57:36 worker_long.1    | Error: No such command "worker".
13:57:36 schedule.1       | Error: No such command "schedule".
13:57:36 worker_short.1   | Usage: bench [OPTIONS] COMMAND [ARGS]...
13:57:36 worker_short.1   | 
13:57:36 web.1            | Error: No such command "serve".
13:57:36 worker_short.1   | Error: No such command "worker".
13:57:36 watch.1          | Usage: bench [OPTIONS] COMMAND [ARGS]...
13:57:36 watch.1          | 
13:57:36 worker_default.1 | Usage: bench [OPTIONS] COMMAND [ARGS]...
13:57:36 worker_default.1 | 
13:57:36 watch.1          | Error: No such command "watch".
13:57:36 worker_default.1 | Error: No such command "worker".
13:57:36 system           | schedule.1 stopped (rc=2)
13:57:36 system           | sending SIGTERM to redis_socketio.1 (pid 2230)
13:57:36 system           | sending SIGTERM to worker_long.1 (pid 2206)
13:57:36 system           | sending SIGTERM to watch.1 (pid 2211)
13:57:36 system           | sending SIGTERM to redis_queue.1 (pid 2204)
13:57:36 system           | sending SIGTERM to web.1 (pid 2205)
13:57:36 system           | sending SIGTERM to worker_default.1 (pid 2212)
13:57:36 system           | sending SIGTERM to socketio.1 (pid 2208)
13:57:36 system           | sending SIGTERM to redis_cache.1 (pid 2209)
13:57:36 system           | sending SIGTERM to worker_short.1 (pid 2210)
13:57:36 redis_socketio.1 | [2236 | signal handler] (1462024656) Received SIGTERM, scheduling shutdown...
13:57:36 redis_queue.1    | [2213 | signal handler] (1462024656) Received SIGTERM, scheduling shutdown...
13:57:36 redis_cache.1    | [2223 | signal handler] (1462024656) Received SIGTERM, scheduling shutdown...
13:57:36 system           | worker_long.1 stopped (rc=-15)
13:57:36 system           | web.1 stopped (rc=-15)
13:57:36 system           | watch.1 stopped (rc=-15)
13:57:36 system           | worker_short.1 stopped (rc=-15)
13:57:36 system           | socketio.1 stopped (rc=-15)
13:57:36 redis_cache.1    | [2223] 30 Apr 13:57:36.428 # User requested shutdown...
13:57:36 redis_cache.1    | [2223] 30 Apr 13:57:36.428 # Redis is now ready to exit, bye bye...
13:57:36 system           | redis_cache.1 stopped (rc=-15)
13:57:36 system           | worker_default.1 stopped (rc=-15)
13:57:36 redis_socketio.1 | [2236] 30 Apr 13:57:36.507 # User requested shutdown...
13:57:36 redis_socketio.1 | [2236] 30 Apr 13:57:36.507 # Redis is now ready to exit, bye bye...
13:57:36 system           | redis_socketio.1 stopped (rc=-15)
13:57:36 redis_queue.1    | [2213] 30 Apr 13:57:36.510 # User requested shutdown...
13:57:36 redis_queue.1    | [2213] 30 Apr 13:57:36.510 # Redis is now ready to exit, bye bye...
13:57:36 system           | redis_queue.1 stopped (rc=-15)

**Comment by anandpdoshi** [comment]
Run `bench update`
