### ISSUE TITLE
Bench command to setup firewall

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/bench#216]
Keep the following tcp ports open:

- 80
- 443
- SSH port

**Comment by mhbu50** [comment]
+1

**Comment by vjFaLk** [comment]
@rmehta @shreyasp 

Should I integrate this into the production install as well?

**Comment by rmehta** [comment]
`bench setup firewall` ?

**Comment by shreyasp** [comment]
@vjFaLk This is more opinionated setup for the firewall, so I don't think we should enforce it on users. They can setup if they want a simpler setup using the command

**Comment by vjFaLk** [comment]
Merged with: https://github.com/frappe/bench/pull/326
