### ISSUE TITLE
Bench command to setup SSL using Letsencrypt

### ISSUE THREAD

**Issue by shreyasp** [frappe/bench#218]
- [ ] Create a bench command to setup SSL using letsencrypt.

**Comment by vjFaLk** [comment]
**Command** : `bench --site [site-name] setup letsencrypt 

or 

`bench letsencrypt [site-name]` (Sounds nicer eh?) 

- [ ] Save boilerplate cfg file in bench, ref : https://gist.github.com/xrstf/581981008b6be0d2224f
- [ ] Use jinja to modify cfg file accordingly
- [ ] Add cert files to site_config.json
- [ ] Setup and reload nginx

**Comment by anandpdoshi** [comment]
ideally, letsencrypt: true in common_site_config and it should auto-create new certificate on adding a new site 💥

**Comment by rmehta** [comment]
yeah add auto-create new certificate using scheduler
