### ISSUE TITLE
Unable to locate package tcl8.6-dev

### ISSUE THREAD

**Issue by jmatsushita** [frappe/bench#223]
Running the frappe install on a debian 7 (as recommended in the easy install notes) results in the following errors:

```
E: Unable to locate package tcl8.6-dev
E: Couldn't find any package by regex 'tcl8.6-dev'
E: Unable to locate package tk8.6-dev
E: Couldn't find any package by regex 'tk8.6-dev'
```

According to this search https://packages.debian.org/search?keywords=tcl8.6-dev tcl8.6-dev is only available on Jessie stable...

**Comment by anandpdoshi** [comment]
Try tcl8.5-dev and tk8.5-dev

@vjFalk and @shreyasp can you include this in the new installer?

Best,
Anand Doshi

ERPNext
