### ISSUE TITLE
Missing public key for mariadb repo (Ubuntu 16.04)

### ISSUE THREAD

**Issue by skylarmt** [frappe/bench#226]
The script doesn't install the correct public keys when adding the mariadb repo on Ubuntu 16.04.

```
skylar@erpnext:~$ sudo apt-get update
Get:1 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease [3,128 B]     
Ign:1 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease               
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Hit:3 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [94.5 kB]        
Hit:5 https://deb.nodesource.com/node_0.12 xenial InRelease          
Hit:6 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease                             
Fetched 192 kB in 2s (83.9 kB/s)
Reading package lists... Done
W: GPG error: http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F1656F24C74CD1D8
W: The repository 'http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: There is no public key available for the following key IDs:
F1656F24C74CD1D8  
```

The key can be installed with this command (found it [in the Dockerfile for this project](https://hub.docker.com/r/andriyg/mariadb_with_dump/))
`apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys F1656F24C74CD1D8`

**Comment by shreyasp** [comment]
@skylarmt We have fixed this issue and there is already a PR under review https://github.com/frappe/bench/pull/222.

**Comment by Wripro** [comment]
TASK [Add apt key for mariadb for Ubuntu >= 16.04] *****************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv C74CD1D8", "failed": true, "msg": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No data", "rc": 2, "stderr": "Warning: apt-key output should not be parsed (stdout is not a terminal)\ngpg: keyserver receive failed: No data\n", "stdout": "Executing: /tmp/tmp.O0pISnDzYu/gpg.1.sh --keyserver\nhkp://keyserver.ubuntu.com:80\n--recv\nC74CD1D8\n", "stdout_lines": ["Executing: /tmp/tmp.O0pISnDzYu/gpg.1.sh --keyserver", "hkp://keyserver.ubuntu.com:80", "--recv", "C74CD1D8"]}
	to retry, use: --limit @production/install.retry
I'm getting this error. how do i resolve this issue.
