### ISSUE TITLE
Beta Installer fails on wkhtmltopdf install because of Ansible bug

### ISSUE THREAD

**Issue by vjFaLk** [frappe/bench#233]

**Comment by shreyasp** [comment]
Issue is related to bug core modules in Ansible 2.1 (https://github.com/ansible/ansible-modules-core/issues/3752)

**Comment by anandpdoshi** [comment]
Any fix / workaround?

**Comment by vjFaLk** [comment]
@anandpdoshi Using Ansible 2.0

**Comment by shreyasp** [comment]
@anandpdoshi Will send out PR in sometime to install Ansible 2.0.2.0 which was used before Ansible 2.1
