### ISSUE TITLE
DNS Multi-tenancy default

### ISSUE THREAD

**Issue by blrzzzt** [frappe/bench#241]
https://frappe.github.io/frappe/user/en/bench/guides/setup-multitenancy.html

Your documentation says "DNS based multitenancy mode is enabled by default," but from my experience setting up dns multi-tenancy, this isn't the case.

If one follows the steps as per the guide:

"bench setup nginx"
throws:
Exception: Port 80 is being used by another site ...

It seems that you need to explicitly turn on multi-tenancy first with:
"bench config dns_multitenant on"

then continue as per the guide for it to work.

Just a little stumbling block that hopefully helps save someone time...

**Comment by anandpdoshi** [comment]
@blrzzzt thanks a lot for pointing this out, and sorry! @vjFaLk can you fix this?

**Comment by vjFaLk** [comment]
https://github.com/frappe/bench/pull/242
