### ISSUE TITLE
command    bench start  cause error

### ISSUE THREAD

**Issue by moustfaAyad** [frappe/bench#25]
ERROR: Procfile does not exist or is not a file

**Comment by asaraffan** [comment]
> it's work now fourmax@fourmax-To-be-filled-by-O-E-M:~/frappe-bench$ bench start 10:33:43 web.1 | started with pid 2569 10:33:43 worker.1 | started with pid 2570 10:33:43 workerbeat.1 | started with pid 2572 10:33:44 web.1 | * Running on http://0.0.0.0:8000/ 10:33:44 web.1 | * Restarting with reloader 10:33:45 workerbeat.1 | [2014-07-17 10:33:45,307: INFO/MainProcess] beat: Starting... 10:33:46 worker.1 | [2014-07-17 10:33:46,474: WARNING/MainProcess] celery@fourmax-To-be-filled-by-O-E-M ready. 10:33:52 web.1 | 127.0.0.1 - - [17/Jul/2014 10:33:52] "GET / HTTP/1.1" 404 - 10:33:53 web.1 | 127.0.0.1 - - [17/Jul/2014 10:33:53] "GET / HTTP/1.1" 404 - 10:33:53 web.1 | 127.0.0.1 - - [17/Jul/2014 10:33:53] "GET / HTTP/1.1" 404 - 10:33:54 web.1 | 127.0.0.1 - - [17/Jul/2014 10:33:54] "GET / HTTP/1.1" 404 - 10:33:55 web.1 | 127.0.0.1 - - [17/Jul/2014 10:33:55] "GET / HTTP/1.1" 404 - 10:33:57 web.1 | 127.0.0.1 - - [17/Jul/2014 10:33:57] "GET / HTTP/1.1" 404 - 10:34:00 web.1 | 127.0.0.1 - - [17/Jul/2014 10:33:59] "GET / HTTP/1.1" 404 - 10:34:00 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:00] "GET / HTTP/1.1" 404 - 10:34:00 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:00] "GET / HTTP/1.1" 404 - 10:34:01 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:01] "GET / HTTP/1.1" 404 - 10:34:02 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:02] "GET / HTTP/1.1" 404 - 10:34:25 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:25] "GET / HTTP/1.1" 404 - 10:34:51 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:51] "GET / HTTP/1.1" 404 - 10:34:51 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:51] "GET /favicon.ico HTTP/1.1" 404 - 10:34:51 web.1 | 127.0.0.1 - - [17/Jul/2014 10:34:51] "GET /favicon.ico HTTP/1.1" 404 -
> 
> when i open url http://localhost:8000/ or 0.0.0.0:8000
> 
> i see msg :Not Found
> 
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

I am also getting this same error. how you solved this? can you please the steps
