### ISSUE TITLE
Installation Issues with Beta Script

### ISSUE THREAD

**Issue by Prashanth-Murthy** [frappe/bench#261]
Hi,

Trying to install ERPNext on Ubuntu 16 LTS, encountering following error ...

> Adding ubuntu mariadb repo
Reading package lists...
Building dependency tree...
Reading state information...
software-properties-common is already the newest version (0.96.20.2).
python-software-properties is already the newest version (0.96.20.2).
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 wkhtmltox : Depends: libjpeg62-turbo but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

Tryed to install libjpeg62 separately with no success ...

Please help me out resolving this.

Regards,
Prashanth

**Comment by Prashanth-Murthy** [comment]
Additionally, i have tried the Python Script also with similar error ....

> prashanth@ubuntu:~/ERPNext$ sudo python install.py --production
Get:1 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease [3,874 B]
Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
Ign:1 http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [95.7 kB]
Hit:4 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu xenial-security InRelease
Fetched 99.5 kB in 3s (28.3 kB/s)
Reading package lists... Done
W: GPG error: http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F1656F24C74CD1D8
W: The repository 'http://ams2.mirrors.digitalocean.com/mariadb/repo/10.0/ubuntu xenial InRelease' is not signed.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: There is no public key available for the following key IDs:
F1656F24C74CD1D8
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
git is already the newest version (1:2.7.4-0ubuntu1).
python-dev is already the newest version (2.7.11-1).
python-setuptools is already the newest version (20.7.0-1).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.1).
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 wkhtmltox : Depends: libjpeg62-turbo but it is not installable
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
Traceback (most recent call last):
  File "install.py", line 264, in <module>
    install_bench(args)
  File "install.py", line 16, in install_bench
    'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel'
  File "install.py", line 149, in run_os_command
    returncode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo apt-get install -y git build-essential python-setuptools python-dev libffi-dev libssl-dev' returned non-zero exit status 100

>

**Comment by vjFaLk** [comment]
Hi, can you start afresh? I think the previous installer might have made changes that is affecting the second one.
