### ISSUE TITLE
v7 bench source in production is in develop

### ISSUE THREAD

**Issue by ccfiel** [frappe/bench#268]
I install erpnext in a production setting. When I look at the git of .bench its pointed in develop. Production should be pointed in master and its difficult to switch to master. see below in this issue https://github.com/frappe/bench/issues/265

**Comment by vjFaLk** [comment]
Good catch! Fixed : https://github.com/frappe/bench/pull/269

**Comment by ccfiel** [comment]
@vjFaLk awesome!
