### ISSUE TITLE
Base Document Line

### ISSUE THREAD

**Issue by David-at-GitHub** [frappe/bench#274]
Dear all,

in the JSON formatted RESTful call, the base-document number (from which the document was converted/copied from) is mentioned. For example in the Delivery Note this would be the 'against_sales_order' field. This is good, but in case the same Item exists in more than one line, or in case there are multiple Sales Orders converted to the same Delivery, it would be important also to have the 
Base Document Line ID (e.g. against_sales_order_idx), as the Item Code is not unique. It would be great if this could be added to the next level Document Form and RESTful JSON file:

![image](https://cloud.githubusercontent.com/assets/15001320/17129390/d257e3fe-52e0-11e6-8061-da136d55e3e0.png)

Thanks, David

**Comment by rmehta** [comment]
@David-at-GitHub the place to raise this is https://github.com/frappe/erpnext/issues

Seems like a reasonable thing, you an send in a pull-request with this

**Comment by David-at-GitHub** [comment]
@rmehta Thank you, I have opened the issue at https://github.com/frappe/erpnext/issues/5873 and will close this one.
