### ISSUE TITLE
Import (Module)

### ISSUE THREAD

**Issue by Hussain1975** [frappe/bench#280]
Dear Sir,

We are Manufacturer cum importer but import feature is not available in erpnext kindly tell us about it what we do?

Waiting your feed back

Thank/Regards

**Comment by yashodhank** [comment]
@Hussain1975 Glad to know you are interested in ERPNext, please head to https://discuss.erpnext.com and open an new topic and share your ideas / requirements there, if feature is useful for most of users, then it might be added to the product.

**Note:** Github Issues for ERPNext/Frappe/Bench are not for request help or features but for reporting errors and bugs to improve softwares.
