### ISSUE TITLE
Error while upgrading to v7

### ISSUE THREAD

**Issue by nick9822** [frappe/bench#299]
Hi there,

I am getting error while bench update --upgrade
`/home/frappe/frappe-bench/apps/erpnext/erpnext/schools/doctype/Assessment/Assessment.json missing
/home/frappe/frappe-bench/apps/erpnext/erpnext/schools/doctype/Fees/Fees.json missing
/home/frappe/frappe-bench/apps/erpnext/erpnext/schools/doctype/Course/Course.json missing
/home/frappe/frappe-bench/apps/erpnext/erpnext/schools/doctype/Announcement/Announcement.json missing`

Please advise, is there something wrong? I also tried `bench --site all reload-doc Schools doctype Assessment` but gives same missing error. 

You can see whole log http://pastebin.com/8JM2Kcbu

Thanks.

**Comment by shreyasp** [comment]
@nick9822 We have pushed a fix, Please try updating in sometime.

**Comment by nick9822** [comment]
Thank you for quick resolution, but now another error pops up.
`frappe.exceptions.LinkValidationError: Could not find _doctype: Student`

You can see whole log http://pastebin.com/YUZEbyjY

Thanks.

**Comment by rmehta** [comment]
pushed another fix

**Comment by nick9822** [comment]
Very thanks. :+1: 
Now its almost updated but error appeared `Sorry, user frappe is not allowed to execute '/bin/supervisorctl status' as root`

I tried changing user as root and frappe, but same error. Please advise.

Thanks.

**Comment by nick9822** [comment]
Its solved. Thanks to [https://github.com/frappe/erpnext/issues/5083](url)
