### ISSUE TITLE
errors in bench installation

### ISSUE THREAD

**Issue by ehsanquranwala** [frappe/bench#312]
hi guys
plese help me solve the problem
when i try to install bench with
sudo python install.py --develop

ehsan@ehsan-ThinkPad-T400:~/Desktop/frappe$ sudo python install.py --develop
[sudo] password for ehsan: 
Ign http://pk.archive.ubuntu.com trusty InRelease                              
Hit http://pk.archive.ubuntu.com trusty-updates InRelease                      
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://pk.archive.ubuntu.com trusty-backports InRelease                    
Hit http://pk.archive.ubuntu.com trusty Release.gpg                            
Hit http://nyc2.mirrors.digitalocean.com trusty InRelease                      
Ign http://dl.google.com stable InRelease                                      
Hit http://pk.archive.ubuntu.com trusty-updates/main Sources                   
Hit http://pk.archive.ubuntu.com trusty-updates/restricted Sources             
Hit http://security.ubuntu.com trusty-security InRelease                       
Hit http://ppa.launchpad.net trusty/main amd64 Packages                        
Hit http://pk.archive.ubuntu.com trusty-updates/universe Sources               
Ign http://mirrors.neusoft.edu.cn trusty InRelease                             
Hit http://pk.archive.ubuntu.com trusty-updates/multiverse Sources             
Hit http://nyc2.mirrors.digitalocean.com trusty/main amd64 Packages            
Hit http://dl.google.com stable Release.gpg                                    
Hit http://pk.archive.ubuntu.com trusty-updates/main amd64 Packages            
Hit http://pk.archive.ubuntu.com trusty-updates/restricted amd64 Packages      
Hit http://ppa.launchpad.net trusty/main i386 Packages                         
Hit http://nyc2.mirrors.digitalocean.com trusty/main i386 Packages             
Hit http://pk.archive.ubuntu.com trusty-updates/universe amd64 Packages        
Hit http://pk.archive.ubuntu.com trusty-updates/multiverse amd64 Packages      
Hit http://pk.archive.ubuntu.com trusty-updates/main i386 Packages             
Hit http://ppa.launchpad.net trusty/main Translation-en                        
Hit http://pk.archive.ubuntu.com trusty-updates/restricted i386 Packages       
Hit http://pk.archive.ubuntu.com trusty-updates/universe i386 Packages         
Hit http://dl.google.com stable Release                                        
Hit http://pk.archive.ubuntu.com trusty-updates/multiverse i386 Packages       
Ign http://mirrors.neusoft.edu.cn trusty Release.gpg                           
Hit http://pk.archive.ubuntu.com trusty-updates/main Translation-en            
Hit http://pk.archive.ubuntu.com trusty-updates/multiverse Translation-en      
Hit http://dl.google.com stable/main amd64 Packages                            
Hit http://pk.archive.ubuntu.com trusty-updates/restricted Translation-en      
Hit http://pk.archive.ubuntu.com trusty-updates/universe Translation-en        
Hit http://pk.archive.ubuntu.com trusty-backports/main Sources                 
Hit http://pk.archive.ubuntu.com trusty-backports/restricted Sources           
Hit http://pk.archive.ubuntu.com trusty-backports/universe Sources             
Ign http://mirrors.neusoft.edu.cn trusty Release                               
Hit http://pk.archive.ubuntu.com trusty-backports/multiverse Sources           
Hit http://pk.archive.ubuntu.com trusty-backports/main amd64 Packages          
Hit http://pk.archive.ubuntu.com trusty-backports/restricted amd64 Packages    
Hit http://pk.archive.ubuntu.com trusty-backports/universe amd64 Packages      
Hit http://pk.archive.ubuntu.com trusty-backports/multiverse amd64 Packages    
Hit http://pk.archive.ubuntu.com trusty-backports/main i386 Packages           
Hit http://pk.archive.ubuntu.com trusty-backports/restricted i386 Packages     
Hit http://pk.archive.ubuntu.com trusty-backports/universe i386 Packages       
Hit http://pk.archive.ubuntu.com trusty-backports/multiverse i386 Packages     
Hit http://pk.archive.ubuntu.com trusty-backports/main Translation-en          
Hit http://pk.archive.ubuntu.com trusty-backports/multiverse Translation-en    
Hit https://deb.nodesource.com trusty InRelease                                
Hit http://pk.archive.ubuntu.com trusty-backports/restricted Translation-en    
Ign http://nyc2.mirrors.digitalocean.com trusty/main Translation-en_US         
Hit http://pk.archive.ubuntu.com trusty-backports/universe Translation-en      
Hit http://pk.archive.ubuntu.com trusty Release                                
Ign http://nyc2.mirrors.digitalocean.com trusty/main Translation-en            
Hit https://deb.nodesource.com trusty/main amd64 Packages                      
Hit http://pk.archive.ubuntu.com trusty/main Sources                           
Hit http://pk.archive.ubuntu.com trusty/restricted Sources                     
Hit http://pk.archive.ubuntu.com trusty/universe Sources                       
Hit http://pk.archive.ubuntu.com trusty/multiverse Sources                     
Hit https://deb.nodesource.com trusty/main i386 Packages                       
Hit http://pk.archive.ubuntu.com trusty/main amd64 Packages                    
Ign http://extras.ubuntu.com trusty InRelease                                  
Hit http://pk.archive.ubuntu.com trusty/restricted amd64 Packages              
Ign http://dl.google.com stable/main Translation-en_US                         
Hit http://pk.archive.ubuntu.com trusty/universe amd64 Packages                
Hit http://extras.ubuntu.com trusty Release.gpg                                
Hit http://pk.archive.ubuntu.com trusty/multiverse amd64 Packages              
Get:1 https://deb.nodesource.com trusty/main Translation-en_US                 
Hit http://pk.archive.ubuntu.com trusty/main i386 Packages                     
Hit http://pk.archive.ubuntu.com trusty/restricted i386 Packages               
Hit http://extras.ubuntu.com trusty Release                                    
Ign http://dl.google.com stable/main Translation-en                            
Hit http://pk.archive.ubuntu.com trusty/universe i386 Packages                 
Hit http://pk.archive.ubuntu.com trusty/multiverse i386 Packages               
Hit http://extras.ubuntu.com trusty/main Sources                               
Hit http://pk.archive.ubuntu.com trusty/main Translation-en                    
Hit http://extras.ubuntu.com trusty/main amd64 Packages                        
Hit http://pk.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://extras.ubuntu.com trusty/main i386 Packages                         
Hit http://pk.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://pk.archive.ubuntu.com trusty/universe Translation-en                
Hit http://security.ubuntu.com trusty-security/main Sources                    
Ign http://pk.archive.ubuntu.com trusty/main Translation-en_US                 
Ign http://pk.archive.ubuntu.com trusty/multiverse Translation-en_US           
Ign http://pk.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://pk.archive.ubuntu.com trusty/universe Translation-en_US             
Ign http://extras.ubuntu.com trusty/main Translation-en_US                     
Ign http://extras.ubuntu.com trusty/main Translation-en                        
Ign https://deb.nodesource.com trusty/main Translation-en_US                   
Ign https://deb.nodesource.com trusty/main Translation-en                      
Hit http://security.ubuntu.com trusty-security/restricted Sources              
Hit http://security.ubuntu.com trusty-security/universe Sources                
Hit http://security.ubuntu.com trusty-security/multiverse Sources              
Err http://mirrors.neusoft.edu.cn trusty/main amd64 Packages                   
  404  Not Found [IP: 219.216.128.25 80]
Hit http://security.ubuntu.com trusty-security/main amd64 Packages             
Hit http://security.ubuntu.com trusty-security/restricted amd64 Packages       
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages         
Err http://mirrors.neusoft.edu.cn trusty/main i386 Packages                    
  404  Not Found [IP: 219.216.128.25 80]
Hit http://security.ubuntu.com trusty-security/multiverse amd64 Packages       
Hit http://security.ubuntu.com trusty-security/main i386 Packages              
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages        
Err http://mirrors.neusoft.edu.cn trusty/main ppc64el Packages                 
  404  Not Found [IP: 219.216.128.25 80]
Hit http://security.ubuntu.com trusty-security/universe i386 Packages          
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages        
Ign http://mirrors.neusoft.edu.cn trusty/main Translation-en_US                
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en       
Hit http://security.ubuntu.com trusty-security/restricted Translation-en       
Ign http://mirrors.neusoft.edu.cn trusty/main Translation-en                   
Hit http://security.ubuntu.com trusty-security/universe Translation-en         
W: Failed to fetch http://mirrors.neusoft.edu.cn/mariadb/repo/10.1/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 219.216.128.25 80]

W: Failed to fetch http://mirrors.neusoft.edu.cn/mariadb/repo/10.1/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 219.216.128.25 80]

W: Failed to fetch http://mirrors.neusoft.edu.cn/mariadb/repo/10.1/ubuntu/dists/trusty/main/binary-ppc64el/Packages  404  Not Found [IP: 219.216.128.25 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
Traceback (most recent call last):
  File "install.py", line 342, in <module>
    install_bench(args)
  File "install.py", line 21, in install_bench
    'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel'
  File "install.py", line 219, in run_os_command
    returncode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo apt-get update' returned non-zero exit status 100

**Comment by shreyasp** [comment]
@ehsanquranwala This seems to be a network issue, because of which your installation has failed. Try running again.
