### ISSUE TITLE
Link to "Change the Hostname" page not working

### ISSUE THREAD

**Issue by warwickchapman** [frappe/bench#333]
Link to https://frappe.github.io/frappe/user/en/bench/guides/how-to-change-host-name-from-localhost.html is broken.

**Comment by vjFaLk** [comment]
It's actually been deprecated. To use custom domains use `bench setup add-domain`

**Comment by peefour** [comment]
hi, the link is still there. 
this is misguiding.
why don't you replace the link with this new information?
thanks!
