### ISSUE TITLE
After running Easy Install script, Production procedure requires password

### ISSUE THREAD

**Issue by warwickchapman** [frappe/bench#334]
After running the Easy Install script, I could not access the development application because it complained that the hostname I was using to hit port 8000 was unknown.

I tried to deploy with the production procedure but that requires a password for the frappe user running the sudo command and the easy install process did not make that password known to the user.

**Comment by shreyasp** [comment]
@warwickchapman please try executing `passwd frappe` from root login to set a password for the frappe user.

**Comment by warwickchapman** [comment]
OK, that being done, it now complains about Frappe not being a member of sudoers.  Think you should add two lines to the script to set a frappe password and to add frappe to sudoers, or add notes about this for the productionize process.

**Comment by vjFaLk** [comment]
@warwickchapman So, the installer is meant to give the frappe user specific permissions to run only particular sudo commands. If you want to access the frappe user, as root you can just type `su frappe` and you will change to that user. 

To answer your second question you need to run `bench setup production frappe` to make it work.

Also, any reason you did not run the easy install with the `--production` tag?

**Comment by warwickchapman** [comment]
Because I was following the instructions on doing an install.

You have a two step process - and I'm trying to help point out where the
second step in the process isn't working so well.

Ps. If I run "bench setup production frappe" I get a python crash.

**Comment by vjFaLk** [comment]
The instructions mention that for a production setup you pass the production tag. To do a production install, you don't need to do two steps. You just need to run `python install.py --production --user frappe`

Could you share the traceback for the error? 

Anyway, if you don't want to be debugging your issue, i'd just suggest starting with a fresh system and running the installer with the `--production` tag

**Comment by warwickchapman** [comment]
frappe@khokha:~/frappe-bench$ sudo bench setup production frappe
Port configuration list:
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 40, in cli
    bench_command()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in
__call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in
main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060,
in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060,
in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in
invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in
invoke
    return callback(*args, **kwargs)
  File "/home/frappe/.bench/bench/commands/setup.py", line 56, in
setup_production
    setup_production(user=user)
  File "/home/frappe/.bench/bench/config/production_setup.py", line 17, in
setup_production
    bench_name=bench_name, extn=supervisor_conf_extn))
  File "/usr/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'

**Comment by saurabh6790** [comment]
@warwickchapman  Are you still facing this issue?

**Comment by joshreeder** [comment]
I am still getting this error trying to turn on production from the docker image

**Comment by codingCoffee** [comment]
@joshreeder please open an issue in https://github.com/frappe/frappe_docker
