### ISSUE TITLE
Unable to view erpnext site on centos 

### ISSUE THREAD

**Issue by osmanahmed2712** [frappe/bench#335]
Installed erpnext on centos version -7 .the installation was done on vmware the host and the guest vm is able to ping eachother . But when i tried to access the erpnext website it provided me with the nginx page .with website administrator .

![5cd590399af46d691087422895d3784f407aaae4](https://cloud.githubusercontent.com/assets/22319481/19636292/7c263194-99d9-11e6-8535-09cee4bfe852.png)

**Comment by vjFaLk** [comment]
Hm what did you use to install? Seems the config is off? This is the default nginx page.

**Comment by osmanahmed2712** [comment]
I referred the installation process for the following website:
http://comtronic.com.au/install-erpnext-centos7/

All the installation was smooth till the end.
-tried to access the erpnext locally  got nginx webpage.
tired to access erpnext from another machine but NO WEBPAGE IS LOADED .

**Comment by vjFaLk** [comment]
Oh man, that's an old article! The old installer has been replaced by a completely new one that installs _everything_ with one command on CentOS 7. Ref to : https://github.com/frappe/bench#easy-install

You wanna do this on a completely fresh server.

**Comment by osmanahmed2712** [comment]
Thank You for your help VJ FALK. I tired installation with the easy install as you referred everything went smoothly. During installation i selected the PRODUCTION as option .When i try to login though the webpage still i am facing the same issue.

**Comment by osmanahmed2712** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22319481/19723029/63554e5e-9b8a-11e6-852f-dfeee77a7b58.png)

**Comment by vjFaLk** [comment]
It seems that you might be accessing the wrong address. Maybe you're accidentally accessing your host machine? Change the network mode for the VM to Bridged, and try accessing it via a network IP? 

Just in case run `curl localhost` from the VM, you should be able to see code related to ERPNext Login instead of the nginx welcome page.

**Comment by osmanahmed2712** [comment]
when i used curl localhost - failed connection to localhost 80 connection refused .(output result)
-i made bridge connection and when i try to ping the ip of VM it is pinging and when i try to access the erpnext login it is not showing anything i tried locally and using network ip as well.

**Comment by osmanahmed2712** [comment]
After installation do i need to input any more command after installation for getting the erpnext login page

**Comment by vjFaLk** [comment]
No, it should just work. I feel there is an issue with your networking more than the installation. Have you port forwarded the required ports?

Also, did you run the `curl` commands from inside the VM? Cause it shouldn't reject it.

**Comment by osmanahmed2712** [comment]
i just installaed a fresh centos . 
-i have port forwarded ,i thought that the script will do by itself.But now i will portforward .
yes i did run curl command from inside the vm .but it got rejected
