### ISSUE TITLE
Support for Elementary OS in EasyInstaller

### ISSUE THREAD

**Issue by dottenbr** [frappe/bench#339]
You are strong proponents for ElementaryOS but the EasyInstaller script doesnt support ElementaryOS. Maybe you want to reconsider this?

> Sorry, the installer doesn't support "elementary" 0. Aborting installation!

**Comment by zhujieo** [comment]
I hope too.

**Comment by TurkerTunali** [comment]
I've comment out 8th line (#check_distribution_compatibility()) and tried the easy install. It says
"Frappe/ERPNext has been successfully installed!" and everything installed without an error. But I can't start bench. I can't find bench.

bench start gives "bench: command not found" error.

Any idea?
