### ISSUE TITLE
Installation Failure on Ubuntu Server 16.04 LTS 

### ISSUE THREAD

**Issue by EnSeal** [frappe/bench#342]
Hello Team 

I am absolutely new to this solution, and i am trying to install this on our E2 console. But i seem not make headway. I am following the easy install steps for Linux and i am stuck at this point 

![image](https://cloud.githubusercontent.com/assets/18033246/19967085/fe4b329e-a1ce-11e6-845c-b20439560ade.png)

Please assist on instructions to get past this......

Regards

**Comment by system19** [comment]
sudo apt-get install python-pip

Please ask any further tech questions like this on the forum at:
https://discuss.erpnext.com
Thanks

**Comment by vjFaLk** [comment]
@EnSeal Just do `sudo apt-get install python-minimal`

**Comment by EnSeal** [comment]
Thank you. This is sorted now
