### ISSUE TITLE
Installing over Cloudways on Digital Ocean

### ISSUE THREAD

**Issue by benjaroa** [frappe/bench#346]
Hi,

(i'm a newbie, and not a trained techie guy, just reading and learning)

I have a server managed by Cloudways on Digital Ocean. 

Running:
`python -V`
> Python 2.7.9

`curl -V`
> curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1t zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
> Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp > smtps telnet tftp
> Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP

`mysql -V`
> mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

`nginx -v`
> nginx version: nginx/1.10.1

`redis-server --version`
> Redis server v=3.2.5 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=474f5462991a0e92

`node --version`
> v6.9.1

Apparently i won't be ably to have sudo access (https://support.cloudways.com/why-cant-i-have-root-access-to-my-server/)

I followed the steps, but can't run install.py cause i don't have sudo privileges.
```
python install.py --user my_user --production --verbose
[sudo] password for my_user:
my_user is not in the sudoers file.  This incident will be reported.
Traceback (most recent call last):
  File "install.py", line 351, in <module>
    install_bench(args)
  File "install.py", line 21, in install_bench
    'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel'
  File "install.py", line 219, in run_os_command
    returncode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo apt-get update' returned non-zero exit status 1
``` 

Is there any way to run the install without being sudo?

**Comment by yashodhank** [comment]
@benjaroa kindly use Manual Installation instructions.
Use https://discuss.erpnext.com for such questions.

**Comment by vjFaLk** [comment]
@benjaroa Also, you want to probably just have your own VPS with root access, it's just better.

**Comment by benjaroa** [comment]
Hi,
@yashodhank as I said in my question, I already follow the manual installation. I'll post the same in https://discuss.erpnext.com/
@vjFaLk OK, I'll look for it, but my question is still not answered: are there any chance to install frappe/ERPNext without root access?

Thanks!

**Comment by yashodhank** [comment]
@benjaroa installer.py does require you **root** access as it install depending packages, creates users. Very reason auto installer provided to make life easier.
If you are not sure how to use Manual installation instructions better use server with root access.
