### ISSUE TITLE
Bench update failure

### ISSUE THREAD

**Issue by cgpurbaugh** [frappe/bench#348]
Every time we attempt to update, we get a warning that changes to redis.py will be overwritten.  Below is a link, you can see the difference between our version of Redis.py (right) and the redis.py on GitHub (left).  Any ideas why the file would be changed?  

https://www.diffchecker.com/PQfF0fPp

**Comment by vjFaLk** [comment]
I think this is a bug that's been showing up every now and then. Doing a `git reset --hard` in the frappe folder will resolve the issue

**Comment by cgpurbaugh** [comment]
You're right.
