### ISSUE TITLE
MacOS: install.py fails because of MySQLdb

### ISSUE THREAD

**Issue by anandpdoshi** [frappe/bench#349]
[Update] I posted this too soon. Just `xcode-select --install` didn't fix it. 
[Update 2] I had to globally upgrade pip using `pip install --upgrade pip` and then it started working.

```
...
    In file included from _mysql.c:44:
    /usr/local/Cellar/mariadb/10.0.21/include/mysql/my_config.h:344:11: warning: 'SIZEOF_SIZE_T' macro redefined [-Wmacro-redefined]
      #define SIZEOF_SIZE_T  SIZEOF_LONG
              ^
    /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/include/python2.7/pymacconfig.h:43:17: note: previous definition is here
    #        define SIZEOF_SIZE_T           8
                    ^
    _mysql.c:1589:10: warning: comparison of unsigned expression < 0 is always false [-Wtautological-compare]
            if (how < 0 || how >= sizeof(row_converters)) {
                ~~~ ^ ~
    2 warnings generated.
    clang -bundle -undefined dynamic_lookup -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk build/temp.macosx-10.12-x86_64-2.7/_mysql.o -L/usr/local/Cellar/mariadb/10.0.21/lib -lmysqlclient_r -lz -lssl -lcrypto -o build/lib.macosx-10.12-x86_64-2.7/_mysql.so
    ld: library not found for -lssl
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'clang' failed with exit status 1
```

To solve this, install XCode developer tools using:
`xcode-select --install`

This could either be fixed in Readme or can be part of the install.py process. 

> Tested on: December 19, 2016 (Latest commit 2b67155  on Nov 14)

**Comment by manassolanki** [comment]
[Update] 
- Installation of MySql-python via pip fails in the virtualenv only, it is working fine globally. 
- OpenSSL is prerequisites for MySql-python and Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries. I have tried setting an environment variable in virtualenv so that Xcode can build but that build still failing.
