### ISSUE TITLE
Currency amount "In Words"

### ISSUE THREAD

**Issue by franciscobuendiao** [frappe/bench#354]
Hi.
In Mexico there’s a specific string to describe a currency amount when doing invoices. For example:

$86,304.57 - EIGHTY SIX THOUSAND, THREE HUNDRED FOUR **_DOLLARS, 57/100 U.S.D._**
Or...
$86,304.57- OCHENTA Y SEIS MIL, TRESCIENTOS CUATRO **_PESOS, 57/100 M.N._**

This is what ERPNext does:
![captura](https://cloud.githubusercontent.com/assets/25084259/21899422/c208f316-d8b5-11e6-92a7-1a11d0f556d1.PNG)
**_MXN_** Ochenta Y Seis Mil Trescientos Cuatro **_netos_**
_(By the way, if the amount have cents, if it isn't rounded, doesn’t work, doesn't show cents)._

The string should be: 

- MILLION, THOUSAND, HUNDRED DOLLARS, ##/100 U.S.D.
- MILLONES, MILES, CIENTOS PESOS, ##/100 M.N.

Is it possible to adjust “In Words” as per Mexico requirements? I'm implementing on ERPNext cloud hosting, to three different companies and all requested the same.

Regards.

**Comment by saurabh6790** [comment]
If you are still facing this issue, please report at https://github.com/frappe/erpnext/issues
