### ISSUE TITLE
Nginx proxy missing server_port in Production VBox Image

### ISSUE THREAD

**Issue by yashodhank** [frappe/bench#360]
The correct forwarding should be:

```
proxy_set_header Host $host:$server_port;
```
Or any redirection will be incorrect. e.g. OAuth redirection.
was opened by @srdgame at https://github.com/frappe/erpnext/issues/7714

**Comment by saurabh6790** [comment]
Fixed! feel free to reopen if the issue persists

**Comment by daraul** [comment]
Any reason you didn't change the line in the nginx template[1]?

[1] https://github.com/frappe/bench/blob/d1ebb4c3b2821379382106905d4560200f3480b9/bench/config/templates/nginx.conf#L91
