### ISSUE TITLE
Translations missing

### ISSUE THREAD

**Issue by ChristopherMeyering** [frappe/bench#368]
Hi,
we now have erpnext up & and running.
But we noticed that the german translation differs from the online demo.

For example:
When searching for "Artikel" i only get results in english, not in german.

bench download-translations and bench update (bench restart) didn't work as a fix.

greetings,
Chris

**Comment by saurabh6790** [comment]
If still facing the issue, please report this issue at https://github.com/frappe/erpnext/issues
