### ISSUE TITLE
Path are confused ? 

### ISSUE THREAD

**Issue by kickapoo** [frappe/bench#370]
I have 2 installations of bench
1. in /Dev
2. in /erpnext_conf

I try to update a frappe repo in `/Dev/frappe-bench/`  but the error I get in bench is associate with the installation of bench-repo in `/erpnext_conf`

```
subprocess.CalledProcessError: Command 'basename $(git symbolic-ref -q HEAD)' returned non-zero exit status 1
```

 File "**/Users/kickapoo/erpnext_conf/frappe_batman/bench-repo/bench/utils.py**", line 326, in get_cmd_output
    return subprocess.check_output(cmd, cwd=cwd, shell=True, stderr=open(os.devnull, 'wb')).strip()

**Comment by saurabh6790** [comment]
Please share output for `basename $(git symbolic-ref -q HEAD)`

**Comment by daraul** [comment]
I had this problem when I initialized my bench with `bench init --frappe-branch <whatever>`. Unless I define an actual branch there `git symbolic-ref -q HEAD` returns nothing, causing `basename` to throw an error.
