### ISSUE TITLE
git status message changed as of version 2.9.1

### ISSUE THREAD

**Issue by Barakat** [frappe/bench#372]
I was having this bug that shows me this [error message](https://github.com/frappe/bench/blob/master/bench/app.py#L141). 

[As of](https://github.com/git/git/blob/e0c1ceafc5bece92d35773a75fff59497e1d9bd5/Documentation/RelNotes/2.9.1.txt#L53) git 2.9.1 the message displayed by `git status` has been changed from `nothing to commit, working directory clean` to `nothing to commit, working tree clean`.

**Comment by ckosiegbu** [comment]
Hi. I noticed​ this too. Made a pull request:
https://github.com/frappe/bench/pull/373

Hoping for a quick fix as bench update won't work till it's fixed.
