### ISSUE TITLE
No switch-to-v7 command

### ISSUE THREAD

**Issue by vjFaLk** [frappe/bench#375]
Two problems. 

1. bench tells me to run bench switch-to-v7 if I want to lock to v7  when running `bench update` but there is no such command
I could've written that feature myself, but : 
2. There isn't a branch locked at 7.2.x for ERPNext / Frappe

**Comment by vjFaLk** [comment]
@rmehta @saurabh6790 Can we get a 7.2.x branch? I can then make the command myself.

**Comment by nabinhait** [comment]
@vjFaLk I will push a branch for v7.x.x

But we have removed those 'switch-to-' commands. Because lot of users confused by those commands and they use those commands to downgrade the system. But unfortunately downgrading is not possible in frappe/erpnext due to database schema changes.

**Comment by vjFaLk** [comment]
@nabinhait Thanks! I'll just switch to it manually then.

**Comment by nabinhait** [comment]
Pushed v7.x.x branch to frappe and erpnext repo.
