### ISSUE TITLE
Easy install fails on Ubuntu 16.04.2 LTS x64 server

### ISSUE THREAD

**Issue by dpetropoulos-lemco** [frappe/bench#377]
Installed Ubuntu on a fresh virtual machine.
Added user "frappe"
As root I executed the following:
  `sudo apt-get update`
  `sudo apt-get upgrade`
  `sudo apt-get install python-minimal`
  `wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py`
  `python install.py --production --user frappe`

The result:

```
E: Some index files failed to download. They have been ignored, or old ones used instead.
Traceback (most recent call last):
  File "install.py", line 351, in <module>
    install_bench(args)
  File "install.py", line 21, in install_bench
    'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel'
  File "install.py", line 219, in run_os_command
    returncode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo apt-get update' returned non-zero exit status 100

```
What's causing this kind of trouble on a freshly installed latest-stable-version Ubuntu?

**Comment by dpetropoulos-lemco** [comment]
Tried the EXACT same thing on a fresh installation of Ubuntu 14.04.5 x32 server.
The outcome was the EXACT same error.

**Comment by sagarvora** [comment]
The README expressly states that the command `python install.py --production --user frappe` is to be run if you're logged in as root.

Alternatively, pass the command with sudo like this:
`sudo python install.py --production`

**Comment by dpetropoulos-lemco** [comment]
In my initial message I mention "_...As root I executed the following:..._" and `python install.py --production --user frappe` which you suggested.

Using "sudo" even as root doesn't mean I'm not logged in as root.

I tried everything from scratch on four fresh VMs, one Ubuntu 16 as root, one Ubuntu 16 as user "frappe", one Ubuntu 14 as root, one Ubuntu 14 as user "frappe". As user "root" I used `python install.py --production --user frappe` and as user "frappe" I used `sudo python install.py --production`. All four returned the same results mentioned in the first comment. Something is clearly broken in the script.

**Comment by dpetropoulos-lemco** [comment]
I finally managed to install EPRnext with the following steps:

On a VM I installed Ubuntu 16.0.4.2 LTS x64 **without allowing it to install live updates**. 
Added one user named "frappe"
Logged in as "frappe"
Deliberately **did not** execute `sudo apt-get update` or `sudo apt-get upgrade`
Didn't leave the Ubuntu installation CD mounted
Installed Python with `sudo apt-get install python-minimal`
Downloaded easy install script `wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py`
Successfully ran `sudo python install.py --production`

Finally, after so many tries, I had a working system. The easy installation script seems to be very sensitive to any OS updates.
