### ISSUE TITLE
Proposal: bench exclude-from-update [app-name]

### ISSUE THREAD

**Issue by sagarvora** [frappe/bench#379]
If a developer has a custom app which he doesn't want to pull when `bench update` is executed, he can pass a command like this:
`bench exclude-from-update [app-name]`

The app name will be saved in `update_exclusions.txt` in the `sites` folder alongside other text files.

These apps will not be checked for local changes and will not be pulled from their repository when `pull_all_apps()` is executed.

Any suggestions are welcome. I will work on the pull request after approval.

This command will be helpful primarily in the development environment where there is a possibility of unstaged changes in custom apps.

**Comment by mhbu50** [comment]
+1

**Comment by vjFaLk** [comment]
I like this command! Do link the PR here, I can review it as well.

**Comment by DRogue1337** [comment]
@sagarvora What's the status?

**Comment by sagarvora** [comment]
@DRogue1337 Not developed yet. Do you want to take the lead on this one?

**Comment by codingCoffee** [comment]
added in #517
