### ISSUE TITLE
I cannot get my site in web browser.

### ISSUE THREAD

**Issue by ameerbab** [frappe/bench#383]
**I cannot get my site in web browser through IP or domain name.**
I installed the app "ni_dark_theme" and after 2 - 3 days tried to uninstalled the same. But the app is still there disabled. but I am not able to use my site through web browser or mobile app.

for **sudo bench update** command the result was:
File "/home/frappe/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'd94d2e5efbff78f3'@'localhost' (using password: YES)")

Request the help from experts.

**Comment by tundebabzy** [comment]
@ameerbab 
Please post this question on https://discuss.erpnext.com if its still persisting issue
