### ISSUE TITLE
Issue with Easy Installer in Ubuntu 16.04.2 x64

### ISSUE THREAD

**Issue by selvaganeshilango** [frappe/bench#397]
Hi,

I am installing ERPNext in a fresh system created with Digital Ocean 512 MB Memory / 20 GB Disk / NYC3,

1. I created a new user 'frappe'
2. Added "Sudo" Permissions to the user 'frappe'
3. Logged in as user 'frappe'
4. Installed python with `sudo apt-get install python-minimal`
5. Downloaded easy installer `wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py`
6. Executed the installer `sudo python install.py --production`

I endded up in the following error,

![image](https://cloud.githubusercontent.com/assets/25768338/26063511/388196fe-395c-11e7-9a8e-afdb84641bbf.png)

**Comment by sagarvora** [comment]
Hi, the installation cannot continue due to the errors in your APT sources. Once you fix them, it should work fine.

**Comment by selvaganeshilango** [comment]
Hi Sagarvora,
Thanks for the reply,
Can you please explain how to fix my APT sources?

Thanks

**Comment by sagarvora** [comment]
https://askubuntu.com/questions/307/how-can-ppas-be-removed
One more thing, 512 MB RAM is insufficient. Best to use 1GB instead.

**Comment by selvaganeshilango** [comment]
Thanks.
I solved the issue after changing the file as ROOT user, based on the link

Steps:
1. Open a new Terminal window and run the following command

**sudo vi /etc/apt/sources.list.d/google-chrome.list**
or
**sudo vi /etc/apt/sources.list.d/google.list**

2. In the text file that opens edit the file so that the line reads:

**deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main**
The only addition you need to make is entering the **[amd64]** architecture after ‘deb’ but preceding the ‘http’. Do not edit or replace any other text in this file.

3. Hit Save. Close

Now return to the Terminal and refresh your package list by running:

sudo apt-get update
The ‘failed to fetch’ APT error should no longer appear.


Thanks
Selva
