### ISSUE TITLE
unable to  view webpage after installation of frappe and erpNext on AWS ubuntu 14.04 server

### ISSUE THREAD

**Issue by vinodgangal** [frappe/bench#418]
I was able to successfully install frappe and erpNext and have started the bench too.

Here are the details of the inbound security group settings in AWS.
Ports	Protocol	Source	frappe-erpnext
80	tcp	0.0.0.0/0, ::/0	✔
8080	tcp	0.0.0.0/0, ::/0	✔
22	tcp	0.0.0.0/0, ::/0	✔

I am trying to access the website on http://ec2-52-15-166-255.us-east-2.compute.amazonaws.com:8080 but i getting unable to connect error.
Complete error :
"Unable to connect

Firefox can't establish a connection to the server at ec2-52-15-166-255.us-east-2.compute.amazonaws.com.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer's network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web."

**Comment by saurabh6790** [comment]
You are accessing in wrong way. You should use IP:PORT if in develop mode or only IP address in enough to access the site
