### ISSUE TITLE
Install script leaves apps in non-updateable status

### ISSUE THREAD

**Issue by mist-01** [frappe/bench#419]
Using the install script to install ERPNext on a fresh install of Ubuntu 16.04.2 64-bit leaves the apps (frappe, erpnext) in a non-updatable status.  (I am running "python install.py --production --user=erp --site=myfqdn" as root)  The install script finishes without error.  However, running "bench update" will fail and complain about needing to stash changes.  If you run a "git status" or "git diff" in one of the app folders, you can see that the problem is a difference in file modes:

> diff --git a/frappe/core/doctype/custom_role/custom_role.py b/frappe/core/doctype/custom_role
> /custom_role.py
> old mode 100644
> new mode 100755
> diff --git a/frappe/core/doctype/custom_role/test_custom_role.py b/frappe/core/doctype/custom_role/test_custom_role.py
> old mode 100644
> new mode 100755
> diff --git a/frappe/core/doctype/defaultvalue/README.md b/frappe/core/doctype/defaultvalue/README.md
> old mode 100644
> new mode 100755
> diff --git a/frappe/core/doctype/defaultvalue/__init__.py b/frappe/core/doctype/defaultvalue/__init__.py
> old mode 100644
> new mode 100755
> diff --git a/frappe/core/doctype/defaultvalue/defaultvalue.json b/frappe/core/doctype/defaultvalue/defaultvalue.json
> old mode 100644
> new mode 100755

The file list is huge, the above is just a sample.

This can easily be worked around by running "git config core.filemode false".  However, it's quite discouraging to be unable to run an update command on a fresh install.  If this isn't a bug, it would at least be nice to print a message explaining to the user how to solve the problem.

**Comment by ashish-greycube** [comment]
It appears other solution is
find . -type d -exec chmod a+rwx {} \; # Make folders traversable and read/write
find . -type f -exec chmod a+rw {} \;  # Make files read/write
If you do that, you'll never need to use core.fileMode, except in very rare environment
[stackoverflow](https://stackoverflow.com/questions/1580596/how-do-i-make-git-ignore-file-mode-chmod-changes)

**Comment by saurabh6790** [comment]
Fixed!
