### ISSUE TITLE
TASK [download wkthmltox linux] fails 

### ISSUE THREAD

**Issue by Biggo6** [frappe/bench#427]
Hello

Please help i got this error 
![8](https://user-images.githubusercontent.com/4988463/26842447-8c4081f6-4af5-11e7-9f6d-e2e594d40c27.PNG)

**Comment by DRogue1337** [comment]
Have you tried running the install script again?
It's working on my end. The download could have failed for various reasons.

**Comment by mbauskar** [comment]
@Biggo6, @DRogue1337.

wkhtmltopdf site was down yesterday which was causing the issue while installing the wkhtmltopdf. Issue was also raised for the same on wkhtmltopdf repo https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3508
