### ISSUE TITLE
Log depth when installing app 

### ISSUE THREAD

**Issue by nathando** [frappe/bench#429]
Hi guys, 

Just wanna check if there is a reason we do shallow clone instead of full clone for development. Was the size that big ? Because I was trying to check out a specific commit and it's not available, then I've realized it's because of the shallow clone. 

I found the code setting it [here](https://github.com/frappe/bench/blob/bee3de44e4cf3913f353a4a517c4e68a726f45ff/playbooks/install.py) 
```
     success = run_os_command(
		{'git': 'git clone {repo_url} {bench_repo} --depth 1 --branch {branch}'.format(
			repo_url=repo_url, bench_repo=clone_path, branch=branch)}
    )

```

**Comment by saurabh6790** [comment]
It will take too long to fetch all commit history thus shallow cloning is used. You can unshallow it after installation.

https://www.perforce.com/blog/git-beyond-basics-using-shallow-clones
