### ISSUE TITLE
Proposal for "versions freezing" enhancement

### ISSUE THREAD

**Issue by brownharryb** [frappe/bench#439]
Hi guys,
We have a custom app that is currently compatible with specific versions of frappe and ERPNext, but when setting up bench together with our app, we are not able to specify these versions upon install.
We believe this is a required feature for bench and we propose extending the installation procedure to give devs and users the ability to "freeze" or set their preferred versions of frappe and ERPNext when setting up a new bench and also when updating the system. 
We propose giving users the ability to set these versions using the "--versions" option

`python install.py --versions “frappe:8.0.4 erpnext:8.0.5”`
for installation, and
`bench update --versions “frappe:8.0.4 erpnext:8.0.5"`
for updates

When the "--versions" option is set, the system pulls the specified versions for both frappe and ERPNext to the bench using the available git tags for the repos, this way, custom apps based on these versions will still function as intended without the fear of codes breaking due to major or minor version changes in frappe or ERPNext 
Comments and suggestions are welcome
Regards

**Comment by achillesrasquinha** [comment]
Okay this seems to be an excellent idea to have versions locked. bench itself is a package manager for frappe apps and I guess you could maybe have an `apps.lock.txt` file that like you mentioned freeze. Send in a PR! 😄

**Comment by salmanulfarzy** [comment]
Install `bench` from master, You could specify branch of `frappe` and `erpnext` on install (#638)

```shell
git clone https://github.com/frappe/bench
pip install -e ./bench
bench init --frappe-branch v10.x.x <directory>
cd <directory>
bench get-app erpnext --branch v10.x.x
```
