### ISSUE TITLE
Frappe support Debian 9 and PHP7 ?

### ISSUE THREAD

**Issue by blackyzero** [frappe/bench#441]
Hi everyone,

I'd like to know whether Frappe support OS Debian 9 and PHP7 ?

**Comment by ishanloya** [comment]
Maybe I'm wrong but I believe PHP version shouldn't matter since Frappe doesn't use PHP. You could try spinning up a test server on DigitalOcean and test it with Debian 9. Ubuntu is fully supported but not sure about Debian.

**Comment by blackyzero** [comment]
i got error with fresh install on Debian 9, mysql error

**Comment by so-rose** [comment]
I get this error message:

```
Sorry, the installer doesn't support debian 9. Aborting installation!
Install on debian 8 instead
```

I'd love to be able to run on the much newer stretch - any chance of this?

**Comment by achillesrasquinha** [comment]
Could you try the manual install otherwise?

**Comment by saurabh6790** [comment]
I think this has been fixed!
