### ISSUE TITLE
Not able to restore db, Bench Version -- 4.1.0  

### ISSUE THREAD

**Issue by morethegr8** [frappe/bench#442]
proteus@proteus-server:/home/frappe/frappe-bench$ bench --version
4.1.0
proteus@proteus-server:/home/frappe/frappe-bench$ sudo bench frappe --restore /home/frappe/frappe-bench/sites/site1.local/public/files/20170630_95060254_database.sql
frappe app is not installed. Run the following command to install frappe
bench get-app https://github.com/frappe/frappe.git
Traceback (most recent call last):
  File "/usr/local/bin/bench", line 11, in <module>
    load_entry_point('bench', 'console_scripts', 'bench')()
  File "/home/frappe/.bench/bench/cli.py", line 20, in cli
    return old_frappe_cli()
  File "/home/frappe/.bench/bench/cli.py", line 78, in old_frappe_cli
    os.execv(f, [f] + sys.argv[2:])
OSError: [Errno 2] No such file or directory

**Comment by saurabh6790** [comment]
1. Don't use sudo
2.  switch to frappe user and run 
``` bench --site site-name --force restore path/to/backup/file.sql.gz```
