### ISSUE TITLE
the 404 page shows html code not the result

### ISSUE THREAD

**Issue by jefathey** [frappe/bench#476]
hi every one
i've a pure ubuntu 16.06 server it's clean and new
this is my all commands history

`apt-get install python-minimal
apt-get install build-essential python-setuptools
wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
sudo python install.py --production
pwd
sudo bench start
sudo bench new-site example
sudo bench --site example install-app erpnext
sudo bench use example
sudo bench start`

and evey thing working very well but
if i type any thing after my ip/ slash 
for examble 
127.0.0.1/any thing here.txt
i got this code
`<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Not Found</title>
	<meta name="generator" content="frappe">

    
	<link rel="shortcut icon"
		href="/assets/erpnext/images/favicon.png"
		type="image/x-icon">
	<link rel="icon"
		href="/assets/erpnext/images/favicon.png"
		type="image/x-icon">
    

		
		<link type="text/css" rel="stylesheet" href="/assets/frappe/css/bootstrap.css">
		<link type="text/css" rel="stylesheet" href="/assets/css/frappe-web.css">
		<link type="text/css" rel="stylesheet" href="/assets/erpnext/css/website.css">
		<link type="text/css" rel="stylesheet" href="/website_theme.css"><script>
		window.frappe = {};
		frappe.ready_events = [];
		frappe.ready = function(fn) {
			frappe.ready_events.push(fn);
		}
		window.dev_server = 0;
    </script>
</head>
<body data-path="frankestein">
	<div class="main-section">
		<div>
			<header>
					<nav class="navbar navbar-default navbar-main" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand ellipsis"
					 href="/">
					<span><img src='/files/logo.png' style='max-width: 40px; max-height: 25px;'> Mobykan Leader</span>
				</a>
				<div class="dropdown">
					<button class="btn btn-default navbar-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
						<i class="octicon octicon-three-bars"></i>
					</button>
					<ul class="dropdown-menu dropdown-menu-right">

<li class="divider"></li>

<li data-label="My Account" 
 class=" logged-in" ><a href="/me" 
	rel="nofollow">
	My Account
	</a></li><li data-label="Logout" 
 class=" logged-in" ><a href="/?cmd=web_logout" 
	rel="nofollow">
	Logout
	</a></li>
<li class="btn-login-area"><a href="/login">Login</a></li>

</ul>
				</div>
			</div>
			<div class="hidden-xs">
				
				
<ul class="nav navbar-nav navbar-right">
	
		
	<li class="shopping-cart hidden">
		<div class="cart-icon">
			<a class="dropdown-toggle" href="#" data-toggle="dropdown" id="navLogin">
				Cart <span class="badge-wrapper" id="cart-count"></span>
			</a>
			<div id="cart-overlay" class="dropdown-menu shopping-cart-menu"></div>
		</div>
	 </li>

	
	
	

<li class="dropdown logged-in" id="website-post-login"
	data-label="website-post-login" style="display: none">
	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
		<span class="user-image-wrapper"></span>
		<span class="full-name"></span>
		<b class="caret"></b>
	</a>
    <ul class="dropdown-menu" role="menu"><li data-label="My Account" 
			><a href="/me" 
					rel="nofollow">
					My Account
				</a></li><li data-label="Logout" 
			><a href="/?cmd=web_logout" 
					rel="nofollow">
					Logout
				</a></li></ul>
</li>

<li class="btn-login-area"><a href="/login">Login</a></li>

</ul>
				
			</div>
		</div>
	</nav></header>

            <div class="hero-and-content">
                <div data-html-block="hero"></div>
                <div class="container">
                
<div class="page-container" id="page-404"
	data-path="frankestein">
		
		<div class="page-content without-sidebar">
			<div class="page-content-wrapper">
				<div class="row page-head">
					<div class='col-sm-12'>
						
					</div>
					<div class="col-sm-8 col-xs-6">
						
					</div>
					<div class="col-sm-4 col-xs-6">
						

						
					</div>
				</div>
				<div class="page_content">
<div class='page-card'>
	<div class='page-card-head'>
		<span class='indicator darkgrey'>Page Missing or Moved</span>
	</div>
	<p>The page you are looking for is missing. This could be because it is moved or there is a typo in the link.</p>
	<div><a href='/' class='btn btn-primary btn-sm'>Home</a></div>
</div>
<p class='text-muted text-center small' style='margin-top: -20px;'>Error Code: 404</p>
<style>
.hero-and-content {
	background-color: #f5f7fa;
}
</style>
</div>
			</div>
			
		</div>
</div>

                </div>
            </div></div>
		<div><footer class="web-footer">
	<section class="footer-links">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 text-left">
					
				</div>

				<div class="col-sm-6 text-right">
					
						
<div class='input-group input-group-sm pull-right footer-subscribe'>
	<input class="form-control" type="text" id="footer-subscribe-email"
		placeholder="Your email address...">
	<span class='input-group-btn'>
		<button class="btn btn-default" type="button"
			id="footer-subscribe-button">Get Updates</button>
	</span>
</div>

<script>
frappe.ready(function() {
	$("#footer-subscribe-button").click(function() {

		if($("#footer-subscribe-email").val() && valid_email($("#footer-subscribe-email").val())) {
			$("#footer-subscribe-email").attr('disabled', true);
			$("#footer-subscribe-button").html("Sending...")
				.attr("disabled", true);
			erpnext.subscribe_to_newsletter({
				email: $("#footer-subscribe-email").val(),
				callback: function(r) {
					if(!r.exc) {
						$("#footer-subscribe-button").html(__("Added"))
							.attr("disabled", true);
					} else {
						$("#footer-subscribe-button").html(__("Error: Not a valid id?"))
							.addClass("btn-danger").attr("disabled", false);
						$("#footer-subscribe-email").val("").attr('disabled', false);
					}
				}
			});
		}
		else
			frappe.msgprint(frappe._("Please enter valid email address"))
	});
});
</script>

					
				</div>
			</div>
			<div class="row footer-bottom-line">
				<div class="text-muted small col-sm-6 col-xs-12">
					
					
				</div>
				
				<div class="text-muted small col-sm-6 col-xs-12
					text-right footer-powered">
					
						<a href="https://erpnext.com?source=website_footer" target="_blank" class="text-muted">
		Powered by ERPNext</a>
					
				</div>
			</div>
		</div>
	</section>
</footer></div>
	</div>
	
	
	<script type="text/javascript"
		src="/assets/frappe/js/lib/jquery/jquery.min.js"></script>
	<script type="text/javascript"
		src="/assets/js/frappe-web.min.js"></script>
	
	<script type="text/javascript" src="/website_script.js"></script>
	<script type="text/javascript" src="/assets/js/erpnext-web.min.js"></script>

	<script>frappe.csrf_token = "None";</script></body>
</html>`
i don't know if this thing good or bad just for notice 👍

**Comment by saurabh6790** [comment]
Thanks for reporting this issue! Will verify this and wii fix it.

**Comment by achillesrasquinha** [comment]
Erm. Are you searching for a page that does not exists? 
You just mentioned you typed your IP/anythinghere.txt

If it doesn't exists, it shows you the page which is is clearly what it does.

Or am I wrong?

Anyway, this is more of `frappe` issue than a `bench` issue. Could you move it there if I'm wrong? Else go ahead and close this.
