### ISSUE TITLE
Can not log in to local host in centos 7

### ISSUE THREAD

**Issue by fnrfarid** [frappe/bench#477]
Hi, I have been trying to install ERPnext on my CentOS7. I can successfully install bench and add ERPnext, but I can't log in to localhost; 

I followed both manual and easy installation method. But, same result. I'm not a programmer nor I understand linux very well. 

Can anyone please help me out with a easy tutorial for centos7 ?

**Comment by fnrfarid** [comment]
Here's the codes error while trying to add a site. 

Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/farid/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 94, in <module>
    main()
  File "/home/farid/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/farid/frappe-bench/apps/frappe/frappe/commands/site.py", line 29, in new_site
    verbose=verbose, install_apps=install_app, source_sql=source_sql, force=force)
  File "/home/farid/frappe-bench/apps/frappe/frappe/commands/site.py", line 60, in _new_site
    admin_password=admin_password, verbose=verbose, source_sql=source_sql,force=force, reinstall=reinstall)
  File "/home/farid/frappe-bench/apps/frappe/frappe/installer.py", line 36, in install_db
    create_database_and_user(force, verbose)
  File "/home/farid/frappe-bench/apps/frappe/frappe/installer.py", line 60, in create_database_and_user
    if force or (db_name not in dbman.get_database_list()):
  File "/home/farid/frappe-bench/apps/frappe/frappe/model/db_schema.py", line 544, in get_database_list
    return [d[0] for d in self.db.sql("SHOW DATABASES")]
  File "/home/farid/frappe-bench/apps/frappe/frappe/database.py", line 123, in sql
    self.connect()
  File "/home/farid/frappe-bench/apps/frappe/frappe/database.py", line 69, in connect
    use_unicode=True, charset='utf8mb4')
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
_mysql_exceptions.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

**Comment by fnrfarid** [comment]
While starting bench

18:19:52 web.1            | localhost does not exist
18:19:52 web.1            | ----------------------------------------
18:19:52 web.1            | Exception happened during processing of request from ('127.0.0.1', 52710)
18:19:52 web.1            | Traceback (most recent call last):
18:19:52 web.1            |   File "/usr/lib64/python2.7/SocketServer.py", line 593, in process_request_thread
18:19:52 web.1            |     self.finish_request(request, client_address)
18:19:52 web.1            |   File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
18:19:52 web.1            |     self.RequestHandlerClass(request, client_address, self)
18:19:52 web.1            |   File "/usr/lib64/python2.7/SocketServer.py", line 649, in __init__
18:19:52 web.1            |     self.handle()
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 232, in handle
18:19:52 web.1            |     rv = BaseHTTPRequestHandler.handle(self)
18:19:52 web.1            |   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
18:19:52 web.1            |     self.handle_one_request()
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 267, in handle_one_request
18:19:52 web.1            |     return self.run_wsgi()
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
18:19:52 web.1            |     execute(self.server.app)
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/serving.py", line 199, in execute
18:19:52 web.1            |     for data in application_iter:
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/debug/__init__.py", line 284, in debug_application
18:19:52 web.1            |     app_iter = self.app(environ, start_response)
18:19:52 web.1            |   File "/home/farid/frappe-bench/apps/frappe/frappe/middlewares.py", line 15, in __call__
18:19:52 web.1            |     return super(StaticDataMiddleware, self).__call__(environ, start_response)
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 600, in __call__
18:19:52 web.1            |     return self.app(environ, start_response)
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/wsgi.py", line 600, in __call__
18:19:52 web.1            |     return self.app(environ, start_response)
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/local.py", line 228, in application
18:19:52 web.1            |     return ClosingIterator(app(environ, start_response), self.cleanup)
18:19:52 web.1            |   File "/home/farid/frappe-bench/env/lib/python2.7/site-packages/werkzeug/wrappers.py", line 301, in application
18:19:52 web.1            |     return f(*args[:-2] + (request,))(*args[-2:])
18:19:52 web.1            |   File "/home/farid/frappe-bench/apps/frappe/frappe/app.py", line 54, in application
18:19:52 web.1            |     init_request(request)
18:19:52 web.1            |   File "/home/farid/frappe-bench/apps/frappe/frappe/app.py", line 105, in init_request
18:19:52 web.1            |     frappe.init(site=site, sites_path=_sites_path)
18:19:52 web.1            |   File "/home/farid/frappe-bench/apps/frappe/frappe/__init__.py", line 135, in init
18:19:52 web.1            |     local.conf = _dict(get_site_config())
18:19:52 web.1            |   File "/home/farid/frappe-bench/apps/frappe/frappe/__init__.py", line 192, in get_site_config
18:19:52 web.1            |     sys.exit(1)
18:19:52 web.1            | SystemExit: 1
18:19:52 web.1            | ----------------------------------------

**Comment by fnrfarid** [comment]
[farid@localhost frappe-bench]$ bench start
18:23:08 system           | worker_long.1 started (pid=17728)
18:23:08 system           | redis_socketio.1 started (pid=17726)
18:23:08 system           | watch.1 started (pid=17730)
18:23:08 system           | redis_queue.1 started (pid=17739)
18:23:08 system           | redis_cache.1 started (pid=17741)
18:23:09 system           | web.1 started (pid=17734)
18:23:09 system           | socketio.1 started (pid=17742)
18:23:09 system           | worker_short.1 started (pid=17746)
18:23:09 system           | worker_default.1 started (pid=17747)
18:23:09 system           | schedule.1 started (pid=17744)
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.054 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.054 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.055 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
18:23:09 redis_socketio.1 |                 _._                                                  
18:23:09 redis_socketio.1 |            _.-``__ ''-._                                             
18:23:09 redis_socketio.1 |       _.-``    `.  `_.  ''-._           Redis 3.2.3 (00000000/0) 64 bit
18:23:09 redis_socketio.1 |   .-`` .-```.  ```\/    _.,_ ''-._                                   
18:23:09 redis_socketio.1 |  (    '      ,       .-`  | `,    )     Running in standalone mode
18:23:09 redis_socketio.1 |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 12000
18:23:09 redis_socketio.1 |  |    `-._   `._    /     _.-'    |     PID: 17726
18:23:09 redis_socketio.1 |   `-._    `-._  `-./  _.-'    _.-'                                   
18:23:09 redis_socketio.1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:23:09 redis_socketio.1 |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
18:23:09 redis_socketio.1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:23:09 redis_socketio.1 |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:23:09 redis_socketio.1 |  |    `-._`-._        _.-'_.-'    |                                  
18:23:09 redis_socketio.1 |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:23:09 redis_socketio.1 |       `-._    `-.__.-'    _.-'                                       
18:23:09 redis_socketio.1 |           `-._        _.-'                                           
18:23:09 redis_socketio.1 |               `-.__.-'                                               
18:23:09 redis_socketio.1 | 
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.057 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.057 # Server started, Redis version 3.2.3
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.057 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.057 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18:23:09 redis_socketio.1 | 17726:M 29 Aug 18:23:09.057 * The server is now ready to accept connections on port 12000
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.070 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.076 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.077 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.077 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.077 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
18:23:09 redis_cache.1    |                 _._                                                  
18:23:09 redis_cache.1    |            _.-``__ ''-._                                             
18:23:09 redis_cache.1    |       _.-``    `.  `_.  ''-._           Redis 3.2.3 (00000000/0) 64 bit
18:23:09 redis_cache.1    |   .-`` .-```.  ```\/    _.,_ ''-._                                   
18:23:09 redis_cache.1    |  (    '      ,       .-`  | `,    )     Running in standalone mode
18:23:09 redis_cache.1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 13000
18:23:09 redis_cache.1    |  |    `-._   `._    /     _.-'    |     PID: 17741
18:23:09 redis_cache.1    |   `-._    `-._  `-./  _.-'    _.-'                                   
18:23:09 redis_cache.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:23:09 redis_cache.1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
18:23:09 redis_cache.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:23:09 redis_cache.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:23:09 redis_cache.1    |  |    `-._`-._        _.-'_.-'    |                                  
18:23:09 redis_cache.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.078 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
18:23:09 redis_cache.1    |       `-._    `-.__.-'    _.-'                                       
18:23:09 redis_cache.1    |           `-._        _.-'                                           
18:23:09 redis_cache.1    |               `-.__.-'                                               
18:23:09 redis_cache.1    | 
18:23:09 redis_queue.1    |                 _._                                                  
18:23:09 redis_queue.1    |            _.-``__ ''-._                                             
18:23:09 redis_queue.1    |       _.-``    `.  `_.  ''-._           Redis 3.2.3 (00000000/0) 64 bit
18:23:09 redis_queue.1    |   .-`` .-```.  ```\/    _.,_ ''-._                                   
18:23:09 redis_queue.1    |  (    '      ,       .-`  | `,    )     Running in standalone mode
18:23:09 redis_queue.1    |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 11000
18:23:09 redis_queue.1    |  |    `-._   `._    /     _.-'    |     PID: 17739
18:23:09 redis_queue.1    |   `-._    `-._  `-./  _.-'    _.-'                                   
18:23:09 redis_queue.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:23:09 redis_queue.1    |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
18:23:09 redis_queue.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:23:09 redis_queue.1    |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
18:23:09 redis_queue.1    |  |    `-._`-._        _.-'_.-'    |                                  
18:23:09 redis_queue.1    |   `-._    `-._`-.__.-'_.-'    _.-'                                   
18:23:09 redis_queue.1    |       `-._    `-.__.-'    _.-'                                       
18:23:09 redis_queue.1    |           `-._        _.-'                                           
18:23:09 redis_queue.1    |               `-.__.-'                                               
18:23:09 redis_queue.1    | 
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.086 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.087 # Server started, Redis version 3.2.3
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.087 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.087 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.087 # Server started, Redis version 3.2.3
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.088 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.088 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
18:23:09 redis_cache.1    | 17741:M 29 Aug 18:23:09.088 * The server is now ready to accept connections on port 13000
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.088 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
18:23:09 redis_queue.1    | 17739:M 29 Aug 18:23:09.089 * The server is now ready to accept connections on port 11000
18:23:11 socketio.1       | listening on *: 9000
18:23:14 web.1            |  * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
18:23:14 web.1            |  * Restarting with inotify reloader
18:23:14 worker_long.1    | 18:23:14 RQ worker u'rq:worker:localhost.localdomain.17728.long' started, version 0.8.1
18:23:14 worker_long.1    | 18:23:14 Cleaning registries for queue: long
18:23:14 worker_long.1    | 18:23:14 
18:23:14 worker_long.1    | 18:23:14 *** Listening on long...
18:23:14 worker_default.1 | 18:23:14 RQ worker u'rq:worker:localhost.localdomain.17747.default' started, version 0.8.1
18:23:14 worker_default.1 | 18:23:14 Cleaning registries for queue: default
18:23:14 worker_default.1 | 18:23:14 
18:23:14 worker_default.1 | 18:23:14 *** Listening on default...
18:23:14 worker_short.1   | 18:23:14 RQ worker u'rq:worker:localhost.localdomain.17746.short' started, version 0.8.1
18:23:14 worker_short.1   | 18:23:14 Cleaning registries for queue: short
18:23:14 worker_short.1   | 18:23:14 
18:23:14 worker_short.1   | 18:23:14 *** Listening on short...
18:23:14 web.1            |  * Debugger is active!
18:23:14 web.1            |  * Debugger PIN: 166-041-143
18:23:15 watch.1          | compiling avatar.less
18:23:15 watch.1          | compiling calendar.less
18:23:15 watch.1          | compiling common.less
18:23:15 watch.1          | compiling desk.less
18:23:15 watch.1          | compiling desktop.less
18:23:15 watch.1          | compiling docs.less
18:23:15 watch.1          | compiling email.less
18:23:15 watch.1          | compiling form.less
18:23:15 watch.1          | compiling form_grid.less
18:23:15 watch.1          | compiling gantt.less
18:23:15 watch.1          | compiling graphs.less
18:23:15 watch.1          | compiling indicator.less
18:23:15 watch.1          | compiling kanban.less
18:23:15 watch.1          | compiling list.less
18:23:15 watch.1          | compiling mixins.less
18:23:15 watch.1          | compiling mobile.less
18:23:15 watch.1          | compiling module.less
18:23:15 watch.1          | compiling navbar.less
18:23:15 watch.1          | compiling page.less
18:23:15 watch.1          | compiling report.less
18:23:15 watch.1          | compiling role_editor.less
18:23:15 watch.1          | compiling sidebar.less
18:23:15 watch.1          | compiling slickgrid.less
18:23:15 watch.1          | compiling tree.less
18:23:15 watch.1          | compiling website.less
18:23:15 watch.1          | file watching on *: 6787
18:23:16 watch.1          | Less files compiled
18:23:16 watch.1          | Wrote css/frappe-web.css - 65.36 KB
18:23:17 watch.1          | Wrote js/frappe-web.min.js - 132.33 KB
18:23:18 watch.1          | Wrote js/control.min.js - 61.42 KB
18:23:19 watch.1          | Wrote js/dialog.min.js - 108.94 KB
18:23:19 watch.1          | Wrote css/desk.min.css - 293.66 KB
18:23:19 watch.1          | Wrote css/frappe-rtl.css - 32.6 KB
18:23:19 watch.1          | Wrote js/libs.min.js - 843.67 KB
18:23:23 watch.1          | Wrote js/desk.min.js - 460.75 KB
18:23:23 watch.1          | Wrote js/d3.min.js - 380.4 KB
18:23:23 watch.1          | Wrote css/module.min.css - 2.16 KB
18:23:23 watch.1          | Wrote css/form.min.css - 4.55 KB
18:23:24 watch.1          | Wrote js/form.min.js - 196.87 KB
18:23:24 watch.1          | Wrote css/list.min.css - 14.82 KB
18:23:25 watch.1          | Wrote js/list.min.js - 143.14 KB
18:23:25 watch.1          | Wrote css/report.min.css - 8.31 KB
18:23:26 watch.1          | Wrote js/report.min.js - 261.37 KB
18:23:26 watch.1          | Wrote js/web_form.min.js - 247.58 KB
18:23:26 watch.1          | Wrote css/web_form.css - 24.69 KB
18:23:26 watch.1          | Wrote js/print_format_v3.min.js - 23.64 KB

**Comment by saurabh6790** [comment]
Seems site not installed properly. Please reinstall a site `bench --site site-name reinstall`
