### ISSUE TITLE
Unable to install in Ubuntu 16.04 LTS 1GB ram

### ISSUE THREAD

**Issue by Borisbudini** [frappe/bench#479]
Hey! I am getting this error when running the script for production
TASK [Create new site] ********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: No closing quotation
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_9PwWvj/ansible_module_command.py\", line 220, in <module>\n    main()\n  File \"/tmp/ansible_9PwWvj/ansible_module_command.py\", line 194, in main\n    args = shlex.split(args)\n  File \"/usr/lib/python2.7/shlex.py\", line 279, in split\n    return list(lex)\n  File \"/usr/lib/python2.7/shlex.py\", line 269, in next\n    token = self.get_token()\n  File \"/usr/lib/python2.7/shlex.py\", line 96, in get_token\n    raw = self.read_token()\n  File \"/usr/lib/python2.7/shlex.py\", line 172, in read_token\n    raise ValueError, \"No closing quotation\"\nValueError: No closing quotation\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/tmp/.bench/playbooks/production/install.retry

PLAY RECAP ********************************************************************************************************************************************************************
localhost                  : ok=40   changed=8    unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 381, in <module>
    install_bench(args)
  File "install.py", line 111, in install_bench
    run_playbook('production/install.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 323, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'production/install.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2

**Comment by vpnguyen** [comment]
From the readme at https://github.com/frappe/bench, it says:

"If you are using on a VPS make sure it has >= 1Gb of RAM or has swap setup properly."

I just setup successfully on a VPS with 512MB ram and 2GB swap file. Run very fast with 1 user :)

**Comment by Borisbudini** [comment]
I already have 1GB of ramOn Sep 10, 2017 23:52, "V.P. Nguyen" <notifications@github.com> wrote:From the readme at https://github.com/frappe/bench, it says:
"If you are using on a VPS make sure it has >= 1Gb of RAM or has swap setup properly."
I just setup successfully on a VPS with 512MB ram and 2GB swap file. Run very fast with 1 user :)

**Comment by saurabh6790** [comment]
Have you set up a swap area?

**Comment by SOLOSOFTMA** [comment]
it's related to some yml files missing in playbooks i have the same issue not yet resolved

**Comment by saurabh6790** [comment]
I think this has been fixed! Please check and if the issue persists, feel free to reopen the issue.
