### ISSUE TITLE
Unable to install on debian 8.9, debian 9 and mac OS sierra

### ISSUE THREAD

**Issue by serCliff** [frappe/bench#494]
No one of the scripts works

**Comment by achillesrasquinha** [comment]
Try 
```console
$ curl -sL bit.do/get-bench | python
```
For mac OS Sierra?

**Comment by jwrober** [comment]
Follow these steps

https://jwrober.github.io/erpnext_admin_guide/i-u-b/install

Also Debian 9 is not supported. 7 and 8 are.
