### ISSUE TITLE
[Feature Requests] Add cache and dependencies checker to Bench

### ISSUE THREAD

**Issue by ghost** [frappe/bench#496]
While installing bench via the steps mentioned in the readme file, I encountered two issue.

* Bench didn't check the dependencies (e.g. npm) required for it's installation. It ran the process of build and complained about missing dependency at a much later stage. Ideally bench should be intelligent enough to check the dependencies available in the system and advice (or if possible install the dependencies ) the user accordingly.

* While installing bench or frappe via bench, it would be great to have a cache for downloaded date which gets pulled either via git or some other sources (in future), so that at a time when the install process or build process fails, it would continue from the stuf where it stopped, without the need to re-download or pull stuff. There is also a problem where bench complains and fails if there is already a folder that was left with a broken download or pull earlier. It should advice or automatically clean any corrupt or irrelevant folders

I hope I have ellaborated the issue correctly.

**Comment by achillesrasquinha** [comment]
With regards to the first point, you must have surely used the manual way of installing which provides you full control over what you install. We've got our install scripts that helps you install all dependencies bench requires.

With regards to point 2, I so agree. Working on it 😄

**Comment by raghukamath** [comment]
@achillesrasquinha , on point one, this is no issue since user will normally see the dependencies from the manual before trying, it is just a convenience in case someone jumps right into it. I tried the steps which are given in the bench readme.

Thanks for working on Point 2 👍

**Comment by raghukamath** [comment]
I guess we can close this now. Is it merged yet?
