### ISSUE TITLE
ValidationError: Setup Already Complete! how to solve this problem

### ISSUE THREAD

**Issue by RVMurugan** [frappe/bench#511]
![screenshot from 2017-11-29 11-20-47](https://user-images.githubusercontent.com/30973681/33373648-e225cbd6-d528-11e7-9ace-6f49b6fb0b72.png)
![screenshot from 2017-11-29 11-21-06](https://user-images.githubusercontent.com/30973681/33373649-e268ed44-d528-11e7-91c3-03e40260aadf.png)
![screenshot from 2017-11-29 11-40-11](https://user-images.githubusercontent.com/30973681/33373650-e2971b2e-d528-11e7-9063-6812e6405561.png)

**Comment by manassolanki** [comment]
Hi,
This is not a valid issue for this repo. Please create issue on ERPNext/Frappé repo or post your issue on discuss.erpnext.com
