### ISSUE TITLE
Bench update fails when you use a language different than english

### ISSUE THREAD

**Issue by germanp** [frappe/bench#514]
Hi,

I was trying to run:

``` $ bench update```

But I always obtained:

```Cannot proceed with update: You have local changes in app "frappe" that are not committed.```

Unfortunately, when I check the frappe folder under the app/ directory I realize that there aren't changes in the local so repo, so, there is no reason to get this error. Btw, I checked in the code and I found that it is matching against the git's output (https://github.com/frappe/bench/blob/master/bench/app.py#L145) but my computer is configured in spanish, so there is no way to match with the same string. 

I know there is a --porcelain flag in git to avoid this class of issues. (https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain)

**Comment by germanp** [comment]
As a workaround I've run:
``` $ export LANG=en```
And then:
``` $ bench upgrade```
And it is works.

Cheers

**Comment by saurabh6790** [comment]
```
You have local changes in app "frappe" that are not committed.
```

seems you have local changes (code changes or related to directory permissions)

**Comment by germanp** [comment]
Instead of suddenly close the issue, please, take some time to read it, As I took the time to verify the source code and look for a workaround.

Among others, this kind of attitudes made me to stop using erpnext.

**Comment by jasonbrowne** [comment]
from bench-repo run git status

example:

[latte@erpnext-v ~/bench-repo]$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   bench/config/templates/502.html

no changes added to commit (use "git add" and/or "git commit -a")
[latte@erpnext-v ~/bench-repo]$

**Comment by germanp** [comment]
That was the first thing I've tried. But when I checked the code I've realized that the message comes from the bench code. If you check https://github.com/frappe/bench/blob/master/bench/app.py#L176 you will see that the regular expresion is looking for "nothing to commit, working " string but my computer is configured in spanish, so the the message I've get is:

`nada para hacer commit, el árbol de trabajo esta limpio`

So, there is no way that this will match

Again, please take the time to read thoroughly all issue description.
