### ISSUE TITLE
Workflow give edit permission to multiple role for single state

### ISSUE THREAD

**Issue by jigartarpara** [frappe/bench#516]
If I add multiple role permission for single state of document 
then only first permission will work and others will be ignored 

state               Only Allow Edit For
Approved       Project User
Approved       Finance manager

for above case, if the document is in the approved state then only project user able to change document
but finance manager will unable to change document

**Comment by saurabh6790** [comment]
Please post this issue at https://github.com/frappe/erpnext/issues/new or https://discuss.erpnext.com
