### ISSUE TITLE
Attempting to install on Windows Subsystem for Linux 

### ISSUE THREAD

**Issue by tedzhu** [frappe/bench#522]
Hi all, I decided to have a go at installing bench and ERPNext on WSL, want to list what I did here.

The WSL is a ubuntu on windows 10. Downloaded and running the install script (https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py)

1. There's no localectl, removed the line with 'locale' in '/tmp/.bench/playbooks/prerequisites/install_roles.yml'.
2. Ran into the exception syntax error in (https://github.com/frappe/bench/pull/466), not sure whether it's fixed. Changed first line in 'bench' from python3 to python. At this point bench runs.
3. Now it stops at 'bench --site site1.local install-app erpnext'.
```
  File "/home/ted/frappe-bench/apps/frappe/frappe/commands/site.py", line 165, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/ted/frappe-bench/apps/frappe/frappe/installer.py", line 131, in install_app
    frappe.only_for("System Manager")
  File "/home/ted/frappe-bench/apps/frappe/frappe/__init__.py", line 480, in only_for
    raise PermissionError
```
my roles is set(['All', 'Guest'])
If I skip this check, the program runs, but appears to take suspiciously long time, with one line output:  "Installing erpnext...", CPU usage is low.

Guess it might not be a good idea to run on WSL at this point. Maybe some minor changes can get it running? Anyway that's all I got, any suggestions are welcomed.

Thanks!

**Comment by saurabh6790** [comment]
We don't support windows installations as of now!
