### ISSUE TITLE
Can't install chromedriver

### ISSUE THREAD

**Issue by hampoelz** [frappe/bench#526]
Hello,
When I run the `bench init frappe-bench && cd frappe-bench` command, I get the following messages:

> `frappe@rh-programm:~$ bench init frappe-bench && cd frappe-bench`
> `INFO:bench.utils:virtualenv -q env -p /usr/bin/python`
> `INFO:bench.utils:./env/bin/pip -q install --upgrade pip`
> `INFO:bench.utils:./env/bin/pip -q install wheel`
> `INFO:bench.utils:./env/bin/pip -q install six`
> `INFO:bench.utils:./env/bin/pip -q install -e git+https://github.com/frappe/python-pdfkit.git#egg=pdfkit`
> `INFO:bench.app:getting app frappe`
> `INFO:bench.utils:git clone https://github.com/frappe/frappe.git   --origin upstream`
> `Cloning into 'frappe'...`
> `remote: Counting objects: 137726, done.`
> `remote: Compressing objects: 100% (19/19), done.`
> `remote: Total 137726 (delta 6), reused 4 (delta 1), pack-reused 137706`
> `Receiving objects: 100% (137726/137726), 122.38 MiB | 1.71 MiB/s, done.`
> `Resolving deltas: 100% (103484/103484), done.`
> `Checking connectivity... done.`
> `('installing', u'frappe')`
> `INFO:bench.app:installing frappe`
> `INFO:bench.utils:frappe-bench/env/bin/pip install -q  -e frappe-bench/apps/frappe --no-cache-dir`
> `Updating node libraries...`
> `INFO:bench.utils:npm install`
> 
> `> uws@0.14.5 install /home/frappe/frappe-bench/node_modules/uws`
> `> node-gyp rebuild > build_log.txt 2>&1 || exit 0`
> 
> 
> `> chromedriver@2.34.0 install /home/frappe/frappe-bench/node_modules/chromedriver`
> `> node install.js`
> 
> `Downloading https://chromedriver.storage.googleapis.com/2.34/chromedriver_linux32.zip`
> `Saving to /tmp/chromedriver/chromedriver_linux32.zip`
> `Received 0K total.`
> `Extracting zip contents`
> `ChromeDriver installation failed Error extracting archive: Error: end of central directory record signature not found`
> `npm WARN frappe@ No description`
> `npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):`
> `npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})`
> 
> `npm ERR! code ELIFECYCLE`
> `npm ERR! errno 1`
> `npm ERR! chromedriver@2.34.0 install: 'node install.js'`
> `npm ERR! Exit status 1`
> `npm ERR!`
> `npm ERR! Failed at the chromedriver@2.34.0 install script.`
> `npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`
> 
> `npm ERR! A complete log of this run can be found in:`
> `npm ERR!     /home/frappe/.npm/_logs/2018-01-01T21_12_02_490Z-debug.log`
> `Traceback (most recent call last):`
> `  File "/usr/local/bin/bench", line 11, in <module>`
> `    load_entry_point('bench', 'console_scripts', 'bench')()`
> `  File "/home/frappe/bench-repo/bench/cli.py", line 40, in cli`
> `    bench_command()`
> `  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__`
> `    return self.main(*args, **kwargs)`
> `  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main`
> `    rv = self.invoke(ctx)`
> `  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke`
> `    return _process_result(sub_ctx.command.invoke(sub_ctx))`
> `  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke`
> `    return ctx.invoke(self.callback, **ctx.params)`
> `  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke`
> `    return callback(*args, **kwargs)`
> `  File "/home/frappe/bench-repo/bench/commands/make.py", line 21, in init`
> `    verbose=verbose, clone_from=clone_from, skip_bench_mkdir=skip_bench_mkdir, skip_redis_config_generation=skip_redis_config_generation)`
> `  File "/home/frappe/bench-repo/bench/utils.py", line 72, in init`
> `    update_npm_packages(bench_path=path)`
> `  File "/home/frappe/bench-repo/bench/utils.py", line 442, in update_npm_packages`
> `    exec_cmd('npm install', cwd=bench_path)`
> `  File "/home/frappe/bench-repo/bench/utils.py", line 140, in exec_cmd`
> `    raise CommandFailedError(cmd)`
> `bench.utils.CommandFailedError: npm install`

**Comment by rh-programm** [comment]
Update: https://github.com/giggio/node-chromedriver/issues/136

Is there any way to install erpnext with chromedriver '2.33'?

**Comment by chungyan5** [comment]
hi rh-programm, 
I faced exactly your same error, looked at internet and finally came to your this Issue. 

* Reason: chromedriver >=2.34.x does not support 32bit Linux any more
* Solution: need to downgrade the chromedriver to <2.34.x
    * login into Terminal #1
        * bench init frappe-bench && cd frappe-bench
    * login into Terminal #2 
        * ls -al /home/frappe/frappe-bench/apps/frappe/
        * until the /home/frappe/frappe-bench/apps/frappe/package.json existing (Terminal #1 will download the latest master branch of frappe)
    * login into Terminal #3 
        * vi /home/frappe/frappe-bench/apps/frappe/package.json
            …
            "chromedriver":     from "^2.32.3" to "~2.32.3",    (should be ~2.33.3, but my typing error in testing, it works)
            …
    * @ Terminal #1
        * after the above Terminal #2 & Terninal #3, it will pass this error.

**Comment by rh-programm** [comment]
Thank you.

close
