### ISSUE TITLE
Down load template for imports of items, etc should have an option to show required when manually selecting what to include.

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/bench#528]
Problem: When manually selecting what data to download there is no option to highlight or indicate what is required for re importing the data.

![feature](https://user-images.githubusercontent.com/19347811/34506608-455b311c-efe3-11e7-9e76-686118034f02.png)

**Comment by saurabh6790** [comment]
Please open this issue at https://github.com/frappe/erpnext/issues/new
