### ISSUE TITLE
Keyserver Timed Out 

### ISSUE THREAD

**Issue by maektwain** [frappe/bench#532]
https://github.com/frappe/bench/blob/6f186942114f92fbd134e3b390f5b30d5611c9a2/install_scripts/setup_frappe.sh#L139

ubuntu 14.04 

As I was trying to run /.setup....

It was throwing error
```
 Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.ckp7JbSIkh --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xcbcb082a1bb943db
gpg: requesting key 1BB943DB from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error
```

did 

had to manually import the gpg public key using gpg --import 

Thanks

**Comment by saurabh6790** [comment]
try to install via install.py

https://github.com/frappe/bench#easy-install
