### ISSUE TITLE
Stuck in "Sorry! We will be back soon." message after system freeze.

### ISSUE THREAD

**Issue by JrenzP** [frappe/bench#538]
I tried to install the "Shopify" app while I'm in the localhost:8080; then the system froze after I clicked the install and I had to restart my laptop.

After that, I opened the Virtual Machine and everything goes fine until I found out that I'm stuck at "Sorry! 
We will be back soon."
message.

What should I do?

![image](https://user-images.githubusercontent.com/30467646/34903849-ec4edeb2-f874-11e7-9c5d-0338b38aaa23.png)

**Comment by codingCoffee** [comment]
Closing. Feel free to open if issue persists, and give steps for replication of issue

**Comment by JrenzP** [comment]
Thank you!
