### ISSUE TITLE
Bench get-app should handle pre-existing app directories

### ISSUE THREAD

**Issue by ghost** [frappe/bench#554]
When you do get-app, if the folder already contains a directory by same name git will fail.
Bench should check whether thereis already a app directory and offer an option to user
- Delete the existing directory and and re-do a get-app
- Do a get-app except skip the cloning part

Use case - 
When a user does get-app , there may be a situation when get-app fails in middle of the operation.
when user tries to do a get-app again it complains about exisiting directory, this should be handled interactively by bench, without the need for deleting the directory manually and redoing get-app

**Comment by gavindsouza** [comment]
it should probably ask user confirmation for either of those. this could change depending on different use cases. In case, an error occurs mid clone operation, it'll have to be restarted again.
