### ISSUE TITLE
bench use:  No such command "use".

### ISSUE THREAD

**Issue by carlos22** [frappe/bench#558]
https://frappe.io/docs/user/en/bench/resources/bench-commands-cheatsheet.html
```
bench use [site] Sets a default site
```
```
frappe@erpnext:~$ bench use
Usage: bench [OPTIONS] COMMAND [ARGS]...

Error: No such command "use".
```
bench version: 4.1.0
OS: Ubuntu 16.04

**Comment by raghukamath** [comment]
@carlos22 I think you are not in the frappe bench folder.
Also the correct usage is
```
bench user yoursitename
```

**Comment by carlos22** [comment]
I noticed already that it is important to be in the correct folder. Will try again soon. But why can't bench detect the folder it is installed in?
