### ISSUE TITLE
bench update on install.py --production fails

### ISSUE THREAD

**Issue by carlos22** [frappe/bench#560]
A lot of files are not in the git index but I did not change anything? Is this a bug?
Seems to work with `bench update --reset` option, but am I now using the latest release or development version?

**Comment by KaruguDev** [comment]
its because of the `.pyc` files, `bench update --reset` deletes the `.pyc` files which are the reason for the conflict hence `bench update` command fails

**Comment by saurabh6790** [comment]
I think it's fixed,  if not feel free to reopen the issue.
