### ISSUE TITLE
ERPNext installation

### ISSUE THREAD

**Issue by shankargurutarikere** [frappe/bench#566]
![screenshot 49](https://user-images.githubusercontent.com/31584520/35850500-17c0a52e-0b4b-11e8-9440-0c90d018d9a1.png)

I am having windows OS.I have tried to install ERPnext in ubuntu(VM) in both manual and easy installation which has been given in the github. I am  facing this error please help me out.
and one more question,Can i develop ERPnext in windows??

**Comment by mwaigichuhi** [comment]
Hi @shankargurutarikere 

The dialog is not an error you will see this whenever you run an install in existing package environments so just make a selection. In this case just use the first one i.e. No configuration

Can i develop ERPnext in windows?
I suppose you could if running within a docker or similar environment but if you mean on Windows itself than you will likely have some challenges and so far not much interest or focus is put on this OS as a development environment so perhaps its time you learnt some Linux :-)

**Comment by saurabh6790** [comment]
You can download and use pre-installed vm https://erpnext.com/download
