### ISSUE TITLE
bench start issue in ubunutu.

### ISSUE THREAD

**Issue by shankargurutarikere** [frappe/bench#569]
I have added a site and installed erpnext according to the procedure given in (https://github.com/frappe/bench). Then i tried to start the bench using the command     bench start.
I am getting this error.where i went wrong?? I am unable to figure it out. 

![screenshot 64](https://user-images.githubusercontent.com/31584520/35958271-e2091566-0cc5-11e8-87d4-f162643d32cf.png)

**Comment by raghukamath** [comment]
Please don't ask support questions on a issue tracker, use forum for questions like this
closing this now, if the problem persists and you think that this is a bug then please let us know,

thanks
