### ISSUE TITLE
Unexpected token error durring Yarn rollup

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/bench#581]
[!] Error: Unexpected token
../../node_modules/frappe-datatable/dist/frappe-datatable.css (3:0)
1: /* variables */
2: 
3: .data-table {
   ^
4: 
5:   /* styling */

More info including commands and output can be found here:
https://oasis.sandstorm.io/shared/wqm0b0LW6VYMygQbgqWPqV576txfQkUPE2c8DqN2EZi

**Comment by codingCoffee** [comment]
Fixed. Feel free to reopen if necessary
