### ISSUE TITLE
ERPNext new data import tool does not get uncheck unmandatory files when mandatory is selected

### ISSUE THREAD

**Issue by jasonbrowne** [frappe/bench#592]
Problem: While attempting to use the new data import tool to down load item template with only mandatory fields all fields are checked.
![item](https://user-images.githubusercontent.com/19347811/37116195-69ddba18-2202-11e8-8b35-b014fe959bd0.png)

**Comment by achillesrasquinha** [comment]
Wrong Place to raise this issue. Please try erpnext isntead.
