### ISSUE TITLE
System Error Cleaning Old Sessions

### ISSUE THREAD

**Issue by ARAGATO** [frappe/bench#594]
Every day the system generates an error message, because the daily session cleaning process tries to clean a session of an non existing user.
![image](https://user-images.githubusercontent.com/25451106/37194850-c7301052-23a2-11e8-8422-0371c0b65fdb.png)
The user is me, but I renamed myself to a different email address. Unfortunately, this has triggered the daily session cleaning error.
![image](https://user-images.githubusercontent.com/25451106/37194859-d58a6602-23a2-11e8-9952-49d49e1b50e7.png)

How to solve it? Thanks.

**Comment by achillesrasquinha** [comment]
Can you move this issue to frappe? Thanks!

**Comment by achillesrasquinha** [comment]
Also by non-existent, you mean a deleted user or `inactive`?
