### ISSUE TITLE
install.py accepts blank password but fails setup because of it

### ISSUE THREAD

**Issue by oxwivi** [frappe/bench#609]
IIRC, when manually setting up MariaDB, you can just let the root password be blank, but while `install.py`'s prompt asks and accepts blank password, it fails at the `TASK` setting up database. The error message wasn't quite obvious about it and I didn't record those, but after multiple failures in using the script, I suspected lack of password and it worked, but only on fresh OS. Previous blank password attempts prevented subsequent attempts with proper password from succeeding.

**Comment by codingCoffee** [comment]
Fixed. Blank passwords are not accepted now
