### ISSUE TITLE
Error when installing in Ubuntu 16.04

### ISSUE THREAD

**Issue by SubrataBauri** [frappe/bench#629]
```
root@ip-***-**-**-**:/var/www/html# wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
--2018-04-10 11:30:48--  https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.188.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.188.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12330 (12K) [text/plain]
Saving to: ‘install.py.1’

install.py.1                         100%[====================================================================>]  12.04K  --.-KB/s    in 0s      

2018-04-10 11:30:48 (160 MB/s) - ‘install.py.1’ saved [12330/12330]

root@ip-***-**-**-**:/var/www/html# sudo python install.py --develop
Traceback (most recent call last):
  File "install.py", line 400, in <module>
    install_bench(args)
  File "install.py", line 8, in install_bench
    check_distribution_compatibility()
  File "install.py", line 132, in check_distribution_compatibility
    if float(dist_version) in supported_dists[dist_name]:
ValueError: could not convert string to float: stretch/sid
root@ip-***-**-**-**:/var/www/html# 
```

`***-**-**-** is my masked IP`

**Comment by codingCoffee** [comment]
Any particular reason for doing it in the `/var/www/html` folder? 

By any chance did you modify the `install.py` script you downloaded earlier?

Also the install script you downloaded seems to be `install.py.1` and not `install.py`. Maybe you had already downloaded it before. Try removing both using `rm install.py install.py.1` and then try `wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py` and then execute `sudo python install.py --develop`

**Comment by SubrataBauri** [comment]
@codingCoffee 
No, not any particular reason to run it from `/var/www/html`
`root@ip-***-**-**-**:/var/www/html# sudo python install.py --develop`
```
Traceback (most recent call last):
  File "install.py", line 400, in <module>
    install_bench(args)
  File "install.py", line 8, in install_bench
    check_distribution_compatibility()
  File "install.py", line 132, in check_distribution_compatibility
    if float(dist_version) in supported_dists[dist_name]:
ValueError: could not convert string to float: stretch/sid
```

**Comment by codingCoffee** [comment]
I'm not about to replicate the error.
Can you open a python console:
```
python
```
And then execute the following and post the output here:
```
import platform
platform.dist()
```

**Comment by SubrataBauri** [comment]
@codingCoffee 
```
>>> import platform
>>> platform.dist()
('debian', 'stretch/sid', '')
```

**Comment by codingCoffee** [comment]
It seems you're **not** using **Ubuntu 16.04**, and rather an old version of **Debian**, which is causing this error. Closing the issue.

**Comment by SubrataBauri** [comment]
@codingCoffee 
`lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

**Comment by codingCoffee** [comment]
Okay, something seems off... Which cloud provider are you using ?

**Comment by SubrataBauri** [comment]
@codingCoffee  AWS

**Comment by SubrataBauri** [comment]
@codingCoffee any idea about the cause of the error?

**Comment by codingCoffee** [comment]
@SubrataBauri I tried executing the following commands on multiple instances:
```
>>> import platform
>>> platform.dist()
```
And none of them provide the output 
```
('debian', 'stretch/sid', '')
```
They all provide
```
('Ubuntu', '16.04', 'xenial')
```
as the output.

So, it's most likely an AWS specific issue. However, since AWS is a popular platform the issue cannot be ignored. I'll need some help from you to fix it. Will you be able to help out? If yes, once you download the install.py script, just comment out line no 8:
```
	check_distribution_compatibility()
```
and execute the script using 
```
sudo python install.py --production
```
and see if you're able to install ERPNext. If not post the error log here. Thanks

**Comment by SubrataBauri** [comment]
Hi, 
I created a new instance with a community provided AMI for Ubuntu, installed all the prerequisite with latest version (except for python 2.7) and tried reinstalling and it did install properly. I installed with default `ubuntu` user and did not create any separate user.

**Comment by codingCoffee** [comment]
Which AMI were you using previously?
Did you comment out the line I mentioned or tried the installation without commenting it?

**Comment by codingCoffee** [comment]
Alright, so I guess it seems to be a problem with the particular AMI with ID ami-916f59f4, and not with the install scripts. So I think it's safe to close the issue. Thanks for reporting it.
