### ISSUE TITLE
Unable to install in Ubuntu 16.04 failed:1

### ISSUE THREAD

**Issue by RamAmancha** [frappe/bench#636]
error in Ubuntu 16.04
distribution was not found and is required by bench
to retry user --limit @/tmp/.bench/playbooks/site.retry

**Comment by codingCoffee** [comment]
Can you post the entire error log and which command you executed

**Comment by RamAmancha** [comment]
commands:
wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
on a fresh Ubuntu server:
python install.py --develop --user frappe
sudo python install.py --production

Error Log:
TASK [bench : python2 bench init for production] *******************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["bench", "init", "/home/frappe/frappe-bench", "--frappe-branch", "master"], "delta": "0:00:00.148754", "end": "2018-04-13 15:58:48.085182", "msg": "non-zero return code", "rc": 1, "start": "2018-04-13 15:58:47.936428", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/bench\", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3088, in <module>\n    @_call_aside\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3072, in _call_aside\n    f(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3101, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 574, in _build_master\n    ws.require(__requires__)\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 892, in require\n    needed = self.resolve(parse_requirements(requirements))\n  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 778, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The 'GitPython==0.3.2.1' distribution was not found and is required by bench", "stderr_lines": ["Traceback (most recent call last):", "  File \"/usr/local/bin/bench\", line 6, in <module>", "    from pkg_resources import load_entry_point", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3088, in <module>", "    @_call_aside", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3072, in _call_aside", "    f(*args, **kwargs)", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 3101, in _initialize_master_working_set", "    working_set = WorkingSet._build_master()", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 574, in _build_master", "    ws.require(__requires__)", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 892, in require", "    needed = self.resolve(parse_requirements(requirements))", "  File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 778, in resolve", "    raise DistributionNotFound(req, requirers)", "pkg_resources.DistributionNotFound: The 'GitPython==0.3.2.1' distribution was not found and is required by bench"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=70   changed=17   unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 400, in <module>
    install_bench(args)
  File "install.py", line 117, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 333, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2

**Comment by codingCoffee** [comment]
Run,
```
apt-get update
apt-get upgrade -y
apt-get install -y python-minimal curl git wget
```
on a **fresh server** before running the install scripts and try again

**Comment by RamAmancha** [comment]
Thanks for the quick response.  Its working!!! here are the complete steps
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install -y python-minimal curl git wget
sudo wget https://raw.githubusercontent.com/frappe/bench/master/playbooks/install.py
sudo python install.py --develop --user frappe
sudo python install.py --production

**Comment by codingCoffee** [comment]
@RamAmancha, henceforth please post such queries on the forum https://discuss.erpnext.com before opening issues!
