### ISSUE TITLE
Unable to install frappe - Easy Install

### ISSUE THREAD

**Issue by Navneet-Suresh** [frappe/bench#645]
> root@erpnext:/# python install.py --production
> Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
> Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease
> Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
> Hit:4 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> build-essential is already the newest version (12.1ubuntu2).
> libffi-dev is already the newest version (3.2.1-4).
> python-setuptools is already the newest version (20.7.0-1).
> git is already the newest version (1:2.7.4-0ubuntu1.3).
> libssl-dev is already the newest version (1.0.2g-1ubuntu4.12).
> python-dev is already the newest version (2.7.12-1~16.04).
> 0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
> Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages
> Requirement already up-to-date: pip==9.0.3 in /usr/local/lib/python2.7/dist-packages
> You are using pip version 9.0.3, however version 10.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> Requirement already satisfied: ansible in /usr/local/lib/python2.7/dist-packages
> Requirement already satisfied: paramiko in /usr/local/lib/python2.7/dist-packages (from ansible)
> Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from ansible)
> Requirement already satisfied: jinja2 in /usr/local/lib/python2.7/dist-packages (from ansible)
> Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages (from ansible)
> Requirement already satisfied: PyYAML in /usr/local/lib/python2.7/dist-packages (from ansible)
> Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible)
> Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible)
> Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from paramiko->ansible)
> Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from jinja2->ansible)
> Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible)
> Requirement already satisfied: enum34; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible)
> Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible)
> Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible)
> Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible)
> Requirement already satisfied: ipaddress; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from cryptography->ansible)
> Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->ansible)
> You are using pip version 9.0.3, however version 10.0.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
>  [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
> 
>  [WARNING]: No inventory was parsed, only implicit localhost is available
> 
>  [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
> 
> 
> PLAY [localhost] ****************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] **********************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Create user] **************************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Set home folder perms] ****************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Set home folder perms] ****************************************************************************************************************************************************************
> skipping: [localhost]
> 
> TASK [Set /tmp/.bench folder perms] *********************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [Change default shell to bash] *********************************************************************************************************************************************************
> changed: [localhost]
> 
> PLAY RECAP **********************************************************************************************************************************************************************************
> localhost                  : ok=5    changed=1    unreachable=0    failed=0
> 
> Passwords saved at ~/passwords.txt
>  [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source
> 
>  [WARNING]: No inventory was parsed, only implicit localhost is available
> 
>  [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
> 
> 
> PLAY [localhost] ****************************************************************************************************************************************************************************
> 
> TASK [Gathering Facts] **********************************************************************************************************************************************************************
> ok: [localhost]
> 
> TASK [common : include_tasks] ***************************************************************************************************************************************************************
> included: /tmp/.bench/playbooks/roles/common/tasks/debian_family.yml for localhost
> 
> TASK [common : Install prerequisites using apt-get] *****************************************************************************************************************************************
> ok: [localhost] => (item=[u'dnsmasq', u'fontconfig', u'git', u'htop', u'libcrypto++-dev', u'libfreetype6-dev', u'liblcms2-dev', u'libssl-dev', u'libwebp-dev', u'libxext6', u'libxrender1', u'libxslt1-dev', u'libxslt1.1', u'libffi-dev', u'ntp', u'postfix', u'python-dev', u'python3-dev', u'python-tk', u'screen', u'vim', u'xfonts-75dpi', u'xfonts-base', u'zlib1g-dev', u'apt-transport-https', u'libsasl2-dev', u'libldap2-dev'])
> 
> TASK [common : include_tasks] ***************************************************************************************************************************************************************
> skipping: [localhost]
> 
> TASK [common : include_tasks] ***************************************************************************************************************************************************************
> included: /tmp/.bench/playbooks/roles/common/tasks/ubuntu.yml for localhost
> 
> TASK [common : install pillow prerequisites for Ubuntu < 14.04] *****************************************************************************************************************************
> [DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare` instead use `result is version_compare`. This feature will be removed in version 2.9.
>  Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> skipping: [localhost] => (item=[])
> 
> TASK [common : install pillow prerequisites for Ubuntu >= 14.04] ****************************************************************************************************************************
> [DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|version_compare` instead use `result is version_compare`. This feature will be removed in version 2.9.
>  Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
> ok: [localhost] => (item=[u'libjpeg8-dev', u'libtiff5-dev', u'tcl8.6-dev', u'tk8.6-dev'])
> 
> TASK [common : include_tasks] ***************************************************************************************************************************************************************
> skipping: [localhost]
> 
> TASK [locale : Check current locale] ********************************************************************************************************************************************************
> fatal: [localhost]: FAILED! => {"changed": true, "cmd": "localectl", "delta": "0:00:00.507265", "end": "2018-04-24 07:38:26.058610", "msg": "non-zero return code", "rc": 1, "start": "2018-04-24 07:38:25.551345", "stderr": "Failed to create bus connection: No such file or directory", "stderr_lines": ["Failed to create bus connection: No such file or directory"], "stdout": "", "stdout_lines": []}
>         to retry, use: --limit @/tmp/.bench/playbooks/site.retry
> 
> PLAY RECAP **********************************************************************************************************************************************************************************
> localhost                  : ok=5    changed=0    unreachable=0    failed=1
> 
> Traceback (most recent call last):
>   File "install.py", line 417, in <module>
>     install_bench(args)
>   File "install.py", line 122, in install_bench
>     run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
>   File "install.py", line 338, in run_playbook
>     success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
> 

I am using easy install.

**Comment by codingCoffee** [comment]
Are you trying to install it inside docker or any other container based virtualization system ??

**Comment by Navneet-Suresh** [comment]
Yes, I am installing it inside docker container.
Using Ubuntu as a base image.

**Comment by codingCoffee** [comment]
Please use manual installation for the same.
Ref: https://github.com/frappe/frappe/wiki/The-Hitchhiker's-Guide-to-Installing-Frapp%C3%A9-on-Linux-OS
The easy install scripts are meant only for fresh servers, with complete virtualization, and not container based virtualization.

**Comment by Navneet-Suresh** [comment]
Okay. Thanks
