### ISSUE TITLE
Error at easy installer

### ISSUE THREAD

**Issue by elba7r** [frappe/bench#650]
fatal: [localhost]: FAILED! => {"reason": "Unable to retrieve file contents\nCould not find or access '/tmp/.bench/playbooks/setup_erpnext.yml'"}

**Comment by codingCoffee** [comment]
Please post the entire error log, with details about:
Operating system, virtualization if you're using any, all commands you executed in sequence to arrive at this

**Comment by elba7r** [comment]
there is no entire error log its only this red line which i sent to you and im using ubuntu server 16.04 lts

**Comment by elba7r** [comment]
i used sudo apt-get update 
sudo apt-get upgrade
sudo install python-minimal 
sudo install build-essential python-setuptools
sudo python install.py --production

**Comment by elba7r** [comment]
@codingCoffee 
Here all what i can get from terminal : 

TASK [bench : include_tasks] ***************************************************
fatal: [localhost]: FAILED! => {"reason": "Unable to retrieve file contents\nCould not find or access '/tmp/.bench/playbooks/setup_erpnext.yml'"}
	to retry, use: --limit @/tmp/.bench/playbooks/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=77   changed=44   unreachable=0    failed=1   

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2

**Comment by elba7r** [comment]
@codingCoffee 
git status response is : 

On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean

git log --format="%H" -n 1 response : 

0040a9d324aedf386514812b1c9805242db6ac08

i hope this will help on fixing the problem

**Comment by elba7r** [comment]
@codingCoffee 

i tried to install from your repo and it completed so it looks like the error from my own repo, it looks like i did not migrate the updates correctly so im downloading the last version of your repo and will check for the error and fix it then will try to install again, so im sorry for wasting your time about this issue and will get back to you if there is still any errors.

Best Regards

**Comment by elba7r** [comment]
@codingCoffee 
i replaced my repo with the latest updates and i found 2 files did not migrated when i pulled the latest updates, so now the installer is working fine.

Thanks very much for your response

Best Regards
