### ISSUE TITLE
Ansible Syntax Error while installing frappe - Ubuntu 16.04

### ISSUE THREAD

**Issue by navdeepghai1** [frappe/bench#652]
> Distributor ID:	Ubuntu
> Description:	Ubuntu 16.04.3 LTS
> Release:	16.04
> Codename:	xenial

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/tmp/.bench/playbooks/roles/common/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- include_tasks: debian_family.yml
  ^ here

The error appears to have been in '/tmp/.bench/playbooks/roles/common/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- include_tasks: debian_family.yml
  ^ here

**Comment by codingCoffee** [comment]
Unable to replicate error. Install scripts seem to be working perfectly. Please provide some more details. What were the exact sequence of commands you executed. Also post the output of the following:
```
cd /tmp/.bench
git status
git log --format="%H" -n 1
```

**Comment by codingCoffee** [comment]
Ohh, alright, thanks for mentioning. Will fix it up

ToDo:
- [ ] Update ansible before script execution

**Comment by aleksas** [comment]
Any update on this?

Having the same issue on **Debian GNU/Linux 8.10 (jessie)** during fresh production install.


```
....

Passwords saved at ~/passwords.txt
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/tmp/.bench/playbooks/roles/common/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include_tasks: debian_family.yml
  ^ here


The error appears to have been in '/tmp/.bench/playbooks/roles/common/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- include_tasks: debian_family.yml
  ^ here

Traceback (most recent call last):
  File "install.py", line 417, in <module>
    install_bench(args)
  File "install.py", line 122, in install_bench
    run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
  File "install.py", line 338, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 4

```

**Comment by codingCoffee** [comment]
I tried on a digital ocean droplet Debian 8.10. It's working perfectly. May I know which VPS provider you're using?

**Comment by aleksas** [comment]
It's not VPS it's a local server.

**Comment by aleksas** [comment]
Fixed the issue by removing `ansible` executable manually, and `pip uninstall ansible`. The latter should have been sufficient.
