### ISSUE TITLE
developent error

### ISSUE THREAD

**Issue by agrameshprasath** [frappe/bench#659]
hi
while developing the site
i added the line in site_conf.json 
 "developer_mode": 1,
 "host_name":"http://meeting.dev:8000"

and added the line in 
127.0.0.1       meeting.dev

but i receive error like this.

14:51:48 web.1            | 127.0.0.1 - - [07/May/2018 14:51:48] "�����-�7�`��v�j��Zy��DFD$;�
14:51:48 web.1            | �+�/̨̩�,�0�" 400 -
14:51:48 web.1            | INFO:werkzeug:127.0.0.1 - - [07/May/2018 14:51:48] "�����-�7�`��v�j��Zy��DFD$;�
14:51:48 web.1            | �+�/̨̩�,�0�" 400 -

thanks in advance

**Comment by codingCoffee** [comment]
Please check if you're trying to access the site on `https` instead of `http`
