### ISSUE TITLE
Ubuntu 18.04 support

### ISSUE THREAD

**Issue by codingCoffee** [frappe/bench#660]

**Comment by akshaykodali** [comment]
- [ ] `bench setup production` should output systemd unit files

**Comment by williamjmorenor** [comment]
The installation guidelines recomends a Ubuntu 16-04 host, so we are many out there running frappe and erpnext on a Ubuntu 16-04 host, so should be great to have official support updating from Ubuntu 16.04 to Ubuntu 18.04, this mean than frappe and bench should support the python, nodejs, mariadb and redis version available in both versions of the OS.
