### ISSUE TITLE
Update to Pip 10.0.1

### ISSUE THREAD

**Issue by dottenbr** [frappe/bench#690]
You are using pip version 9.0.3 in your virtualenv `/env`, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command or changing the requirements text file to pip 10.0.1.

Every bench update sees this alert message, why not just update?

<img width="547" alt="screen shot 2018-07-03 at 2 55 04 pm" src="https://user-images.githubusercontent.com/9136094/42203362-1db3af22-7ed1-11e8-8b2f-caca0245cb7c.png">

**Comment by dottenbr** [comment]
To do this manually:

1) make sure you are logged in with the `frappe` user
2) go to your frappe-bench folder
3) run this command `. env/bin/activate && pip install --upgrade pip && deactivate`

**Comment by dottenbr** [comment]
When you manually update PIP it will be downgraded again by bench

<img width="563" alt="screen shot 2018-07-06 at 8 56 07 am" src="https://user-images.githubusercontent.com/9136094/42354613-98b3dcb2-80fa-11e8-8e3f-91059c2d1d36.png">

**Comment by codingCoffee** [comment]
I PR is open to remove the hard coded pip downgrade.
Will merge it soon.
