### ISSUE TITLE
module parse_requirements not found in pip 10 error

### ISSUE THREAD

**Issue by navdeepghai1** [frappe/bench#695]
In pip version 10.X.X, pip has moved  parse_requirements  from pip.req to pip._internal.req.
Please fix it for the new users.

I have fixed the error using:
```
try:
    # For oldest version
    from pip.req import parse_requirements
except ImportError as e:
   # for new version
   from pip._internal.req import parse_requirements
```

Facing same error in foundation app also.

**Comment by codingCoffee** [comment]
It has already been fixed. Please pull the latest changes.
