### ISSUE TITLE
Monthly Target not changing.

### ISSUE THREAD

**Issue by jaqobk** [frappe/bench#696]
hi,

am facing an issue froom Tuesday when I updated my software. the monthly sales not changing as the sales increases and has been stack from then. I did a bench update Yesterday to see if this will be resolved but still total monthly still stuck ..

I attached an image
![target](https://user-images.githubusercontent.com/23546438/42322574-bbe5274e-8065-11e8-8767-af2d078bee68.png)

note: my sale are far beyond figure displayed.
kindly help.

**Comment by codingCoffee** [comment]
Please open an issue in https://github.com/frappe/erpnext/issues/new
