### ISSUE TITLE
Bench Update Cannot Proceed: local changes in app "frappe_io"

### ISSUE THREAD

**Issue by dottenbr** [frappe/bench#697]
`bench update` throws error:

```
Cannot proceed with update: You have local changes in app "frappe_io" that are not committed.
```

This requires a `bench update --reset` to continue.

![image](https://user-images.githubusercontent.com/9136094/42368449-a2411dbe-8139-11e8-9a98-cb348a23d510.png)

**Comment by codingCoffee** [comment]
There must be some uncommitted, auto generated `css` in `frappe_io`. Will commit the changes to `frappe_io` soon.
Try `bench update --reset`
