### ISSUE TITLE
bench update --reset should not be necessary

### ISSUE THREAD

**Issue by rmehta** [frappe/bench#717]
Please gitignore files that are generated for docs so that `--reset` should not be necessary

**Comment by codingCoffee** [comment]
Should we close, and reopen when we have the untacked files ?

**Comment by jodeq** [comment]
It should be great also for translations files
When we do a `bench download-translations` frappe repo and erpnext repo are modified

**Comment by gavindsouza** [comment]
Can't replicate. Closing.
