### ISSUE TITLE
`bench new-site` puts the database password in a world-readable site

### ISSUE THREAD

**Issue by mgedmin** [frappe/bench#73]
I followed the instructions at https://github.com/frappe/bench#bench and discovered that the frappe-bench/sites/site1.local/site_config.json file contains the MariaDB password for the site1.local database and is a world-readable file.  Perhaps that's not the best idea?

**Comment by MaxMorais** [comment]
@pdvyas Maybe it symple recipe can help.
https://charlesleifer.com/blog/creating-a-personal-password-manager/

Do you can store only the rules for get the maria_db password that is generated on demand.

Another thing, for the salt, if the site have a SSL certificate you can use the hash of the certfile, if not you can use a random string generated by the bench on it is installed

**Comment by pdvyas** [comment]
Yes, but this password will be usable only if you connect via localhost. If
you enable access from outside, you will have to make a special GRANT and
that will be another password.

I do agree the perms on site_config.json should be something like 400
