### ISSUE TITLE
Task progress bar (% completion) in the install.py script

### ISSUE THREAD

**Issue by palashjhabak** [frappe/bench#752]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
Sometime some tasks take a long period of time and its hard to figure out if something has gone wrong and its stuck or its still working

**Describe the solution you'd like**
It would be nice to have a progress bar (% completion display) specially for bigger tasks. 

**Additional context**
I am happy to contribute, if someone can guide a little

**Comment by achillesrasquinha** [comment]
install.py is an independent script that expects no dependencies! Besides you could use `pv` to show progress of any script.

**Comment by gavindsouza** [comment]
I realize that I'm really late here but, @palashjhabak would it be possible to work on this now?

**Comment by gavindsouza** [comment]
I tried many "creative" ways of doing this. Progress bars are a hard problem as it is. Also, now that there's no dedicated maintainer for "easy install", I'm closing this.
