### ISSUE TITLE
error when starting bench in a live server

### ISSUE THREAD

**Issue by ashinsukumaran** [frappe/bench#757]
root@ERPNext:/home/frappe/frappe-bench# bench start
06:24:09 system           | worker_long.1 started (pid=19222)
06:24:09 system           | redis_socketio.1 started (pid=19218)
06:24:09 redis_socketio.1 | 19229:M 22 Dec 06:24:09.744 * Increased maximum number of open files to 10032 (it was originally set to 1024).
06:24:09 system           | redis_queue.1 started (pid=19219)
06:24:09 system           | watch.1 started (pid=19221)
06:24:09 redis_queue.1    | 19237:M 22 Dec 06:24:09.755 * Increased maximum number of open files to 10032 (it was originally set to 1024).
06:24:09 system           | schedule.1 started (pid=19232)
06:24:09 redis_queue.1    | 19237:M 22 Dec 06:24:09.761 # Creating Server TCP listening socket 127.0.0.1:11000: bind: Address already in use
06:24:09 system           | redis_queue.1 stopped (rc=1)
06:24:09 redis_socketio.1 | 19229:M 22 Dec 06:24:09.769 # Creating Server TCP listening socket 127.0.0.1:12000: bind: Address already in use
06:24:09 system           | redis_socketio.1 stopped (rc=1)
06:24:09 system           | worker_default.1 started (pid=19227)
06:24:09 system           | redis_cache.1 started (pid=19231)
06:24:09 system           | socketio.1 started (pid=19241)
06:24:09 system           | worker_short.1 started (pid=19235)
06:24:09 system           | web.1 started (pid=19239)
06:24:09 system           | sending SIGTERM to worker_long.1 (pid 19222)
06:24:09 system           | sending SIGTERM to watch.1 (pid 19221)
06:24:09 system           | sending SIGTERM to web.1 (pid 19239)
06:24:09 system           | sending SIGTERM to schedule.1 (pid 19232)
06:24:09 system           | sending SIGTERM to worker_default.1 (pid 19227)
06:24:09 system           | sending SIGTERM to socketio.1 (pid 19241)
06:24:09 system           | sending SIGTERM to redis_cache.1 (pid 19231)
06:24:09 system           | sending SIGTERM to worker_short.1 (pid 19235)
06:24:09 system           | socketio.1 stopped (rc=-15)
06:24:09 system           | worker_default.1 stopped (rc=-15)
06:24:09 system           | worker_long.1 stopped (rc=-15)
06:24:09 system           | redis_cache.1 stopped (rc=-15)
06:24:09 system           | web.1 stopped (rc=-15)
06:24:09 system           | worker_short.1 stopped (rc=-15)
06:24:09 system           | schedule.1 stopped (rc=-15)
06:24:09 system           | watch.1 stopped (rc=-15)

please help me with this issue.
any response is highly appreciated

**Comment by sagarvora** [comment]
Hi, were you able to resolve this?
It looks like a bench is already running on this server.

If you wish to run multiple benches on the same server, ensure that they have different ports in `sites/common_site_config.json`
