### ISSUE TITLE
OpenBSD Support Tasks

### ISSUE THREAD

**Issue by kevlar700** [frappe/bench#769]
Issue: Feature Request
Someday when I have more time, I would like to run erpnext on OpenBSD, for smoother/faster upgrade times and security. Hopefully before the 16.04 support deadline in 2021. OpenBSD would seem to satisfy erpnexts main pre-requisites.

Simple patches would be needed for OpenBSDs init system but I am unsure of what else would be needed.

It would be helpful if people could list from the top of their head, any expected changes that would be required for picking up in the future or known blockers to running Erpnext on OpenBSD.

Thankyou

**Comment by gavindsouza** [comment]
> Hopefully before the 16.04 support deadline in 2021.

Seems like there's still time left. Although I'm unsure if this is active anymore. Closing this issue.
