### ISSUE TITLE
cypress Developers not supporting FreeBSD - Bench does not Install

### ISSUE THREAD

**Issue by chlarsen** [frappe/bench#771]
Issue: Bug report

The cypress developers expressively refuse to include support for FreeBSD. 
I have been running ERPNext successfully in a production environment using FreeBSD, until version 11 introduced cypress as seemingly compulsory requirement. 
This constitutes a total roadblock to the pending upgrade.
A hopefully simple solution would be to split up requirements for production environments vs those for development environments. This could hopefully avoid the need to install incompatible cypress on FreeBSD.
Any thoughts? Thank you,
Chris

**Comment by gavindsouza** [comment]
This has been made optional via https://github.com/frappe/frappe/pull/11489. Cypress doesn't install unless UI tests are being run since Frappe v13
