### ISSUE TITLE
Bug or feature ?

### ISSUE THREAD

**Issue by prashantkt10** [frappe/bench#773]
I had to reinstall bench and ERPNEXT because of some issues. I'm getting different UI from previous one which was having icons. I think I've screwed installation.
Please do confirm if this is new UI.

![screenshot from 2019-02-12 16-29-35](https://user-images.githubusercontent.com/12119425/52630895-6f397080-2ee3-11e9-8618-ef5ef3fe7a8a.png)

**Comment by cgpurbaugh** [comment]
It is in fact the new UI.  You must be on V12 erpnext.
