### ISSUE TITLE
Easy Install instructions need update. (simple fix)

### ISSUE THREAD

**Issue by bkm888** [frappe/bench#774]
The Easy Install instructions currently listed on the github frappe/bench page tell users to install all of the old python2.x packages before running the install.py script.

python 2.x is to be retired very, very soon and the install.py text that runs donw the screen displays a huge red section warning that it is about to be unsupported. This would possibly create a great deal of confusion for the newest of users (the ones that use the Easy Install instructions).

Can someone change the instructions to install the correct python 3.x pre-requisites instead. This would save a bunch of time and traffic. If I knew what those pre-requisites should be, I would offer them up here to make the text change that much easier.

Thanks,

BKM

**Comment by codecakes** [comment]
Just wanted to know if migration to python 3 already begun?

**Comment by gavindsouza** [comment]
Fixed in https://github.com/frappe/bench/pull/887
