### ISSUE TITLE
Install Frappe from local filesystem

### ISSUE THREAD

**Issue by Dremor** [frappe/bench#777]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
I'm currently trying to make an alpine-based Docker ERPNext image (I know there is already some other Docker image, but I do this for fun). As such, I could have to do some change to Frappe or ERPNext in order to make it work on this "exotic" base.

I started to work using git submodules (and patches), in order to keep as close as possible to upstream (as seen here : https://lab.dremor.info/egeorget/erpnext-docker/tree/feature/research). But Bench do not allow to install Frappe from a local filesystem (or a local git repository in this case), which prevent this project topology to work.

**Describe the solution you'd like**
I would like to be able to get Frappe (or any bench app) from a local directory (being a local filesystem or a local git repository).

**Comment by gavindsouza** [comment]
Possible solution:

move the app to `{bench-folder}/apps` and add it to `apps.txt` under `{bench-folder}/sites`

then proceed to `bench --site {site-name} {app}`

**Comment by gavindsouza** [comment]
Resolved in #900

**Comment by zeelrupapara** [comment]
This solution works for me:
I used the `file` protocol to get the app in the bench (for local file transfer)
`bench get-app file:///home/custom-app`

**Comment by varun-krishnamurthy** [comment]
This is not working anymore. 

frappe@3da05a912878:/workspace/development/frappe-bench/apps$ bench --version
5.17.2

frappe@3da05a912878:/workspace/development/frappe-bench/apps$ bench get-app file://tmp/hrms/
ERROR: file: not found in frappe or erpnext
Traceback (most recent call last):
  File "/home/frappe/.bench/bench/utils/__init__.py", line 437, in fetch_details_from_tag
    org, repo = org_repo
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/.local/bin/bench", line 8, in <module>
    sys.exit(cli())
  File "/home/frappe/.bench/bench/cli.py", line 132, in cli
