### ISSUE TITLE
Confusing bench releases across GitHub and PyPI

### ISSUE THREAD

**Issue by salmanulfarzy** [frappe/bench#778]
Bit confused about the release process of bench across GitHub and PyPI.

|Latest Release|Version|Date|Diff|
|-|:-:|:-:|:-:|
|GitHub | v4.1 | Aug 3, 2016 | [516 Behind master][1] |
|PyPI | v4.1.2 | Nov 6, 2017 | ??  |

Will there be any new synchronized release across GitHub and PyPi, Because there are tons of useful features in `master` like #638 missing from these releases.

[1]: https://github.com/frappe/bench/compare/4.1...master

**Comment by gavindsouza** [comment]
We haven't released bench on PYPI for quite some time. Currently only source installs are supported but we will soon be releasing bench v5.0 on PYPI and work out a consistent release cycle.


Closing this issue now
