### ISSUE TITLE
ERROR ON initial SETUP

### ISSUE THREAD

**Issue by msalim79** [frappe/bench#782]
ERPNEXT-Production -20180331183346
With ubuntu(64-bit)...ova
Download and ran the ova , logged in with administrator.
Setup wizard pops up....at step http://localhost:8080/desk#setup-wizard/5
I get a message .. A page is slowing down your browser , What would you like to do ? Stop or Wait.

Doesnt go any where after this , just hangs.

This happens in all browsers.Ive tried a to update bench but get a --
![benchupdateerror](https://user-images.githubusercontent.com/30749464/54232549-8cc61e00-4513-11e9-9945-f7d1c5935d42.PNG)

Thanks

**Comment by gavindsouza** [comment]
Seems like a network issue.

Closing this
