### ISSUE TITLE
App crashes at on-boarding when password strength criteria not matched

### ISSUE THREAD

**Issue by LahiruBandara** [frappe/bench#797]
Issue: Bug report

Evaluating your product and I must say I'm already in love with it. Thank you very much for making such a wonderful project an OpenSource one. 

Below is the issue. 

When you initially install the app and run it, on-boarding wizard loads. However, when the password strength criteria is not matched, UI isn't showing an error on the spot, instead give the error on finish (see screenshot). 

When a strong password is given no issues at all. (Alphanumeric + Special Key  works like a charm)

****
<img width="1379" alt="Screen Shot 2019-04-30 at 5 41 15 PM" src="https://user-images.githubusercontent.com/10897961/56961035-4040ab80-6b70-11e9-96cc-a3057d2ed1c2.png">
<img width="1379" alt="Screen Shot 2019-04-30 at 5 42 44 PM" src="https://user-images.githubusercontent.com/10897961/56961036-40d94200-6b70-11e9-9c12-b95686bdd6e2.png">

**Comment by gavindsouza** [comment]
Glad you're enjoying Frappe + ERPNext :)

Sorry for the delayed response. It's been long since this issue was reported and it's been fixed over time. Thank you for your contribution!
