### ISSUE TITLE
Easy installer to support Debian 10

### ISSUE THREAD

**Issue by lasalesi** [frappe/bench#831]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**
The current stable Debian version is version 10. Easy install will fail with "Sorry, the installer doesn't support debian 10. Aborting. Install on debian 9 instead"

**Describe the solution you'd like**
The easy install script should work on Debian 10

**Describe alternatives you've considered**
Installing Debian 9, then the easy install, with upgrading to Debian 10. Is rather cumbersome.

**Additional context**
https://www.debian.org/releases/

**Comment by MartinVerges** [comment]
please add this, debian 10 is great and not supporting it is rather unsatisfying

**Comment by marcogabriel** [comment]
I just created a patch for it. tested with debian 10 on kvm and lxc containers. pull request comes in a minute.

**Comment by Thunderbottom** [comment]
fixed with #872.
