### ISSUE TITLE
Bench shouldn't expect everything to be installed on the same machine 

### ISSUE THREAD

**Issue by alexsegura** [frappe/bench#837]
Issue: Feature Request

Related to frappe/frappe#8280

**Is your feature request related to a problem? Please describe.**

I have been trying to install ERPNext on an existing infrastructure (Debian). 
On the infrastructure I have, I already have a monitored server hosting "databases" (i.e, Redis, Postgres, MariaDB...), and web servers running Nginx/other stuff. Pretty classic setup, I believe. 

I'm still pretty new to Frappe/ERPNext, but from what I see, by default it expects everything to be installed on the same machine. It shouldn't be like this 😕 

When running `bench init`, I had to add `--skip-redis-config-generation`, that's (quite) fine.

I have edited `common_site_config.json` with my Redis DSNs, but when I run `bench start`, I have the following errors: 
```
15:45:40 system           | redis_socketio.1 started (pid=31434)
15:45:40 redis_socketio.1 | /bin/sh: 1: redis-server: not found
15:45:40 system           | redis_socketio.1 stopped (rc=127)
15:45:40 system           | worker_long.1 started (pid=31442)
15:45:40 system           | worker_default.1 started (pid=31446)
15:45:40 system           | redis_queue.1 started (pid=31444)
15:45:40 redis_queue.1    | /bin/sh: 1: redis-server: not found
15:45:40 system           | redis_queue.1 stopped (rc=127)
15:45:40 system           | watch.1 started (pid=31437)
15:45:40 system           | socketio.1 started (pid=31447)
15:45:40 system           | web.1 started (pid=31441)
15:45:40 system           | redis_cache.1 started (pid=31458)
15:45:40 redis_cache.1    | /bin/sh: 1: redis-server: not found
15:45:40 system           | redis_cache.1 stopped (rc=127)
15:45:40 system           | worker_short.1 started (pid=31451)
15:45:40 system           | schedule.1 started (pid=31449)
15:45:40 system           | sending SIGTERM to worker_long.1 (pid 31442)
15:45:40 system           | sending SIGTERM to watch.1 (pid 31437)
15:45:40 system           | sending SIGTERM to web.1 (pid 31441)
15:45:40 system           | sending SIGTERM to schedule.1 (pid 31449)
15:45:40 system           | sending SIGTERM to worker_default.1 (pid 31446)
15:45:40 system           | sending SIGTERM to socketio.1 (pid 31447)
15:45:40 system           | sending SIGTERM to worker_short.1 (pid 31451)
15:45:40 system           | schedule.1 stopped (rc=-15)
15:45:40 system           | worker_long.1 stopped (rc=-15)
15:45:40 system           | watch.1 stopped (rc=-15)
15:45:40 system           | worker_short.1 stopped (rc=-15)
15:45:40 system           | web.1 stopped (rc=-15)
15:45:40 system           | socketio.1 stopped (rc=-15)
15:45:40 system           | worker_default.1 stopped (rc=-15)
```

The only solution that I found, was runing `bench serve --port 8000 --noreload` instead. 

**Describe the solution you'd like**

I expected to find a Docker image running ERPNext out-of-the-box, i.e ONLY ERPNext (i.e, the app). I was expecting to give it the host/ports of my databases (through environment variables), and voilà. 

But unfortunately even [erpnext-docker-debian](https://github.com/pipech/erpnext-docker-debian) installs MariaDB on the same machine that is running the app. 

**Describe alternatives you've considered**

I have considered creating a Docker image containing ONLY ERPNext, but I'm not even sure it's possible.

**Comment by flatline-studios** [comment]
^^ This. It's not the 90s anymore. Separation of concerns, microservices and distributed apps have been the industry standard for over a decade now.

On a sidenote, I've had some luck (not too much though), installing `redis-cli` (probably a part of the `redis` package for your given distribution), and changing the first three lines in the `Procfile` to read (obviously adapted to your own naming convention):

```
redis_cache: redis-cli -h ${REDIS_CACHE__HOST} -p ${REDIS_CACHE__PORT}
redis_socketio: redis-cli -h ${REDIS_SOCKETIO__HOST} -p ${REDIS_SOCKETIO__PORT}
redis_queue: redis-cli -h ${REDIS_QUEUE__HOST} -p ${REDIS_QUEUE__PORT}
```

For example, to get the redis cache's separated. It seems to work (`bench start` runs without error, and stuff gets put in to the redis cache's), but the web server is inaccessible, so still not quite right.

**Comment by PMojito** [comment]
I've been commenting those 3 lines out of my Procfile.  And just launching my Redis separately, each in its own Docker container.

You're both quite correct.  There should be options (installation, post-installation), to indicate where sub-components exist.  So you can divide the services across multiple machines/VMs/containers.

This is currently all possible, but it requires a **lot** of different knowledge and skills:  ERPNext configuration, how Python web frameworks work, Procfiles, Unix sockets, Ansible, and much more.

It's too complex for anyone not already immersed in the ecosystem.

We need a new kind of Bench.  More specifically, Bench needs to be broken apart into separate programs, and updated for 2019.

Do One Thing, Do It Well.  

Instead of Bench doing 5 or 6 things mediocre (installation, configuration, upgrade, git shortcuts, patch management, launching applications, etc.)

**Comment by yashodhank** [comment]
Pull requests are welcome!
Please open thread at https://discuss.erpnext.com/ for discussion, we prefere to use github issues only for handling bugs reports. Thanks for understanding.
