### ISSUE TITLE
Build 56 Fail

### ISSUE THREAD

**Issue by henrynewman** [frappe/bench#839]
Easy install and installation of frappe failing because of this error. Please recommend a fix. 

`E: Unable to locate package libssl1.0-dev
E: Couldn't find any package by regex 'libssl1.0-dev'
Traceback (most recent call last):
  File "/home/circleci/repo/playbooks/install.py", line 413, in <module>
    install_bench(args)
  File "/home/circleci/repo/playbooks/install.py", line 21, in install_bench
    'sudo yum install -y epel-release redhat-lsb-core git python-setuptools python-devel openssl-devel libffi-devel'
  File "/home/circleci/repo/playbooks/install.py", line 226, in run_os_command
    returncode = subprocess.check_call(command, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sudo apt-get install -y git build-essential python3-setuptools python3-dev libffi-dev libssl1.0-dev' returned non-zero exit status 100
Exited with code 1`

[See more at CircleCI](https://circleci.com/gh/frappe/bench/56)

**Comment by aldoblack** [comment]
You have to replace `libssl1.0-dev` to `libssl-dev` on **install.py** and **debian_family.yml** files.

**Comment by jvfiel** [comment]
@aldoblack after I edited the files, and ran the script again I experience another error 

1) The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required.”
-so I installed sudo pip install pymysql
2) I rerun the script again and:
unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, u\"Access denied for user 'root'@'localhost' (using password: YES)\")

Any ideas?

**Comment by henrynewman** [comment]
> libssl-dev

Done, thank you for your assistance.

**Comment by henrynewman** [comment]
@jvfiel was this a new installation?

**Comment by aldoblack** [comment]
> @aldoblack after I edited the files, and ran the script again I experience another error
> 
> 1. The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required.”
>    -so I installed sudo pip install pymysql
> 2. I rerun the script again and:
>    unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, u"Access denied for user 'root'@'localhost' (using password: YES)")
> 
> Any ideas?

I do not know and I do not think this has to do with the error mentioned in the first place.
I believe that the script is trying to login with the wrong root password of mysql.

**Comment by henrynewman** [comment]
@jvfiel please post a new issue to receive assistance from the community.
