### ISSUE TITLE
 easy install, TASK [mariadb : Set root Password] error

### ISSUE THREAD

**Issue by chendelin1982** [frappe/bench#862]
**OS:** Ubuntu18.04,
**Installation solution:** easy install, `python install.py --production --user frappe`

error:
TASK [mariadb : Set root Password]
"msg": "The PyMySQL (Python 2.7 and Python 3.X) or MySQL-python (Python 2.X) module is required."

**Comment by yashodhank** [comment]
This seems to be one of instances when apt fails to fetch package due bad connection or previously installed older lib version.
Closing for now, feel free to re-open with full log (using privatebin.net) or start thread at discuss.erpnext.com
