### ISSUE TITLE
ERROR: frontmatter 3.0.5 has requirement PyYAML==3.13, but you'll have pyyaml 5.1 which is incompatible.

### ISSUE THREAD

**Issue by chengdada123** [frappe/bench#927]
ERROR: frontmatter 3.0.5 has requirement PyYAML==3.13, but you'll have pyyaml 5.1 which is incompatible.
but 
ERROR: frappe 12  has requirement PyYAML==5.1, but you'll have pyyaml 3.13 which is incompatible.

**Comment by gavindsouza** [comment]
Will be fixed when https://github.com/jonbeebe/frontmatter/pull/8 is merged
