### ISSUE TITLE
add options for use in dev docker container 

### ISSUE THREAD

**Issue by revant** [frappe/bench#949]
Issue: Feature Request

**Is your feature request related to a problem? Please describe.**

mariadb and redis need changes for dev docker container

**Describe the solution you'd like**
bench init --skip-redis-config-generation should not create redis config in procfile

bench setup procfile --skip-redis-config-generation
 - no redis in procfile

bench new-site --no-mariadb-socket ...
 - https://stackoverflow.com/a/10823868
 - check the db_type is mariadb
 - after site creation, read db_name and db_password from site_config.json 
 - create site user db_name @ `%`

```sql
UPDATE mysql.user SET Host = '%' where User = '{db_name}'; FLUSH PRIVILEGES;
```
 - set password for db_name @ `%`
```sql
SET PASSWORD FOR '{db_name}'@'%' = PASSWORD('{db_password}'); FLUSH PRIVILEGES;
```
 - grant privileges to new site user to the site database

```
GRANT ALL PRIVILEGES ON \`{db_name}\`.* TO '{db_name}'@'%'; FLUSH PRIVILEGES;
```

**Describe alternatives you've considered**
adding a script in docker image itself. It becomes two commands.

```sh
bench setup procfile
dockerize_procfile Procfile

bench new-site test.localhost
no_socket_mariadb test.localhost
```

**Comment by Thunderbottom** [comment]
closing this issue since everything has been fixed! :)
