### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'dist'

### ISSUE THREAD

**Issue by physiii** [frappe/bench#981]
Issue: Easy Install

Having issues with the "easy installer."

Is this error because I'm using 20.04? How do I by pass? 

$ sudo python3 install.py
Logs are saved under /tmp/logs/easy-install__2020-05-02__18-20.log
Traceback (most recent call last):
  File "install.py", line 433, in <module>
    check_distribution_compatibility()
  File "install.py", line 78, in check_distribution_compatibility
    dist_name, dist_version = get_distribution_info()
  File "install.py", line 100, in get_distribution_info
    current_dist = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'

```
$ uname -a
Linux office 5.4.0-28-lowlatency #32-Ubuntu SMP PREEMPT Wed Apr 22 18:35:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Comment by Alchez** [comment]
Which Python version are you on? Seems like [`platform.dist()` was removed in 3.8](https://docs.python.org/3.6/library/platform.html#platform.dist).

**Comment by kevinpthorne** [comment]
> Which Python version are you on? Seems like [`platform.dist()` was removed in 3.8](https://docs.python.org/3.6/library/platform.html#platform.dist).

Just reproduced the same error tonight with `Python 3.8.2` on a fresh install of Ubuntu 20.04

**Comment by nikunj1222** [comment]
To go through the installation on ubuntu 20.04 please follow the step mentioned on the forum link below : 

https://discuss.erpnext.com/t/easy-install-setup-guide-for-erpnext-installation-on-ubuntu-20-04-lts-with-some-modification-of-course/62375/2

**Comment by gavindsouza** [comment]
Should be fixed with https://github.com/frappe/bench/pull/1048
